import { REGISTRY_BASE, PROFILES_URL, $, state, fetchJSON, option, setBusy, showError, persistSelection } from './state.js';
import { ensureCatalog, ensureRigFacts, ensureProblems, renderMetrics } from './registry.js';
import { searchRegistry } from './search.js';
import { setResultView, renderResults, showDetail } from './render.js';
import { updateSelectionUI, renderConsumerBoundary, buildHandoff, copyText, downloadJSON } from './selection.js';
import { fitCamera, setWireframe, playClip, animationState } from './preview.js';

export async function runSearch(){const result=await searchRegistry();state.lastResults=result.rows;renderResults(result.rows);$('resultMeta').classList.remove('error');$('resultMeta').textContent=`${result.rows.length.toLocaleString()} shown · ${result.total.toLocaleString()} matches · limit 120`;return result;}
function resetFilters(){for(const id of ['searchInput','kindFilter','packFilter','collectionFilter','formatFilter','dependencyFilter','problemFilter','rigFilter','animatedFilter','clipFilter','jointFilter'])$(id).value='';state.lastResults=[];$('resultList').replaceChildren();$('resultMeta').textContent='Enter a query or choose filters.';}
async function bootstrap(){try{setBusy(true,'Loading manifest…');const [manifest,packs,profileDoc,rigSummary]=await Promise.all([fetchJSON(`${REGISTRY_BASE}/manifest.json`),fetchJSON(`${REGISTRY_BASE}/packs/index.json`),fetchJSON(PROFILES_URL),fetchJSON(`${REGISTRY_BASE}/rigfacts-summary.json`,true)]);state.manifest=manifest;state.packs=packs;state.profiles=profileDoc.profiles||{};state.rigSummary=rigSummary;$('sourceCommit').textContent=manifest.sourceCommit||'';$('packFilter').replaceChildren(option('','All packs'),...packs.map((p)=>option(p.packId,p.packId)));$('consumerSelect').replaceChildren(...Object.entries(state.profiles).map(([id,p])=>option(id,p.displayName||id)));renderMetrics();renderConsumerBoundary();setResultView(state.viewMode);updateSelectionUI();setBusy(false);}catch(e){document.body.classList.remove('loading');$('registryStatus').textContent='Registry unavailable';$('registryStatus').classList.add('error');$('resultMeta').textContent=`Registry unavailable: ${e.message}`;}}
$('searchButton').onclick=()=>runSearch().catch(showError);$('searchInput').onkeydown=(e)=>{if(e.key==='Enter')runSearch().catch(showError);};$('resetButton').onclick=resetFilters;$('listViewButton').onclick=()=>setResultView('list');$('galleryViewButton').onclick=()=>setResultView('gallery');
$('clearSelection').onclick=()=>{state.selected.clear();persistSelection();updateSelectionUI();renderResults(state.lastResults);if(state.active)$('toggleSelection').textContent='Add';};$('consumerSelect').onchange=renderConsumerBoundary;$('copyHandoff').onclick=async()=>copyText(JSON.stringify(await buildHandoff(),null,2)+'\n');$('downloadHandoff').onclick=async()=>downloadJSON(`kfb-asset-handoff-${$('consumerSelect').value}.json`,await buildHandoff());
$('resetCamera').onclick=fitCamera;$('fitCamera').onclick=fitCamera;$('wireframeToggle').onchange=(e)=>setWireframe(e.target.checked);$('autoplayToggle').onchange=(e)=>{const {mixer,loadedAnimations}=animationState();if(!loadedAnimations.length)return;if(e.target.checked){const i=Number($('clipSelect').value||0);$('clipSelect').value=String(i);playClip(i);}else if(mixer){mixer.stopAllAction();$('previewStatus').textContent=`${loadedAnimations.length} clip(s) · paused`;}};$('clipSelect').onchange=(e)=>{if(e.target.value==='')return;$('autoplayToggle').checked=true;playClip(Number(e.target.value));};
document.addEventListener('kfb-open-asset',(e)=>showDetail(e.detail).catch(showError));
window.KFBAssetLibrarianV12={version:'1.2',runSearch,showDetail,buildHandoff,ensureCatalog,ensureRigFacts,ensureProblems,getState:()=>({selectedAssetIds:[...state.selected].sort(),activeAssetId:state.active,viewMode:state.viewMode,sourceCommit:state.manifest?.sourceCommit||null})};
updateSelectionUI();bootstrap();
