import { $, formatBytes, formatDuration } from './state.js';
import { clear3D, render3D } from './preview3d.js';
export { fitCamera, setWireframe, playClip, animationState } from './preview3d.js';
function resetMedia(){const a=$('audioPlayer');a.pause();a.removeAttribute('src');a.load();$('imagePreviewImg').removeAttribute('src');$('imagePreview').hidden=true;$('audioPreview').hidden=true;$('dataPreview').hidden=true;}
export function clearPreview(){clear3D();resetMedia();}
function image(record){$('imagePreview').hidden=false;$('previewTitle').textContent='Image / texture preview';$('previewStatus').textContent='Loading…';const img=$('imagePreviewImg');img.onload=()=>{$('previewStatus').textContent='Loaded';$('imageMeta').textContent=`${img.naturalWidth} × ${img.naturalHeight}px · ${record.format}`;};img.onerror=()=>{$('previewStatus').textContent='Preview failed';};img.src=record.source?.rawPinned||record.source?.rawLatest||'';}
function audio(record){$('audioPreview').hidden=false;$('previewTitle').textContent='Audio preview';$('previewStatus').textContent='Ready';const a=$('audioPlayer');a.src=record.source?.rawPinned||record.source?.rawLatest||'';a.onloadedmetadata=()=>{$('audioMeta').textContent=`${formatDuration(a.duration)} · ${record.format} · ${formatBytes(record.sizeBytes)}`;};a.onerror=()=>{$('audioMeta').textContent=`Metadata unavailable · ${record.format} · ${formatBytes(record.sizeBytes)}`;};a.load();}
function data(record){$('dataPreview').hidden=false;$('previewTitle').textContent='Metadata preview';$('previewStatus').textContent='Metadata only';$('dataPreview').textContent=`${record.format.toUpperCase()} · ${formatBytes(record.sizeBytes)} · open pinned RAW for source.`;}
export async function renderPreview(record){clearPreview();$('previewWrap').hidden=false;if(record.kind==='model-3d'&&['glb','gltf'].includes(record.format))return render3D(record);if(record.kind==='image-2d')return image(record);if(record.kind==='audio')return audio(record);return data(record);}
