import { $, state, badge, formatBytes, showError } from './state.js';
import { ensureCatalog, ensureRigFacts, ensureProblems } from './registry.js';
import { renderPreview } from './preview.js';
import { toggleSelected } from './selection.js';
const depBadge=(r)=>r.dependencyStatus?badge(r.dependencyStatus,['missing','unresolved'].includes(r.dependencyStatus)?'warn':'ok'):null;
const rigBadge=(r)=>r.rigFacts?.hasSkin?badge(`rig ${r.rigFacts.jointCount||0}j`,'ok'):null;
const reviewBadge=(r)=>{const n=(state.problemsByAsset.get(r.assetId)||[]).length;return n?badge(`${n} review`,'problem'):null;};
export function setResultView(mode){state.viewMode=mode==='gallery'?'gallery':'list';localStorage.setItem('kfb.asset-librarian.v1.2.view',state.viewMode);$('resultList').classList.toggle('gallery-view',state.viewMode==='gallery');$('resultList').classList.toggle('list-view',state.viewMode!=='gallery');$('listViewButton').classList.toggle('active',state.viewMode==='list');$('galleryViewButton').classList.toggle('active',state.viewMode==='gallery');renderResults(state.lastResults);}
function thumb(r,target){
  target.replaceChildren();
  if(r.kind==='image-2d'){
    const img = document.createElement('img');
    img.loading = 'lazy';
    img.alt = '';
    img.src = r.source?.rawPinned || r.source?.rawLatest || '';
    target.append(img);
  }else{
    const s=document.createElement('span');
    s.className='thumb-label';
    s.textContent=r.kind==='model-3d'?'3D':r.kind==='audio'?'AUDIO':String(r.format||'FILE').toUpperCase();
    target.append(s);
  }
}
export function renderResults(records){const list=$('resultList'),tpl=$('resultTemplate');list.replaceChildren();for(const r of records){const f=tpl.content.cloneNode(true),card=f.querySelector('.result-card'),cb=f.querySelector('.result-select');card.dataset.assetId=r.assetId;f.querySelector('.result-title').textContent=r.name;f.querySelector('.result-subtitle').textContent=[r.packId,r.collectionPath].filter(Boolean).join(' · ')||'unpacked';f.querySelector('.result-path').textContent=r.path;f.querySelector('.result-meta-line').textContent=formatBytes(r.sizeBytes);thumb(r,f.querySelector('.result-thumb'));const badges=f.querySelector('.result-badges');badges.append(badge(r.kind),badge(r.format));for(const b of [depBadge(r),rigBadge(r),reviewBadge(r)])if(b)badges.append(b);cb.checked=state.selected.has(r.assetId);cb.onchange=()=>toggleSelected(r.assetId,cb.checked);f.querySelector('.result-open').onclick=()=>showDetail(r.assetId).catch(showError);if(state.active===r.assetId)card.classList.add('active');list.append(f);}}
const fact=(value,label)=>{const d=document.createElement('div');d.className='fact';const b=document.createElement('b');b.textContent=value==null||value===''?'—':String(value);const s=document.createElement('span');s.textContent=label;d.append(b,s);return d;};
function dependencies(r){const box=$('dependencyFacts'),deps=r.relations?.dependencies||[];if(!deps.length){box.textContent=r.dependencyStatus?`No explicit rows · ${r.dependencyStatus}`:'No explicit dependency facts.';return;}const ul=document.createElement('ul');ul.className='dependency-list';for(const d of deps){const li=document.createElement('li');li.className='dependency-row';li.textContent=`${d.role||'dependency'} · ${d.status||(d.exists?'complete':'unknown')} · ${d.path||d.resolvedPath||d.uri||'unknown'}`;const target=d.path||d.resolvedPath;if(target&&state.catalogById?.has(target)){const b=document.createElement('button');b.textContent='Inspect';b.className='quiet small-button';b.onclick=()=>showDetail(target).catch(showError);li.append(b);}ul.append(li);}box.replaceChildren(ul);}
function rig(r){const x=r.rigFacts,box=$('rigFacts'),warn=$('rigWarnings');warn.hidden=true;if(!x){box.textContent='Rig facts not loaded.';return;}box.replaceChildren(fact(x.parseStatus,'parse status'),fact(x.hasSkin,'has skin'),fact(x.jointCount||0,'joints'),fact(x.animationCount||0,'animations'),fact((x.animationClips||[]).map((c)=>c.name).filter(Boolean).join(', ')||'none','clips'),fact((x.skeletonSignatures||[]).join(', ')||'none','skeleton signature'));if(x.hasSkin||x.skeletonSignatures?.length){warn.hidden=false;warn.textContent='Skeleton signature is structural evidence only; not a retarget/gameplay compatibility guarantee.';}}
function problems(r){const rows=state.problemsByAsset.get(r.assetId)||[],box=$('problemFacts');if(!rows.length){box.textContent='No current review item mapped to this asset.';return;}const ul=document.createElement('ul');for(const p of rows){const li=document.createElement('li');li.className='problem-row';li.textContent=[p.type,p.target,p.detail].filter(Boolean).join(' · ');ul.append(li);}box.replaceChildren(ul);}
export async function showDetail(id){await ensureCatalog();const r=state.catalogById.get(id);if(!r)throw new Error(`Unknown asset: ${id}`);if(r.kind==='model-3d'){await ensureRigFacts();r.rigFacts=state.rigById.get(id)||r.rigFacts;}await ensureProblems();state.active=id;$('emptyDetail').hidden=true;$('detailContent').hidden=false;$('detailKind').textContent=`${r.kind} · ${r.format}`;$('detailName').textContent=r.name;$('detailPath').textContent=r.path;$('detailBadges').replaceChildren(badge(r.packId||'no pack'),badge(r.collectionPath||'no collection'));for(const b of [depBadge(r),rigBadge(r),reviewBadge(r)])if(b)$('detailBadges').append(b);$('openRaw').href=r.source?.rawPinned||'#';$('openLatestRaw').href=r.source?.rawLatest||'#';$('copyRaw').onclick=()=>navigator.clipboard?.writeText(r.source?.rawPinned||'');$('copyPath').onclick=()=>navigator.clipboard?.writeText(r.path);$('copyAssetId').onclick=()=>navigator.clipboard?.writeText(r.assetId);$('toggleSelection').textContent=state.selected.has(id)?'Remove':'Add';$('toggleSelection').onclick=()=>toggleSelected(id);$('identityFacts').replaceChildren(fact(r.assetId,'asset ID'),fact(r.kind,'kind'),fact(r.format,'format'),fact(formatBytes(r.sizeBytes),'size'),fact(r.packId||'unknown','pack'),fact(r.collectionPath||'—','collection'));dependencies(r);rig(r);problems(r);const s=r.source||{};$('provenanceFacts').replaceChildren(fact(s.repo||state.manifest?.sourceRepo,'source repo'),fact(s.commit||state.manifest?.sourceCommit,'source commit'),fact(s.blobSha||'unknown','blob SHA'),fact(r.license||r.sourceLicense||'unknown','license/source metadata'));await renderPreview(r);renderResults(state.lastResults);}
