import { $, state, persistSelection } from './state.js';
import { ensureCatalog, ensureRigFacts } from './registry.js';
export function toggleSelected(assetId, force = !state.selected.has(assetId)) { if(force)state.selected.add(assetId);else state.selected.delete(assetId);persistSelection();updateSelectionUI();document.querySelectorAll('.result-card').forEach((c)=>{if(c.dataset.assetId===assetId)c.querySelector('.result-select').checked=state.selected.has(assetId);}); }
export function updateSelectionUI(){const n=state.selected.size;$('selectionCount').textContent=`${n} selected`;$('clearSelection').disabled=n===0;$('copyHandoff').disabled=n===0;$('downloadHandoff').disabled=n===0;renderTray();}
export function renderTray(){const target=$('trayItems');if(!target)return;target.replaceChildren();if(!state.selected.size){const s=document.createElement('span');s.className='small-note';s.textContent='No assets selected.';target.append(s);return;}for(const id of [...state.selected].sort()){const r=state.catalogById?.get(id),chip=document.createElement('div');chip.className='tray-chip';const open=document.createElement('button');open.type='button';open.className='open-selected';open.textContent=r?.name||id;open.title=id;open.onclick=()=>document.dispatchEvent(new CustomEvent('kfb-open-asset',{detail:id}));const x=document.createElement('button');x.type='button';x.textContent='×';x.title='Remove from tray';x.onclick=()=>toggleSelected(id,false);chip.append(open,x);target.append(chip);}}
export function renderConsumerBoundary(){const p=state.profiles[$('consumerSelect').value],t=$('consumerBoundary');t.replaceChildren();if(!p)return;const strong=document.createElement('strong');strong.textContent=p.ownerBoundary||'Receiving consumer owns suitability.';t.append(strong);if(p.requiredDownstreamValidation?.length){const ul=document.createElement('ul');for(const text of p.requiredDownstreamValidation){const li=document.createElement('li');li.textContent=text;ul.append(li);}t.append(ul);}}
export async function buildHandoff(){await ensureCatalog();const consumerId=$('consumerSelect').value,p=state.profiles[consumerId]||{},assets=[...state.selected].map((id)=>state.catalogById.get(id)).filter(Boolean);if(assets.some((r)=>r.kind==='model-3d'))await ensureRigFacts();const allowed=new Set(p.allowedKinds||[]);return{schema:'kfb.asset-handoff.v1',sourceRepo:state.manifest.sourceRepo,sourceCommit:state.manifest.sourceCommit,consumer:{consumerId,...p},selectionStatus:'candidate-only',suitabilityDecision:'owned-by-receiving-consumer',assets:assets.map((r)=>({assetId:r.assetId,name:r.name,path:r.path,kind:r.kind,format:r.format,sizeBytes:r.sizeBytes,packId:r.packId,collectionPath:r.collectionPath,dependencyStatus:r.dependencyStatus,source:r.source,relations:r.relations,rigFacts:state.rigById?.get(r.assetId)||r.rigFacts||null,consumerKindAllowed:allowed.size?allowed.has(r.kind):true}))};}
export function downloadJSON(name,value){const blob=new Blob([JSON.stringify(value,null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export async function copyText(text){if(!text)return;if(navigator.clipboard?.writeText)return navigator.clipboard.writeText(text);const a=document.createElement('textarea');a.value=text;a.style.position='fixed';a.style.opacity='0';document.body.append(a);a.select();document.execCommand('copy');a.remove();}
