import fs from 'node:fs';
import crypto from 'node:crypto';
const root=new URL('../../../../',import.meta.url);
const read=p=>fs.readFileSync(new URL(p,root),'utf8');
const manifest=JSON.parse(read('extensions/kfb-legacy-web-pet/manifest.json'));
const sources=read('kfb-hub/shared/legacy-web-pet/sources.js');
const host=read('kfb-hub/shared/legacy-web-pet/host.js');
const frame=read('kfb-hub/shared/legacy-web-pet/frame-runtime.js');
const adapter=read('kfb-hub/shared/legacy-web-pet/legacy-rig-adapter.v1.js');
const hub=read('kfb-hub/index.html');
const extFrame=read('extensions/kfb-legacy-web-pet/frame.html');
let pass=0,fail=0;const ok=(x,m)=>{if(x){pass++;console.log('PASS',m)}else{fail++;console.error('FAIL',m)}};
const gitBlob=s=>crypto.createHash('sha1').update(Buffer.concat([Buffer.from('blob '+Buffer.byteLength(s)+'\0'),Buffer.from(s)])).digest('hex');
ok(manifest.manifest_version===3,'Manifest V3');
ok(manifest.content_scripts?.[0]?.matches?.includes('<all_urls>'),'extension targets arbitrary websites');
ok(manifest.host_permissions?.includes('https://raw.githubusercontent.com/*'),'remote asset host permission only');
ok(!/https?:\/\//.test(extFrame),'extension frame executes no remote code');
ok(hub.includes('/kfb-hub/shared/legacy-web-pet/hub-mount.js'),'KFB Hub mounts pet by default');
ok(sources.includes("CHARACTER_PIN='eb48f50489b9e4903ec1e3d2fb1837605ce7d792'"),'Dungeon source pin exact');
ok(sources.includes("LEGACY_PIN='10a7fdce6b3a1ae22504ade71b7dbec5f25e0ff0'"),'Legacy rig/warband pin exact');
ok(['orc_banner.gltf.glb','orc_sword.gltf.glb','orc_shield.gltf.glb','orc_hammerAxe.gltf.glb'].every(x=>sources.includes(x)),'real Orc Warband camp sources');
ok(['Wave','Cheer','Dance','Hop','Roll','AttackSpinning','HeavyAttack'].every(x=>sources.includes(x)),'click pool uses real Legacy clip names');
ok(frame.includes('THREE.ShadowMaterial')&&frame.includes('shadowMap.enabled=true'),'real 3D shadow path');
ok(frame.includes("post('clip'")&&frame.includes('spawnBurst()'),'click action reports clip and spawns VFX');
ok(host.includes("addEventListener('contextmenu'")&&host.includes('Character'),'right-click character settings present');
ok(host.includes('AudioContext')||host.includes('webkitAudioContext'),'user-click procedural SFX present');
ok(host.includes('pointer-events:none')&&host.includes('pointer-events:auto'),'overlay preserves page pointer access outside hitboxes');
ok(gitBlob(adapter)==='41ba111d264cb73f2b3fbd70370dbb0ba042c91d','vendored Legacy adapter matches proven donor blob');
console.log(`LEGACY_WEB_PET_STATIC_RESULT ${pass}/${pass+fail} PASS`);if(fail)process.exit(1);
