import {chromium} from 'playwright';
import fs from 'node:fs/promises';
const BASE=process.env.KFB_PET_BASE||'http://127.0.0.1:4173';
const OUT=process.env.KFB_PET_EVIDENCE||'legacy-web-pet-evidence/web';
await fs.mkdir(OUT,{recursive:true});
const checks=[],errors=[],failed=[];const check=(n,c,e='')=>{checks.push({name:n,pass:!!c,extra:e});if(!c)throw Error('FAIL '+n+' '+e);console.log('PASS',n,e)};
const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{
 const page=await browser.newPage({viewport:{width:1440,height:900}});
 page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 page.on('response',r=>{if(r.status()>=400)failed.push({status:r.status(),url:r.url()})});page.on('requestfailed',r=>failed.push({status:0,url:r.url(),error:r.failure()?.errorText}));
 const res=await page.goto(BASE+'/kfb-hub/stage/toolbox/legacy-web-pet/',{waitUntil:'domcontentloaded',timeout:60000});
 check('stage HTTP',res?.ok(),String(res?.status()));
 await page.waitForFunction(()=>document.documentElement.dataset.kfbLegacyWebPet==='ready',null,{timeout:120000});
 check('web pet ready',true);
 check('default Rogue',await page.evaluate(()=>document.documentElement.dataset.kfbLegacyWebPetCharacter)==='rogue');
 const props=(await page.evaluate(()=>document.documentElement.dataset.kfbLegacyWebPetProps||'')).split(',').filter(Boolean);
 check('two camp props',props.length===2,props.join(','));
 check('camp props distinct',new Set(props).size===2,props.join(','));
 const host=page.locator('#kfb-legacy-web-pet-host');
 check('host exists',await host.count()===1);
 const pet=host.locator('button.pet');
 await pet.click({timeout:30000});
 await page.waitForFunction(()=>!!document.documentElement.dataset.kfbLegacyWebPetLastClip,null,{timeout:30000});
 const clip=await page.evaluate(()=>document.documentElement.dataset.kfbLegacyWebPetLastClip);
 check('click real action',!['','Idle','Walk','Run'].includes(clip),clip);
 await pet.click({button:'right'});
 const select=host.locator('select');check('right-click settings',await select.isVisible());
 await select.selectOption('mage');
 await page.waitForFunction(()=>document.documentElement.dataset.kfbLegacyWebPetCharacter==='mage',null,{timeout:120000});
 check('character switch Mage',true);
 await page.locator('a[href="#works"]').click();
 check('ordinary page link survives',await page.evaluate(()=>location.hash)==='#works');
 await page.screenshot({path:OUT+'/hub-stage-mage.png',fullPage:true});
 check('no failed resources',failed.length===0,JSON.stringify(failed));
 check('no page errors',errors.length===0,JSON.stringify(errors));
 await fs.writeFile(OUT+'/web.json',JSON.stringify({checks,props,clip,failed,errors},null,2));
 console.log('LEGACY_WEB_PET_WEB_RESULT',checks.filter(x=>x.pass).length+'/'+checks.length,'PASS');
}finally{await browser.close()}
