import * as THREE from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {createPhysics,STEP} from './physics.js';import {createDriveIntent} from './drive-intent.mjs';import {createTravelFixture} from './travel-fixture.mjs';
const $=s=>document.getElementById(s),keys=new Set(),removers=[];let paused=true,disposed=false,acc=0,last=performance.now(),frameId=0,orbitOn=false,maxUpError=0,phase='NEUTRAL';
const on=(target,event,fn,options)=>{target.addEventListener(event,fn,options);removers.push(()=>target.removeEventListener(event,fn,options))};
const renderer=new THREE.WebGLRenderer({canvas:$('view'),antialias:true,preserveDrawingBuffer:new URLSearchParams(location.search).has('qa')});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x9ccbd5);scene.fog=new THREE.Fog(0x9ccbd5,.45,1.8);scene.add(new THREE.HemisphereLight(0xe9f1fa,0x70715a,1.5));const sun=new THREE.DirectionalLight(0xfff0d6,1.6);scene.add(sun);
const camera=new THREE.PerspectiveCamera(58,1,.0007,30),fixture=createTravelFixture(scene);sun.position.copy(fixture.toWorld([-60,90,-50]));sun.target.position.copy(fixture.toWorld([0,0,0]));scene.add(sun.target);
const physics=await createPhysics(fixture);physics.addMesh('island',fixture.vertices,fixture.indices);Object.assign(physics.params,{steerMax:.55,steerFalloff:.045,steerEase:.22,brake:90,coast:3});const intent=createDriveIntent();let current=physics.snapshot(),previous=current,lastDriveInput={throttle:0,steer:0,brake:false,drift:false,boost:false,hop:false};
const root=new THREE.Group();root.scale.setScalar(fixture.scale);scene.add(root);
const shell=new THREE.Group();root.add(shell);const wheelPivots=[];
for(const [x,z] of [[-.85,1],[.85,1],[-.85,-1],[.85,-1]]){const pivot=new THREE.Group(),wheel=new THREE.Mesh(new THREE.CylinderGeometry(.42,.42,.24,16),new THREE.MeshStandardMaterial({color:0x27343a,roughness:.8}));wheel.rotation.z=Math.PI/2;pivot.position.set(x,-.4,z);pivot.add(wheel);root.add(pivot);wheelPivots.push({pivot,wheel})}
const sourcePath='media/3D_Assets/kenney_car-kit/Models/GLB format/kart-oobi.glb',assetPin='15e36b915c9bdfd7ff000d398418269e27c6ef9f';
const url='https://raw.githubusercontent.com/georg-doc/kayfabizarro/'+assetPin+'/'+sourcePath.split('/').map(encodeURIComponent).join('/');
const loaded=await new GLTFLoader().loadAsync(url),model=loaded.scene;let bounds=new THREE.Box3().setFromObject(model),size=bounds.getSize(new THREE.Vector3());model.scale.multiplyScalar(2.8/Math.max(size.x,size.z));model.updateMatrixWorld(true);bounds.setFromObject(model);const center=bounds.getCenter(new THREE.Vector3());model.position.x-=center.x;model.position.z-=center.z;model.position.y-=bounds.min.y+.35;model.traverse(n=>{if(/wheel/i.test(n.name)||n.name==='character')n.visible=false});shell.add(model);
const orbit=new OrbitControls(camera,$('view'));orbit.enabled=false;orbit.enableDamping=false;orbit.enablePan=false;orbit.rotateSpeed=-.8;orbit.minDistance=.045;orbit.maxDistance=.75;orbit.mouseButtons.LEFT=THREE.MOUSE.ROTATE;orbit.mouseButtons.RIGHT=THREE.MOUSE.ROTATE;
function clear(){keys.clear();intent.reset();acc=0;document.querySelectorAll('[data-key]').forEach(b=>b.dataset.on='false')}
function setPause(value){paused=!!value;clear();$('pause').textContent=paused?'Resume':'Pause';last=performance.now()}
function reset(){clear();physics.reset('manual');current=physics.snapshot();previous=current;maxUpError=0;place(1,true)}
function request(){return {forward:keys.has('KeyW')||keys.has('ArrowUp'),backward:keys.has('KeyS')||keys.has('ArrowDown'),left:keys.has('KeyA')||keys.has('ArrowLeft'),right:keys.has('KeyD')||keys.has('ArrowRight'),driftLeft:keys.has('KeyQ'),driftRight:keys.has('KeyE'),boost:keys.has('ShiftLeft')||keys.has('ShiftRight'),brake:keys.has('KeyB'),hop:keys.has('Space')}}
function signedSpeed(s){const q=new THREE.Quaternion(s.rotation.x,s.rotation.y,s.rotation.z,s.rotation.w),f=new THREE.Vector3(0,0,1).applyQuaternion(q);return f.dot(new THREE.Vector3(s.velocity.x,s.velocity.y,s.velocity.z))}
function step(){const r=request(),v=signedSpeed(current);let input;
 if($('profile').value==='donor'){input={throttle:Number(r.forward)-Number(r.backward),steer:Number(r.right)-Number(r.left),brake:r.brake,drift:r.driftLeft!==r.driftRight,hop:r.hop};phase='RAW DONOR';}
 else {input=intent.step(r,v,STEP,current.contacts.filter(Boolean).length);phase=input.phase;}
 lastDriveInput={...input};previous=current;current=physics.step(input);maxUpError=Math.max(maxUpError,fixture.upError(current.position));
 if(maxUpError>fixture.diagnostics.upBudgetDegrees){setPause(true);$('status').textContent='Local gravity budget exceeded. Reset required.';}
}
let wheelAngle=0;const look=new THREE.Vector3(),eye=new THREE.Vector3();
function place(alpha,snap=false){const p=new THREE.Vector3().copy(previous.position).lerp(current.position,alpha),q=new THREE.Quaternion().copy(previous.rotation).slerp(new THREE.Quaternion().copy(current.rotation),alpha);root.position.copy(fixture.toWorld(p));root.quaternion.copy(fixture.frameQ).multiply(q);
 for(let i=0;i<4;i++){const w=wheelPivots[i];w.pivot.position.y=-(previous.wheelLengths[i]+(current.wheelLengths[i]-previous.wheelLengths[i])*alpha);w.pivot.rotation.y=i<2?current.steer:0;w.wheel.rotation.x=wheelAngle;}
 const f=new THREE.Vector3(0,0,1).applyQuaternion(root.quaternion),up=new THREE.Vector3(0,1,0).applyQuaternion(fixture.frameQ);camera.up.copy(up);const focus=root.position.clone().addScaledVector(up,.014);
 if(orbitOn){const delta=focus.clone().sub(orbit.target);camera.position.add(delta);orbit.target.copy(focus);orbit.update();}
 else {const desired=focus.clone().addScaledVector(f,-.11).addScaledVector(up,.055);const from=fixture.toLocal(focus),to=fixture.toLocal(desired),clearance=physics.cameraClearance(from,to),full=to.distanceTo(from);if(clearance.blocked&&full>0)desired.copy(fixture.toWorld(from.lerp(to,Math.max(.05,clearance.distance/full))));eye.copy(desired);look.copy(focus).addScaledVector(f,.035);if(snap)camera.position.copy(eye);else camera.position.lerp(eye,.15);camera.lookAt(look);orbit.target.copy(focus);}
}
const snapshot=()=>({id:'fr-s04-02',ready:true,paused,profile:$('profile').value,phase,physical:physics.snapshot(),signedForwardSpeed:signedSpeed(current),terrain:fixture.diagnostics,maxUpErrorDegrees:maxUpError,camera:{orbitOn,azimuth:orbit.getAzimuthalAngle(),polar:orbit.getPolarAngle()},driveInput:{...lastDriveInput},intent:intent.snapshot(),vehicle:{path:sourcePath,pin:assetPin,physicalProxyLength:2.6,visualLength:2.8,driver:'NOT_INCLUDED'},input:[...keys],runtimeConsumer:'NOT_TRAVEL_HOST_INTEGRATED'});
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}on(window,'resize',resize);resize();place(1,true);
function frame(t){if(disposed)return;const dt=Math.min(.1,Math.max(0,(t-last)/1000));last=t;if(!paused){acc+=dt;let n=0;while(acc>=STEP&&n++<6){step();acc-=STEP;}if(n>=6)acc=0;fixture.globe.update(dt);wheelAngle=(wheelAngle+signedSpeed(current)*dt/.42)%(Math.PI*2)}place(paused?1:Math.max(0,acc/STEP));renderer.render(scene,camera);$('speed').textContent=signedSpeed(current).toFixed(1);$('phase').textContent=paused?'PAUSED':phase;$('status').textContent=current.contacts.filter(Boolean).length+'/4 wheel contacts · '+Math.hypot(current.position.x,current.position.z).toFixed(1)+' / '+fixture.diagnostics.localRadius+' local radius';if(document.querySelector('details').open)$('facts').textContent=JSON.stringify(snapshot(),null,2);frameId=requestAnimationFrame(frame)}
const ignore=e=>e.target instanceof Element&&!!e.target.closest('input,select,textarea,button,a,summary');
on(window,'keydown',e=>{if(ignore(e))return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.repeat)return;if(e.code==='KeyR'){reset();return}if(e.code==='Escape'){setPause(!paused);return}if(!paused)keys.add(e.code)});on(window,'keyup',e=>keys.delete(e.code));on(window,'blur',()=>setPause(true));on(document,'visibilitychange',()=>{if(document.hidden)setPause(true)});
for(const b of document.querySelectorAll('[data-key]')){on(b,'pointerdown',e=>{e.preventDefault();if(paused)return;b.setPointerCapture(e.pointerId);keys.add(b.dataset.key);b.dataset.on='true'});for(const ev of ['pointerup','pointercancel','lostpointercapture'])on(b,ev,()=>{keys.delete(b.dataset.key);b.dataset.on='false'})}
$('pause').onclick=()=>{setPause(!paused);$('view').focus()};$('reset').onclick=()=>{reset();$('view').focus()};$('profile').onchange=()=>{setPause(true);reset()};$('camera').onclick=()=>{orbitOn=!orbitOn;orbit.enabled=orbitOn;$('camera').textContent=orbitOn?'Follow view':'Orbit view';$('view').focus()};$('start').onclick=()=>{$('gate').hidden=true;setPause(false);$('view').focus()};
function dispose(){if(disposed)return;disposed=true;cancelAnimationFrame(frameId);clear();removers.forEach(fn=>fn());orbit.dispose();physics.dispose();const geometries=new Set(),materials=new Set(),textures=new Set();scene.traverse(n=>{if(n.geometry)geometries.add(n.geometry);for(const m of [].concat(n.material||[])){materials.add(m);Object.values(m).filter(v=>v?.isTexture).forEach(v=>textures.add(v))}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());renderer.dispose()}
on(window,'pagehide',dispose);window.__FREE_ROAM__={snapshot,dispose};$('loading').textContent='Original kart and '+fixture.diagnostics.contactTriangles+' baked contact triangles loaded.';$('start').disabled=false;window.__FREE_ROAM_READY__=true;frameId=requestAnimationFrame(frame);
