import fs from 'node:fs';import path from 'node:path';import { chromium } from 'playwright';
const base=process.env.STEM_BED_URL||'http://127.0.0.1:4173/kfb-hub/stage/audio-stem-bed-01/';const out=process.env.STEM_BED_PROOF||'audio-stem-bed-proof';fs.mkdirSync(out,{recursive:true});
const result={status:'UNKNOWN',checks:[],errors:[],httpErrors:[],external:[],base};const check=(n,o,d=null)=>{result.checks.push({name:n,ok:!!o,detail:d});if(!o)throw new Error(n+': '+JSON.stringify(d));};
const browser=await chromium.launch({headless:true,args:['--autoplay-policy=no-user-gesture-required']});let page;
try{
 const c=await browser.newContext({viewport:{width:1440,height:980}});page=await c.newPage();const origin=new URL(base).origin;
 page.on('pageerror',e=>result.errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')result.errors.push(m.text())});page.on('response',r=>{if(r.status()>=400)result.httpErrors.push({url:r.url(),status:r.status()})});page.on('request',r=>{try{const u=new URL(r.url());if(!r.url().startsWith('data:')&&u.origin!==origin)result.external.push(r.url())}catch{}});
 await page.goto(base,{waitUntil:'networkidle',timeout:90000});check('build marker',await page.evaluate(()=>document.documentElement.dataset.kfbBuild==='AUDIO-STEM-BED-01-v0.1'));check('runtime export',await page.evaluate(()=>!!window.__KFB_STEM_BED__));
 await page.click('#load');await page.waitForFunction(()=>window.__KFB_STEM_BED__.snapshot().loaded,undefined,{timeout:120000});let s=await page.evaluate(()=>window.__KFB_STEM_BED__.snapshot());
 check('one AudioContext',s.contextCount===1,s.contextCount);check('AudioContext running',s.contextState==='running',s.contextState);check('8 stem decodes',Object.values(s.stemStats).filter(Boolean).length===8);check('stem duration spread zero',s.stemDurationSpread===0,s.stemDurationSpread);
 await page.evaluate(()=>window.__KFB_STEM_BED__.playStemBed());s=await page.evaluate(()=>window.__KFB_STEM_BED__.snapshot());check('sample-sync starts',s.synchronizedStarts,s.timelineStarts);check('eight starts',s.timelineStarts.length===8,s.timelineStarts.length);
 const neutral=s.targets;
 await page.evaluate(()=>window.__KFB_STEM_BED__.setControl('activity',1));const active=(await page.evaluate(()=>window.__KFB_STEM_BED__.snapshot())).targets;check('activity raises drums',active.drums>neutral.drums,{neutral:neutral.drums,active:active.drums});check('activity raises percussion',active.percussion>neutral.percussion,{neutral:neutral.percussion,active:active.percussion});
 await page.evaluate(()=>{window.__KFB_STEM_BED__.reset();window.__KFB_STEM_BED__.setControl('roadLift',1)});const road=(await page.evaluate(()=>window.__KFB_STEM_BED__.snapshot())).targets;check('road raises drums',road.drums>neutral.drums,{neutral:neutral.drums,road:road.drums});check('road raises bass',road.bass>neutral.bass,{neutral:neutral.bass,road:road.bass});
 await page.evaluate(()=>{window.__KFB_STEM_BED__.reset();window.__KFB_STEM_BED__.setControl('night',1)});const night=(await page.evaluate(()=>window.__KFB_STEM_BED__.snapshot())).targets;check('night reduces percussion',night.percussion<neutral.percussion,{neutral:neutral.percussion,night:night.percussion});check('night supports synth bed',night.synth>=neutral.synth,{neutral:neutral.synth,night:night.synth});
 await page.evaluate(()=>{window.__KFB_STEM_BED__.reset();window.__KFB_STEM_BED__.setVoiceFocus(true)});const voice=(await page.evaluate(()=>window.__KFB_STEM_BED__.snapshot())).targets;check('voice strongly ducks keyboard',voice.keyboard<neutral.keyboard*.5,{neutral:neutral.keyboard,voice:voice.keyboard});check('voice preserves bass more than keyboard',voice.bass/neutral.bass>voice.keyboard/neutral.keyboard,{bassRatio:voice.bass/neutral.bass,keyRatio:voice.keyboard/neutral.keyboard});
 await page.screenshot({path:path.join(out,'desktop.png'),fullPage:true});check('no page errors',result.errors.length===0,result.errors);check('no HTTP errors',result.httpErrors.length===0,result.httpErrors);check('no external requests',result.external.length===0,result.external);
 result.snapshot=await page.evaluate(()=>window.__KFB_STEM_BED__.snapshot());result.status='PASS';
}catch(e){result.status='FAIL';result.failure=String(e.stack||e);process.exitCode=1;if(page)await page.screenshot({path:path.join(out,'FAIL.png'),fullPage:true}).catch(()=>{})}
finally{fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({status:result.status,checks:result.checks.length,failure:result.failure||null}));await browser.close();}