"""Reproducible additive P02 viewer. Reuses the unchanged P01 host by explicit transforms.
No third-party source is fetched; the standalone embeds a labelled City palette snapshot.
Execute as production agent, not a user terminal task.
"""
from pathlib import Path
import re, json, hashlib, sys
ROOT=Path(__file__).resolve().parents[1]
P1=ROOT/'landmarks/pilot-01';P2=ROOT/'landmarks/pilot-02'
def body(path):
    return re.sub(r'^import .*?;\n','',path.read_text(),flags=re.M)
def main(out):
    v=(P1/'viewer.mjs').read_text()
    v=v.replace("import {buildLandmark,MODEL_IDS,ZONES} from './geometry.mjs';", "import {buildLandmark,MODEL_IDS} from './geometry.mjs';\nimport {ZONES} from '../pilot-01/geometry.mjs';")
    v=v.replace("import {zoneColours,CITY_STYLE_URL} from './presentation.mjs';", "import {zoneColours} from './presentation.mjs';\nimport {CITY_STYLE_URL} from '../pilot-01/presentation.mjs';")
    v=v.replace("from './three-adapter.mjs'", "from '../pilot-01/three-adapter.mjs'").replace("from './glb.mjs'", "from '../pilot-01/glb.mjs'")
    v=v.replace("active='eiffel'", "active='kremlin-wall'")
    v=v.replace("id==='compare'?MODEL_IDS:[id]", "id==='compare'?MODEL_IDS.filter(id=>id!=='spasskaya'):[id]")
    v=v.replace("'-pilot-01.glb'", "'-pilot-02.glb'")
    v=v.replace("geographicBinding:null,styleSource", "geographicBinding:null,donor:'pilot-02',styleSource")
    # Reuse original wire flag/zone API; expose only inspection methods for QA.
    v=v.replace("setModel:load", "setModel:load,setView:frame")
    (P2/'viewer.mjs').write_text('/** Generated by tests/build_landmarks_p02.py from unchanged Pilot 01 host. */\n'+v)
    h=(P1/'index.html').read_text().replace('Pilot 01','Pilot 02').replace('PILOT 01','PILOT 02')
    h=h.replace('<option value="compare">', '<option value="pentagon">The Pentagon</option><option value="spasskaya">Spasskaya Tower</option><option value="kremlin-wall" selected>Kremlin wall study</option><option value="compare">')
    h=h.replace('Landmark study</h1>', 'Kremlin wall study</h1>')
    (P2/'index.html').write_text(h)
    # Package identical host code and geometries, with scoped legacy helpers.
    g1=body(P1/'geometry.mjs');g1=g1.replace('export ', '')
    p1=body(P1/'presentation.mjs').replace('export ', '')
    p1=p1.replace('zoneColours(', 'priorColours(')
    helper=body(ROOT.parent/'osm-city-lab/src/style/kfb-city-materials.js').replace('export ', '')
    g2=body(P2/'geometry.mjs').replace('export ', '')
    # Scope P01 primitives to prevent name collisions and preserve its exact factories.
    legacy='const Legacy=(()=>{'+g1+';return {buildLandmark,MODEL_IDS,ZONES,boundsOf,mergeZones,faceNormals,assembly,spin,add};})();\n'
    bindings='const {ZONES,boundsOf,mergeZones,faceNormals,assembly,spin,add}=Legacy;const buildPrior=Legacy.buildLandmark;const PRIOR_IDS=Legacy.MODEL_IDS;\n'
    sources=[P1/'geometry.mjs',P1/'presentation.mjs',P1/'viewer.mjs',P1/'glb.mjs',P1/'three-adapter.mjs',P2/'builder.mjs',P2/'geometry.mjs',P2/'presentation.mjs',P2/'viewer.mjs']
    pins={str(p.relative_to(ROOT)):hashlib.sha256(p.read_bytes()).hexdigest() for p in sources}
    stylep=ROOT.parent/'osm-city-lab/styles/kfb-city-v0.json';style=json.loads(stylep.read_text());pins['cityStyleSha256']=hashlib.sha256(stylep.read_bytes()).hexdigest()
    combined='\n'.join([helper,legacy,bindings,g2,p1,body(P2/'presentation.mjs').replace('export ', ''),body(P1/'three-adapter.mjs').replace('export ', ''),body(P1/'glb.mjs').replace('export ', ''),body(P2/'viewer.mjs').replace('export ', '')])
    code="""const timer=setTimeout(()=>document.querySelector('#status').textContent='Still loading Three.js. Check access to unpkg.com.',12000);
try{const THREE=await import('three');const {OrbitControls}=await import('three/addons/controls/OrbitControls.js');\n"""
    code+='window.__KFB_EMBEDDED_CITY_STYLE__='+json.dumps(style)+';\nwindow.__KFB_SOURCE_PINS__='+json.dumps(pins)+';\n'+combined
    code+="\nawait boot();clearTimeout(timer);}catch(e){clearTimeout(timer);const s=document.querySelector('#status');s.textContent='Viewer could not start: '+e.message;s.classList.add('error');document.querySelector('#export').disabled=true;console.error(e);}\n"
    h=re.sub(r'<script type="module" id="boot">.*?</script>',lambda m:'<script type="module" id="boot">\n'+code+'</script>',h,flags=re.S)
    h=h.replace('href="../../prototypes/koelner-dom/v0.2/index.html"','href="https://github.com/georg-doc/kayfabizarro/blob/main/tools/img2threejs/prototypes/koelner-dom/v0.2/index.html"')
    Path(out).write_text(h);print(out,len(h.encode()))
if __name__=='__main__':main(sys.argv[1] if len(sys.argv)>1 else ROOT/'landmark-pilot-02-standalone.html')
