import fs from 'node:fs';
import vm from 'node:vm';
const root=new URL('../',import.meta.url);
const read=(p)=>fs.readFileSync(new URL(p,root),'utf8');
const cat=JSON.parse(read('data/catalog.v1.json'));
let pass=0,fail=0;const ok=(cond,msg)=>{if(cond){pass++;console.log('PASS',msg)}else{fail++;console.error('FAIL',msg)}};
ok(cat.characters.length===4,'four legacy RPG character bodies');
ok(cat.heads.length===17,'17 source head choices');
ok(cat.weapons.length===24,'24 tiered weapons');
ok(cat.accessories.length===10,'five embedded head gear + five source props');
ok(cat.motions.length===30,'30 embedded Legacy clips');
ok(cat.characters.every(c=>c.path.includes('KayKit Dungeon Pack 1.0 2')),'character paths remain exact pack sources');
ok(cat.heads.filter(h=>h.kind==='asset').length===13,'12 alternate heads + skull are separate assets');
ok(new Set(cat.weapons.map(w=>w.family)).size===8,'eight weapon families');
ok(cat.weapons.filter(w=>w.tier==='common').length===8,'eight common weapons');
ok(cat.weapons.filter(w=>w.tier==='uncommon').length===8,'eight uncommon weapons');
ok(cat.weapons.filter(w=>w.tier==='rare').length===8,'eight rare weapons');
ok(cat.semantic.attack==='Attack(1h)' && cat.semantic.bow==='Shoot(2h)Bow','semantic combat mappings use real Legacy clip names');
const app=read('app.js'), rig=read('lib/legacy-rig-adapter.v1.js'), face=read('lib/legacy-facehost.v1.js'), html=read('index.html');
ok(app.includes("STORAGE='kfb.toolbox.legacy-rpg-rigging.v0'"),'isolated localStorage namespace');
ok(app.includes('pet-eye-rig.v6.js'),'existing EyeRig v6 imported, not rewritten');
ok(rig.includes("CORE_BONES=['Body','Head','armLeft','armRight']"),'exact legacy core assembly bone contract');
ok(rig.includes('boneInverses'),'assembly uses donor inverse-bind matrices');
ok(rig.includes('pawAnchor'),'measured rigid-arm prop anchor retained');
ok(face.includes("body.name='body'"),'LegacyFaceHost preserves EyRig body host contract');
ok(face.includes('measureLegacyEyeCandidates'),'head batch measurement path present');
ok(html.includes('Source isolate') && html.includes('No placeholder geometry'),'source-isolation/no-placeholder gate visible');
ok(html.includes('Batch EyeRig v6'),'batch EyeRig authoring surface visible');
ok(html.includes('Prop-rig bridge'),'future prop-rig bridge labelled');
ok(!app.includes('localStorage.clear'),'never clears shared localStorage');
for(const f of ['app.js','lib/legacy-rig-adapter.v1.js','lib/legacy-facehost.v1.js']){try{new vm.SourceTextModule(read(f));ok(true,`${f} module parses`)}catch(e){console.error(e);ok(false,`${f} module parses`)}}
console.log(`RESULT ${pass}/${pass+fail} PASS`);if(fail)process.exit(1);
