// Reproducible extraction from the untouched Claude Design r2 cut.
// Only body geometry, palette and anchor seam: no copied renderer/material,
// provider, frame loop, PDF logic or scheduler.
import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const cut = '../../_inbox/KFB_WORLD_BILLBOARD_CLAY01_CLAUDE_DESIGN_SESSION_CUT_2026-10-01_r2/';
const sourceURL = new URL(cut + 'briefd/billboard-clay.js', import.meta.url);
const source = await readFile(sourceURL, 'utf8');
const sha = value => createHash('sha256').update(value).digest('hex');
const expected = '7d225a768a82b611b3bc303f88e44101437e1772f4b0a209701896254b58665d';
if (sha(source) !== expected) throw Error('r2 source hash differs; review the donor before rebuilding');
const between = (start, end) => {
  const a = source.indexOf(start), b = source.indexOf(end, a + start.length);
  if (a < 0 || b < 0) throw Error('Donor extraction boundary absent');
  return source.slice(a, b);
};
const imports = source.match(/^import .*;$/gm).join('\n');
const geometry = between('// ── Palette:', '// ── Inhalte:');
const originalAnchor = between('// ── Anker → Pose', '// ── Billboard-Instanz');
const defective = 'const y0 = feet.reduce((u, v) => u + v, 0) / 4,';
if (originalAnchor.split(defective).length !== 2) throw Error('Expected one r2 foot-mean repair seam');
const anchor = originalAnchor.replace(defective,
  'const y0 = feet.reduce((u, v) => u + v, 0) / feet.length,');
const generated = '// GENERATED by build-donor.mjs. Authoring source: untouched r2 cut.\n' +
  '// One repair: ground mean divides by actual foot count (2 or 4).\n' +
  imports + '\n\n' + geometry + '\n' + anchor;
await writeFile(new URL('./body-donor.generated.js', import.meta.url), generated);
await writeFile(new URL('./DONOR_LOCK.json', import.meta.url), JSON.stringify({
  schema: 'kfb.billboard-body-donor-lock/1',
  source: 'tools/KFB-ToolBox/_inbox/KFB_WORLD_BILLBOARD_CLAY01_CLAUDE_DESIGN_SESSION_CUT_2026-10-01_r2/briefd/billboard-clay.js',
  sourceSha256: expected, outputSha256: sha(generated),
  approval: 'GEORG_TUNE_READY_2026-10-01',
  seam: 'resolveAnchor: foot height sum / feet.length instead of / 4',
  excluded: ['makeClayFamily', 'loadContent', 'paintFace', 'Billboard', 'BillboardScheduler', 'buildIsland'],
  owners: { surface: 'B1', videoFrontRear: 'B2a', mediaRecipe: 'H13/H14', material: 'canonical KFB prop/signage profile', terrain: 'receiving island owner' }
}, null, 2) + '\n');
console.log('r2 body/anchor extraction generated; material, content and timing owners excluded');
