import fs from 'node:fs'; import path from 'node:path';
const root=path.resolve(process.argv[2]||'.');
const files=['index.html','styles.css','app.js','lib/kaykit-eye-adapter.v1.js','lib/source-face-cleanup.v1.js','lib/medium-source-eye-cleanup.v1.js','lib/face-color-sampler.v1.js','lib/clay-k1.js','lib/clay/clay-soften.v1.js','data/gothgirl.seed.json','data/rig-medium-default.v0.json','data/rig-medium-actors.v0.json','data/rig-large-default.v0.json','data/rig-large-actors.v0.json','data/rig-large-reviewed.v1.json','data/cleanup02-review.v0.json','data/cleanup02-anchors.v0.json','data/mystery-monthly-character-coverage.v1.json','data/appearance-variants.v1.json','docs/SOURCE_AUDIT.md','docs/SOURCE_COMPONENT_IDENTITY_2026-09-19.md','docs/source-components-0-11.html','docs/QA_EYE_CALIBRATION_LOOP_2026-09-19.md','docs/BATCH_FEATURE_BACKLOG_2026-09-19.md','docs/RIG_LARGE_MONSTROSITY_CALIBRATION_2026-09-19.md'];
let pass=0, fail=0; const results=[];
function check(name,ok,detail=''){(ok?pass++:fail++);results.push({name,status:ok?'PASS':'FAIL',detail});}
for(const f of files)check(`file:${f}`,fs.existsSync(path.join(root,f)),fs.existsSync(path.join(root,f))?'present':'missing');
const app=fs.readFileSync(path.join(root,'app.js'),'utf8'); const html=fs.readFileSync(path.join(root,'index.html'),'utf8'); const styles=fs.readFileSync(path.join(root,'styles.css'),'utf8'); const cleanup=fs.readFileSync(path.join(root,'lib/source-face-cleanup.v1.js'),'utf8'); const mediumCleanup=fs.readFileSync(path.join(root,'lib/medium-source-eye-cleanup.v1.js'),'utf8'); const faceColorSampler=fs.readFileSync(path.join(root,'lib/face-color-sampler.v1.js'),'utf8'); const adapter=fs.readFileSync(path.join(root,'lib/kaykit-eye-adapter.v1.js'),'utf8'); const seed=JSON.parse(fs.readFileSync(path.join(root,'data/gothgirl.seed.json'),'utf8')); const medium=JSON.parse(fs.readFileSync(path.join(root,'data/rig-medium-default.v0.json'),'utf8')); const actors=JSON.parse(fs.readFileSync(path.join(root,'data/rig-medium-actors.v0.json'),'utf8')); const large=JSON.parse(fs.readFileSync(path.join(root,'data/rig-large-default.v0.json'),'utf8')); const largeActors=JSON.parse(fs.readFileSync(path.join(root,'data/rig-large-actors.v0.json'),'utf8')); const largeReviewed=JSON.parse(fs.readFileSync(path.join(root,'data/rig-large-reviewed.v1.json'),'utf8')); const cleanup02Review=JSON.parse(fs.readFileSync(path.join(root,'data/cleanup02-review.v0.json'),'utf8')); const cleanup02Anchors=JSON.parse(fs.readFileSync(path.join(root,'data/cleanup02-anchors.v0.json'),'utf8')); const mysteryCoverage=JSON.parse(fs.readFileSync(path.join(root,'data/mystery-monthly-character-coverage.v1.json'),'utf8')); const appearanceVariants=JSON.parse(fs.readFileSync(path.join(root,'data/appearance-variants.v1.json'),'utf8')); const identity=fs.readFileSync(path.join(root,'docs/SOURCE_COMPONENT_IDENTITY_2026-09-19.md'),'utf8'); const componentHtml=fs.readFileSync(path.join(root,'docs/source-components-0-11.html'),'utf8'); const qa=fs.readFileSync(path.join(root,'docs/QA_EYE_CALIBRATION_LOOP_2026-09-19.md'),'utf8'); const backlog=fs.readFileSync(path.join(root,'docs/BATCH_FEATURE_BACKLOG_2026-09-19.md'),'utf8'); const largeDoc=fs.readFileSync(path.join(root,'docs/RIG_LARGE_MONSTROSITY_CALIBRATION_2026-09-19.md'),'utf8');
check('one-localStorage-namespace',app.includes("kfb.toolbox.eye-rig-batch.v0"));
check('never-localStorage-clear',!app.includes('localStorage.clear'));
check('pinned-source-revision',(app.match(/5650b6c54d8789b20ea80abe857688173d506d3b/g)||[]).length>=1);
check('eye-update-render-loop',/state\.eyes\?\.update\(dt,camera\)/.test(app));
check('single-animation-mixer',(app.match(/new THREE\.AnimationMixer/g)||[]).length===1,`${(app.match(/new THREE\.AnimationMixer/g)||[]).length} constructors`);
check('cleanup-fail-closed',cleanup.includes("status: 'HUMAN_REQUIRED'")&&cleanup.includes('expectedConnectedComponents = 12'));
check('cleanup-reuses-donor',cleanup.includes('faceShells, buildStripped'));
check('no-source-GLB-write',!app.includes('GLTFExporter')&&!cleanup.includes('GLTFExporter'));
check('lashes-off',adapter.includes("length: 0")&&adapter.includes("density: 0"));
check('neutral-settle-before-ready',adapter.includes("applyExpression('neutral')")&&adapter.includes('for (let i = 0; i < 16; i++) rig.update(1 / 60)'));
check('six-expression-buttons',['neutral','happy','angry','sad','surprised','thinking'].every((x)=>html.includes(`data-expression="${x}"`)));
check('standard-camera-views',['front','three-left','three-right','side-left','side-right','face'].every((x)=>html.includes(`data-view="${x}"`)));
check('motion-regression-buttons',['Idle_A','Walking_A','Running_A','Jump_Full_Short'].every((x)=>html.includes(`data-motion="${x}"`)));
check('profile-import-preview',html.includes('importPreview')&&app.includes('Nothing has been applied yet'));
check('source-measured-explicit-candidate',html.includes('Use source-measured baseline')&&app.includes("$('#useMeasuredBtn')")&&app.includes("state.profile.status='AUTO_CANDIDATE'"));
check('source-component-isolation-diagnostic',html.includes('id="componentSelect"')&&html.includes('id="isolateComponentBtn"')&&cleanup.includes('setComponentIsolation')&&cleanup.includes('clearComponentIsolation')&&app.includes('wireComponentDiagnostic'));
check('current-source-eye-components-2-3',JSON.stringify(seed.sourceFace.eyeComponents)===JSON.stringify([2,3])&&cleanup.includes('eyeComponents = [2, 3]')&&cleanup.includes('eyeIdentityOk'));
check('source-component-identity-evidence',identity.includes('| 2 | eye')&&identity.includes('| 3 | eye')&&(componentHtml.match(/data-component=/g)||[]).length===12);
check('medium-seed-reference',medium.reference?.blob==='e87e6337a6db67096a9577335f36d60672aa389e'&&medium.reference?.actorId==='gothgirl');
check('medium-authoring-default-screenshot',
  medium.authoringDefault?.eye?.anchor?.dx===0.295 &&
  medium.authoringDefault?.eye?.anchor?.dy===0.045 &&
  medium.authoringDefault?.eye?.anchor?.ring===0.153 &&
  medium.authoringDefault?.eye?.anchor?.track===0.15 &&
  medium.authoringDefault?.eye?.pupilSize===0.34 &&
  medium.authoringDefault?.eye?.inset===0.4 &&
  medium.authoringDefault?.eye?.converge===0.18);
check('measurement-suggestion-only',medium.measurementSuggestion?.policy==='EXPLICIT_SUGGESTION_ONLY_NEVER_AUTO_APPLY'&&!app.includes('calibrateRigMediumDefault'));
check('gothgirl-authoring-seed',seed.eye?.anchor?.dx===0.295&&seed.eye?.anchor?.dy===0.045&&seed.eye?.anchor?.ring===0.153&&seed.eye?.anchor?.track===0.15&&seed.eye?.pupilSize===0.34&&seed.eye?.inset===0.4&&seed.eye?.converge===0.18);
check('lids-face-base-darkened',seed.eye?.baseColor==='#e6cbc3'&&seed.eye?.lidColorMode==='face-base-darkened'&&adapter.includes('baseColor,')&&adapter.includes('setBaseColor(hex)'));
check('legacy-default-migration',app.includes('isLegacyUntunedProfile')&&app.includes('state.savedLegacyDefault')&&app.includes('applyAuthoringDefaultToProfile(state.profile'));
check('eyeoval-donor-reuse',adapter.includes('frizzlegraft-v1/eyeoval.v1.js')&&adapter.includes('attachEyeOval')&&adapter.includes('setOval(patch)')&&['ovalW','ovalH','ovalD','ovalTilt'].every((k)=>html.includes(`data-param="${k}"`)));
check('eyeoval-pupil-isolation-pin',adapter.includes('@2bfbe0d2d73aeb5f2fc3af5b11983dc099016792/tools/KFB-ToolBox/kfb-rigs-embed-v3/frizzlegraft-v1/eyeoval.v1.js'));
check('pupil-tracking-modes',['life','pointer','fixed'].every((k)=>html.includes(`data-tracking-mode="${k}"`))&&app.includes('function setTrackingMode')&&!html.includes('id="gazeFollowToggle"'));
check('persistent-batchbar',['batchImportBtn','batchExportCharacterBtn','batchExportBatchBtn','batchApplySelectedBtn','batchResetBtn','batchApproveBtn'].every((id)=>html.includes(`id="${id}"`)));
check('batch-import-export-v02',app.includes('kfb.eye-profile-batch/0.2-candidate')&&app.includes('rigClass:state.rigClass')&&app.includes('classDefault:clone(seed?.authoringDefault||null)')&&app.includes('selectedActorIds:ids')&&app.includes('profiles'));
check('inheritance-class-character-session',JSON.stringify(medium.inheritance?.order)===JSON.stringify(['rigClass','character','session'])&&app.includes("order:['rigClass','character','session']"));
check('deferred-feature-backlog',backlog.includes('top / bottom eye contour')&&backlog.includes('Mouth Batch')&&backlog.includes('Vehicle EyeRig')&&backlog.includes('headlight'));
check('corrected-cleanup-status-accepted',app.includes("'SOURCE_IDENTITY_VERIFIED_AUTO_CANDIDATE'"));
check('qa-four-key-views',html.includes('id="qaCaptureBtn"')&&app.includes("['front','three-left','three-right','side-right']")&&app.includes("-qa-front-3q-side.png")&&app.includes("state.currentActorId||'actor'")&&qa.includes('Front')&&qa.includes('¾ L')&&qa.includes('¾ R')&&qa.includes('Side'));
check('medium-actor-catalog-55',actors.actorCount===55&&actors.actors?.length===55);
check('medium-actor-catalog-unique',new Set(actors.actors.map((a)=>a.id)).size===55);
check('medium-actor-catalog-rig-boundary',actors.actors.every((a)=>a.rigClass==='Rig_Medium'&&a.jointCount===23));
check('medium-actor-catalog-diverse',['gothgirl','clown','farmer-b','lorekeeper','skeleton-warrior','magical-girl','driver','mannequin-medium','adventurer-barbarian','adventurer-knight','adventurer-mage','adventurer-ranger','adventurer-rogue','adventurer-rogue-hooded','paladin','paladin-helmet','paladin-king','mummy-a','mummy-b','orc-raider','combat-mech','marksman','hoarder','survivalist'].every((id)=>actors.actors.some((a)=>a.id===id)));
check('medium-mystery-coverage-19',actors.actors.filter((a)=>a.reviewGroup==='medium-mystery-coverage').length===19);
check('medium-adventurers-six',actors.actors.filter((a)=>a.reviewGroup==='medium-adventurers').length===6&&['adventurer-barbarian','adventurer-knight','adventurer-mage','adventurer-ranger','adventurer-rogue','adventurer-rogue-hooded'].every((id)=>actors.actors.some((a)=>a.id===id)));
check('medium-adventurers-pinned',actors.actors.filter((a)=>a.reviewGroup==='medium-adventurers').every((a)=>a.packId==='kaykit-adventurers-2-0-free'&&a.revision==='f9dd7a64c4ae0907b8752717861eba065e557d9d'&&typeof a.blob==='string'&&a.blob.length===40));
check('medium-actor-gothgirl-exact-cleanup',actors.actors.find((a)=>a.id==='gothgirl')?.cleanup?.mode==='verified-components');
check('medium-generic-cleanup-donor',mediumCleanup.includes('donoreyes.v1.js')&&mediumCleanup.includes('findDonorEyes')&&mediumCleanup.includes('stripDonorEyes'));
check('medium-generic-cleanup-fail-closed',mediumCleanup.includes("status:'HUMAN_REQUIRED'")&&mediumCleanup.includes('no head-named indexed skinned mesh')&&mediumCleanup.includes('no mirrored front eye pair'));
check('dynamic-actor-loader',app.includes('async function loadActor')&&app.includes('actorUrl(actor)')&&app.includes('prepareMediumActorCleanup'));
check('shared-medium-motion-owner',app.includes('ANIM_PIN')&&app.includes('KayKit_Character_Animations_1.1/Animations/gltf/Rig_Medium/')&&(app.match(/new THREE\.AnimationMixer/g)||[]).length===1);
check('per-actor-profile-store',app.includes('profiles:state.profiles')&&app.includes('function ensureProfile')&&app.includes('state.profiles[actor.id]'));
check('review-state-model',['UNREVIEWED','ADJUSTED','APPROVED','ADJUSTED_APPROVED','UNSUPPORTED','REJECTED'].every((x)=>app.includes(x)));
check('roster-filters',['all','unreviewed','adjusted','unsupported','cleanup-issue'].every((x)=>html.includes(`data-roster-filter="${x}"`))&&app.includes('function renderRoster'));
check('next-unreviewed',html.includes('id="nextUnreviewedBtn"')&&app.includes('function nextUnreviewed')&&app.includes("$('#nextUnreviewedBtn').onclick"));
check('actor-selection-list',html.includes('id="actorList"')&&app.includes('data-select-id')&&app.includes('selectedActors'));
check('dynamic-source-audit',['sourceActor','sourceActorName','sourcePath','sourceCleanup','actorTechHint'].every((id)=>html.includes(`id="${id}"`)));
check('large-actor-catalog-8',largeActors.actorCount===8&&largeActors.actors?.length===8);
check('large-actor-catalog-unique',new Set(largeActors.actors.map((a)=>a.id)).size===8);
check('large-actor-catalog-rig-boundary',largeActors.actors.every((a)=>a.rigClass==='Rig_Large'&&a.jointCount===23));
check('large-actor-catalog-known-set',['monstrosity','black-knight','demon-lord','orc-brute','frost-golem','gtn','gtn-forgotten','clanker'].every((id)=>largeActors.actors.some((a)=>a.id===id)));
check('large-mystery-coverage-4',largeActors.actors.filter((a)=>a.reviewGroup==='large-mystery-coverage').length===4);
check('large-actor-blobs-pinned',largeActors.actors.every((a)=>typeof a.blob==='string'&&a.blob.length===40));
check('large-reviewed-per-actor-no-shared-default',large.status==='REVIEWED_PER_ACTOR_NO_CLASS_DEFAULT'&&large.authoringDefault===null&&large.reviewedBatch?.actorCount===4);
check('large-calibration-start-present',large.calibrationStart?.eye?.anchor?.dx===0.295&&large.calibrationStart?.eye?.anchor?.ring===0.153);
check('large-explicit-default-promotion',large.promotion?.action==='Set as Large default'&&large.promotion?.policy==='human explicit only'&&app.includes('function promoteCurrentAsClassDefault'));
check('rig-class-switch-ui',html.includes('data-rig-class="Rig_Medium"')&&html.includes('data-rig-class="Rig_Large"')&&html.includes('id="rigClassTitle"'));
check('large-default-button',html.includes('id="promoteClassDefaultBtn"')&&app.includes("currentActorId!=='monstrosity'"));
check('per-class-catalog-config',app.includes("Rig_Medium:{")&&app.includes("Rig_Large:{")&&app.includes("catalogUrl:'./data/rig-large-actors.v0.json'"));
check('large-motion-owner',app.includes('Rig_Large/Rig_Large_General.glb')&&app.includes('Rig_Large/Rig_Large_MovementBasic.glb'));
check('large-required-clips-honest',app.includes("requiredClips:['Idle_A','Walking_A','Running_A']")&&!app.includes("Rig_Large:{\n    label:'Large',\n    catalogUrl:'./data/rig-large-actors.v0.json',\n    seedUrl:'./data/rig-large-default.v0.json',\n    defaultActor:'monstrosity',\n    generalUrl:ANIM_CDN+'media/3D_Assets/KayKit_Character_Animations_1.1/Animations/gltf/Rig_Large/Rig_Large_General.glb',\n    moveUrl:ANIM_CDN+'media/3D_Assets/KayKit_Character_Animations_1.1/Animations/gltf/Rig_Large/Rig_Large_MovementBasic.glb',\n    requiredClips:['Idle_A','Walking_A','Running_A','Jump_Full_Short']"));
check('class-switch-runtime',app.includes('async function switchRigClass')&&app.includes('state.catalog=state.catalogs[rigClass]||[]')&&app.includes('await loadMotion(state.loader)'));
check('per-class-persistence',app.includes('classDefaults')&&app.includes('selectedByClass')&&app.includes('currentActorByClass')&&app.includes('currentRigClass'));
check('large-batch-no-fake-default',app.includes('classDefault:clone(seed?.authoringDefault||null)')&&app.includes('calibrationStart:clone(seed?.calibrationStart||null)'));
check('large-doc',largeDoc.includes('Monstrosity')&&largeDoc.includes('Black Knight')&&largeDoc.includes('Demon Lord')&&largeDoc.includes('Orc Brute')&&largeDoc.includes('Set as Large default'));
check('generic-cleanup-single-material-fallback',mediumCleanup.includes('if(!hadGroups) g.addGroup(0,g.index.count,0)')&&mediumCleanup.includes('donorRestore?.()')&&mediumCleanup.includes('g.clearGroups()'));
check('loader-error-review-recovery',app.includes("reviewState==='UNSUPPORTED'")&&app.includes("/^load failed:/.test")&&app.includes("reviewState='UNREVIEWED'")&&app.includes('recovered from previous loader error'));
check('large-reviewed-batch-accepted',largeReviewed.schema==='kfb.eye-profile-batch/0.2-reviewed'&&largeReviewed.profiles?.length===4&&largeReviewed.profiles.every((p)=>p.reviewState==='ADJUSTED_APPROVED'&&p.eye?.baseColor===null&&p.sourceFace?.faceColorSource==='AUTO_SOURCE_HEAD'));
check('large-reviewed-known-actors',['monstrosity','black-knight','demon-lord','orc-brute'].every((id)=>largeReviewed.profiles.some((p)=>p.actorId===id)));
check('large-reviewed-source-pinned',largeReviewed.source?.revision==='52532aee17f85324a6d04ab53150216f00ac5d89'&&largeReviewed.source?.blob==='f55db82d1a76ba9362df261cf66517859abbf953');
check('large-seed-reviewed-link',large.status==='REVIEWED_PER_ACTOR_NO_CLASS_DEFAULT'&&large.reviewedBatch?.path==='data/rig-large-reviewed.v1.json');
check('face-color-sampler-present',faceColorSampler.includes("export function sampleActorFaceColor")&&faceColorSampler.includes("head-texture-around-eye-host")&&faceColorSampler.includes("pickDominantColor"));
check('face-color-sampler-reuses-texture-pattern',faceColorSampler.includes("document.createElement('canvas')")&&faceColorSampler.includes("getImageData")&&faceColorSampler.includes("flipY"));
check('auto-face-color-runtime',app.includes("sampleActorFaceColor")&&app.includes("runtime-head-texture-sample")&&app.includes("needsAutoFaceColor"));
check('canonical-large-profiles-loaded',app.includes("largeReviewed")&&app.includes("for(const p of largeReviewed?.profiles||[])"));
check('generic-actor-base-not-gothgirl',app.includes("actorBase=profile.sourceFace?.faceColor || actor?.faceColor || null")&&app.includes("baseColor:actor.faceColor||null"));
check('loading-overlay-explicit-hide',styles.includes('.loading-card[hidden],.loading-card.is-hidden{display:none!important}')&&app.includes('function setLoading(show, detail=null)')&&app.includes('setLoading(false)'));
check('loading-overlay-errors-nonblocking',app.includes("bootError=err; console.error(err); setLoading(false)")&&app.includes("renderRoster(); save(); setLoading(false);"));
check('cleanup02-review-data',cleanup02Review.schema==='kfb.eye-cleanup-review/0.1-candidate'&&cleanup02Review.summary?.entries===31&&cleanup02Review.summary?.humanDecisionTotal===4);
check('cleanup02-skeleton-decisions',['skeleton-warrior','skeleton-rogue','skeleton-mage'].every((id)=>cleanup02Review.actorIssues?.[id]?.status==='HUMAN_DECISION_REQUIRED')&&cleanup02Review.externalIssues?.some((x)=>x.id==='prototype-pete'&&x.status==='HUMAN_DECISION_REQUIRED'));
check('cleanup02-review-ui',html.includes('id="cleanup02Badge"')&&html.includes('id="cleanup02Issue"')&&html.includes('id="cleanup02Summary"')&&html.includes('data-roster-filter="cleanup-issue"'));
check('cleanup02-review-runtime',app.includes("CLEANUP02_REVIEW_URL")&&app.includes('cleanup02Issue(actorId)')&&app.includes('renderCleanup02Issue()')&&app.includes('cleanup02Issue:cleanup02Issue(state.currentActorId)'));
check('source-anchor-derivation',adapter.includes('export function deriveSourceAnchorSeed')&&adapter.includes('cleanup02-root-eye-anchors')&&adapter.includes('source eye xy falls outside FaceHost surface'));
check('source-anchor-data-exact-path',cleanup02Anchors.schema==='kfb.cleanup02-source-anchors/0.1-candidate'&&cleanup02Anchors.source?.matchPolicy==='EXACT_SOURCE_PATH_ONLY'&&cleanup02Anchors.actorCount===19&&!cleanup02Anchors.actors?.monster&&cleanup02Anchors.actors?.monstrosity?.cleanupId==='monster');
check('source-anchor-clown-auto',cleanup02Anchors.actors?.clown?.autoApply===true&&cleanup02Anchors.actors?.clown?.anchors?.l?.pos?.[1]===1.6064);
check('source-anchor-human-decisions-not-auto',['skeleton-warrior','skeleton-rogue','skeleton-mage'].every((id)=>cleanup02Anchors.actors?.[id]?.autoApply===false));
check('source-anchor-asymmetry-not-auto',cleanup02Anchors.actors?.['animatronic-creepy']?.asymmetric===true&&cleanup02Anchors.actors?.['animatronic-creepy']?.autoApply===false);
check('source-anchor-runtime-auto',app.includes('deriveSourceAnchorSeed')&&app.includes("anchorRec.autoApply&&state.profile.reviewState==='UNREVIEWED'")&&app.includes("kind:'cleanup02-source-anchors'"));
check('source-anchor-dynamic-button',app.includes('function refreshPlacementSourceUi')&&app.includes('Use Cleanup02 source anchors')&&app.includes('currentPlacementCandidate()'));
check('placement-ranges-expanded',html.includes('data-param="dy" type="range" min="-2" max="1.5"')&&html.includes('data-param="ring" type="range" min="0.02" max="1.2"')&&html.includes('data-param="inset" type="range" min="-1.5" max="6"'));
check('placement-range-auto-expands',app.includes('function expandPlacementRange')&&app.includes("['dx','dy','ring','inset'].includes(k)"));
check('monster-mapping-corrected',cleanup02Review.mappingCorrection?.includes("Rig_Large actor 'monstrosity'")&&cleanup02Review.actorIssues?.monstrosity&&!cleanup02Review.actorIssues?.monster);
check('ring-depth-compensation-helper',adapter.includes('export function compensateInsetForRing')&&adapter.includes('oldSeat=oldRing*(SEAT_BASE+oldInset*SEAT_GAIN)')&&adapter.includes('oldSeat/newRing'));
check('ring-size-centre-lock-runtime',adapter.includes('setRingPreserveCenter(newRing)')&&app.includes('state.eyes.setRingPreserveCenter(v)')&&app.includes("state.profile.eye.inset=+r.inset"));
check('track-no-rebuild-runtime',adapter.includes('setTrack(track)')&&adapter.includes('rig.anchor.track=track')&&adapter.includes('rig._max=U*track')&&app.includes("state.eyes.setTrack(v)"));
check('studio-parity-control-labels',html.includes('>Height <output data-out="dy"')&&html.includes('>Eye size (ring) <output data-out="ring"')&&html.includes('>Gaze drift <output data-out="track"'));
check('control-semantics-hint',html.includes('Eye size changes size only (centre locked)')&&html.includes('Splay rotates and re-seats on the surface'));
check('control-semantics-report',app.includes("eyeSize:'size-only-centre-locked'")&&app.includes("inset:'depth-only'")&&app.includes("track:'gaze-amplitude-only'"));
check('mystery-monthly-coverage-49',mysteryCoverage.status==='CATALOG_COMPLETE_PROFILE_REVIEW_OPEN'&&mysteryCoverage.counts?.total===49&&mysteryCoverage.counts?.Rig_Medium===41&&mysteryCoverage.counts?.Rig_Large===8&&mysteryCoverage.actors?.length===49);
check('mystery-monthly-path-unique',new Set(mysteryCoverage.actors.map((a)=>a.path)).size===49);
check('paladin-both-models',mysteryCoverage.actors.some((a)=>a.id==='paladin')&&mysteryCoverage.actors.some((a)=>a.id==='paladin-helmet'));
check('paladin-king-palette',mysteryCoverage.paladin?.embeddedPalette==='A'&&mysteryCoverage.paladin?.kingCandidatePalette==='B'&&mysteryCoverage.actors.filter((a)=>a.id==='paladin'||a.id==='paladin-helmet').every((a)=>a.appearanceVariants?.some((v)=>v.id==='B')));
check('paladin-king-visible-actor',actors.actors.find((a)=>a.id==='paladin-king')?.textureOverride?.blob==='eb45816ada5c84bc91abc0225e3b25f5998accc1'&&mysteryCoverage.paladin?.workbenchKingActorId==='paladin-king'&&mysteryCoverage.paladin?.kingPaletteVisible===true);
check('texture-override-runtime',app.includes('async function applyActorTextureOverride')&&app.includes('new THREE.TextureLoader().loadAsync')&&app.includes('texture.flipY=false')&&app.includes('mat.map=texture')&&app.includes('state.textureOverrideReport=await applyActorTextureOverride'));
check('mystery-container-53-classified',mysteryCoverage.containerCoverage?.status==='ALL_53_GLBS_CLASSIFIED'&&mysteryCoverage.containerCoverage?.counts?.candidateGlbs===53&&mysteryCoverage.containerCoverage?.counts?.supportedPhysicalTotal===51);
check('mystery-container-mummies',actors.actors.filter((a)=>a.reviewGroup==='medium-mystery-extra').length===2&&['mummy-a','mummy-b'].every((id)=>actors.actors.some((a)=>a.id===id&&a.rigClass==='Rig_Medium'&&a.jointCount===23)));
check('mystery-container-custom-explicit',mysteryCoverage.containerCoverage?.customOrTemplateUnsupported?.some((a)=>a.id==='santa'&&a.jointCount===41)&&mysteryCoverage.containerCoverage?.customOrTemplateUnsupported?.some((a)=>a.id==='character-template'&&a.jointCount===41));
check('mystery-clanker-large-evidence',mysteryCoverage.actors.find((a)=>a.id==='clanker')?.rigClass==='Rig_Large'&&String(mysteryCoverage.actors.find((a)=>a.id==='clanker')?.rigEvidence||'').includes('Rig_Large string x10'));
check('inline-number-editors',app.includes("$$('output[data-out]').forEach")&&app.includes('Click value to type directly')&&app.includes("ev.key==='Enter'")&&app.includes("ev.key==='Escape'"));
check('boot-progress-visible',app.includes('function setBootProgress')&&app.includes('Loading catalogs + source contracts')&&app.includes('Controls ready · loading')&&app.includes('Boot failed ·'));
check('roster-wired-before-control-init',app.indexOf('wireRoster();')<app.indexOf('wireRuntimeControls(camera,controls,renderer)'));
check('inline-number-preserves-storage-key',app.includes("const STORAGE_KEY = 'kfb.toolbox.eye-rig-batch.v0'")&&app.includes('profiles:state.profiles'));
check('converge-range-expanded',html.includes('data-param="converge" data-expand="true" type="range" min="-2" max="3"'));
check('flexible-ranges-expand',app.includes('function expandNumericRange')&&html.includes('data-param="track" data-expand="true"')&&html.includes('data-param="ovalW" data-expand="true"'));
check('orc-raider-texture-source',actors.actors.find((a)=>a.id==='orc-raider')?.textureOverride?.blob==='2035dea050702373c5d2d3c9c49a3381c93b1122'&&actors.actors.find((a)=>a.id==='orc-raider')?.textureOverride?.materialNames?.includes('orc_texture_A'));
check('named-material-texture-override',app.includes('const materialNames=new Set')&&app.includes("materialNames.has(String(mat.name||''))")&&app.includes('if(!mat.map&&!named)continue'));
check('appearance-variant-family-count',appearanceVariants.counts?.families===25&&appearanceVariants.families?.length===25);
check('appearance-variant-source-count',appearanceVariants.counts?.sourceAppearanceVariants===56&&appearanceVariants.families.reduce((n,f)=>n+(f.variants?.length||0),0)===56);
check('appearance-magical-girl-four',JSON.stringify(appearanceVariants.families.find((f)=>f.id==='magical-girl')?.variants?.map((v)=>v.variant))===JSON.stringify(['A','B','C','D'])&&appearanceVariants.families.find((f)=>f.id==='magical-girl')?.actorIds?.includes('magical-girl'));
check('appearance-driver-base-b',JSON.stringify(appearanceVariants.families.find((f)=>f.id==='driver')?.variants?.map((v)=>v.variant))===JSON.stringify(['BASE','B'])&&appearanceVariants.families.find((f)=>f.id==='driver')?.actorIds?.includes('driver'));
check('appearance-all-families-mapped',appearanceVariants.families.every((f)=>Array.isArray(f.actorIds)&&f.actorIds.length>0));
check('appearance-blobs-pinned',appearanceVariants.families.every((f)=>f.variants.every((v)=>typeof v.blob==='string'&&v.blob.length===40&&v.revision===appearanceVariants.source.sourceRevision)));
check('appearance-farmers-source-gated',appearanceVariants.families.find((f)=>f.id==='farmers')?.runtimeSelectable===false&&appearanceVariants.families.find((f)=>f.id==='farmers')?.mappingStatus==='SOURCE_MAPPING_OPEN');
check('appearance-selector-runtime',html.includes('id="appearanceSelect"')&&html.includes('id="appearanceHint"')&&app.includes('function effectiveActor')&&app.includes('function setAppearanceVariant')&&app.includes('appearanceByActor:state.appearanceByActor')&&app.includes('APPEARANCE_VARIANTS_URL'));
check('appearance-shared-profile-key',app.includes('const baseActor=actorById(actorId),actor=effectiveActor(baseActor)')&&app.includes('state.profiles[state.profile.actorId]')&&!appearanceVariants.families.some((f)=>f.actorIds.includes('paladin-king')));
check('bounded-wheel-zoom-owner',app.includes('function createBoundedWheelZoom')&&app.includes('controls.enableZoom=false')&&app.includes('minDistance:1.6')&&app.includes('maxDistance:8'));
check('bounded-wheel-gesture-cap',app.includes('step:0.12')&&app.includes('gestureIn:0.65')&&app.includes('gestureOut:0.85')&&app.includes('gestureGapMs:160'));
check('bounded-wheel-frame-smoothing',app.includes('THREE.MathUtils.damp(current,desired,14')&&app.includes('THREE.MathUtils.clamp(damped-current,-0.09,0.09)'));
check('bounded-wheel-preset-resync',app.includes('state.wheelZoom?.syncToCamera?.()'));
check('bounded-wheel-runtime-report',app.includes("owner:'OrbitControls bounded-wheel input adapter'")&&app.includes('nativeZoom:false'));
check('clay-view-switch-ui',html.includes('data-stage-look="neutral"')&&html.includes('data-stage-look="clay"')&&html.includes('id="lookBadge"'));
check('clay-k1-donor-reuse',app.includes("import { makeK1 } from './lib/clay-k1.js'")&&app.includes('perMeshTris:4000')&&app.includes('maxLevels:2')&&app.includes('budgetTris:160000'));
check('clay-k1-reversible',app.includes('state.clayK1?.revert?.()')&&app.includes('state.clayK1.apply(state.figure)')&&app.includes('stageLook:state.stageLook'));
check('clay-excludes-eye-rig',app.includes('markNoClay(eyes.rig?.rig)')&&app.includes('markNoClay(eyes.faceHost?.box)'));
check('clay-floor-pinned-source',app.includes("CLAY_SOURCE_PIN = '74f7a690fbec88cf98ce0936f31b72ad3f1148f5'")&&app.includes('clay_floor_001_diffuse.jpg')&&app.includes('clay_floor_001_normal.jpg')&&app.includes('clay_floor_001_roughness.jpg'));
check('clay-ao-off-in-eyerig-view',!app.includes('.setAO(true)')&&!app.includes('setAO(true'));
check('no-global-schema-promotion',!app.includes('kfb.eye-profile/1'));
console.log(JSON.stringify({pass,fail,total:pass+fail,results},null,2)); if(fail)process.exit(1);
