import fs from 'node:fs';import assert from 'node:assert/strict';import {resolveFunction,resolveFamily,validateContext} from './music-resolver.mjs';
const reg=JSON.parse(fs.readFileSync(new URL('./runtime-registry.v1.json',import.meta.url),'utf8'));
const src=fs.readFileSync(new URL('./kfb-audio-runtime.mjs',import.meta.url),'utf8');
const checks=[];const check=(n,f)=>{try{f();checks.push([n,true])}catch(e){checks.push([n,false,e.message])}};
const base={schema:'kfb.audio.context.v1',seq:1,timestampMs:1,world:{worldId:'GLOBAL_BASE'},environment:{},movement:{mode:'IDLE',speed01:0,drive:false,airborne:false},social:{dialogueActive:false,sourceType:'NONE',intensity01:0},activity:{action01:0,race01:0,threat01:0,work01:0,crowd01:0}};
check('registry schema',()=>assert.equal(reg.schema,'kfb.audio.runtime-registry.v1'));
check('G verified',()=>assert.equal(reg.families.G.status,'SITE_RUNTIME_VERIFIED'));
check('D verified',()=>assert.equal(reg.families.D.status,'SITE_RUNTIME_VERIFIED'));
check('C not falsely verified',()=>assert.equal(reg.families.C.status,'SOURCE_PRESENT_RUNTIME_UNVERIFIED'));
check('no planned M runtime family',()=>assert.equal(reg.families.M,undefined));
check('no DOM document',()=>assert(!/\bdocument\b/.test(src)));
check('no DOM window',()=>assert(!/\bwindow\b/.test(src)));
check('no AudioContext constructor',()=>assert(!/new\s+(?:AudioContext|webkitAudioContext)/.test(src)));
check('context validation',()=>assert.equal(validateContext(base),base));
check('staying function',()=>assert.equal(resolveFunction(base),'STAYING'));
check('movement function',()=>assert.equal(resolveFunction({...base,movement:{...base.movement,speed01:.5}}),'MOVEMENT'));
check('talking priority',()=>assert.equal(resolveFunction({...base,social:{...base.social,dialogueActive:true},movement:{...base.movement,speed01:.8}}),'TALKING'));
check('work function',()=>assert.equal(resolveFunction({...base,activity:{...base.activity,work01:.8}}),'WORK'));
check('race function',()=>assert.equal(resolveFunction({...base,activity:{...base.activity,race01:.8}}),'RACE'));
check('movement maps G',()=>assert.equal(resolveFamily({context:{...base,movement:{...base.movement,speed01:.5}},registry:reg}).familyId,'G'));
check('talking maps D',()=>assert.equal(resolveFamily({context:{...base,social:{...base.social,dialogueActive:true}},registry:reg}).familyId,'D'));
check('staying unavailable does not fake family',()=>assert.equal(resolveFamily({context:base,registry:reg,previousFamily:null}).familyId,null));
const failed=checks.filter(x=>!x[1]);console.log(JSON.stringify({pass:checks.length-failed.length,total:checks.length,checks},null,2));if(failed.length)process.exit(1);
