import fs from 'node:fs';import assert from 'node:assert/strict';import {resolveFunction,resolveFamily,validateContext} from './music-resolver.mjs';
const reg=JSON.parse(fs.readFileSync(new URL('./runtime-registry.v1.json',import.meta.url),'utf8'));
const src=fs.readFileSync(new URL('./kfb-audio-runtime.mjs',import.meta.url),'utf8');
const checks=[];const check=(n,f)=>{try{f();checks.push([n,true])}catch(e){checks.push([n,false,e.message])}};
const base={schema:'kfb.audio.context.v1',seq:1,timestampMs:1,world:{worldId:'GLOBAL_BASE'},environment:{},movement:{mode:'IDLE',speed01:0,drive:false,airborne:false},social:{dialogueActive:false,sourceType:'NONE',intensity01:0},activity:{action01:0,race01:0,threat01:0,work01:0,crowd01:0}};
check('registry schema',()=>assert.equal(reg.schema,'kfb.audio.runtime-registry.v1'));
check('asset source pin',()=>assert.equal(reg.assetSource.pin,'276728f3f82f729cd1656b61e81d278856d736bb'));
check('G verified',()=>assert.equal(reg.families.G.status,'SITE_RUNTIME_VERIFIED'));
check('D verified',()=>assert.equal(reg.families.D.status,'SITE_RUNTIME_VERIFIED'));
check('C not falsely verified',()=>assert.equal(reg.families.C.status,'SOURCE_PRESENT_RUNTIME_UNVERIFIED'));
for(const id of ['M','N','O']) check(id+' source present only',()=>assert.equal(reg.families[id].status,'SOURCE_PRESENT_RUNTIME_UNVERIFIED'));
check('M actual BPM',()=>assert.equal(reg.families.M.bpm,112));
check('N actual BPM',()=>assert.equal(reg.families.N.bpm,70));
check('O actual BPM',()=>assert.equal(reg.families.O.bpm,82));
check('M stem count',()=>assert.equal(reg.families.M.stems.length,10));
check('N stem count',()=>assert.equal(reg.families.N.stems.length,11));
check('O stem count',()=>assert.equal(reg.families.O.stems.length,9));
check('M ambiguous layers muted',()=>assert(reg.families.M.stems.filter(s=>String(s.role).startsWith('UNCLASSIFIED')).every(s=>s.default===0)));
check('N ambiguous layers muted',()=>assert(reg.families.N.stems.filter(s=>String(s.role).startsWith('UNCLASSIFIED')).every(s=>s.default===0)));
check('no DOM document',()=>assert(!/\bdocument\b/.test(src)));
check('no DOM window',()=>assert(!/\bwindow\b/.test(src)));
check('no AudioContext constructor',()=>assert(!/new\s+(?:AudioContext|webkitAudioContext)/.test(src)));
check('context validation',()=>assert.equal(validateContext(base),base));
check('staying function',()=>assert.equal(resolveFunction(base),'STAYING'));
check('movement maps G',()=>assert.equal(resolveFamily({context:{...base,movement:{...base.movement,speed01:.5}},registry:reg}).familyId,'G'));
check('talking maps D',()=>assert.equal(resolveFamily({context:{...base,social:{...base.social,dialogueActive:true}},registry:reg}).familyId,'D'));
check('M not auto mapped before QA',()=>assert.notEqual(reg.profiles.GLOBAL_BASE.functionMappings.STAYING,'M'));
check('N not auto mapped before QA',()=>assert(!Object.values(reg.profiles.GLOBAL_BASE.functionMappings).includes('N')));
check('O not auto mapped before QA',()=>assert(!Object.values(reg.profiles.GLOBAL_BASE.functionMappings).includes('O')));
const failed=checks.filter(x=>!x[1]);console.log(JSON.stringify({pass:checks.length-failed.length,total:checks.length,checks},null,2));if(failed.length)process.exit(1);
