import { worldIdentity } from './world-kernel.js';
const $=q=>document.querySelector(q),canvas=$('#world'),ctx=canvas.getContext('2d',{alpha:false}),seedEl=$('#seed'),versionEl=$('#version'),levelEl=$('#level'),levelOut=$('#levelOut'),statusEl=$('#status'),identityEl=$('#identity'),fingerprintEl=$('#fingerprint'),genMsEl=$('#genMs'),queueEl=$('#queue'),editsEl=$('#edits'),migrateEl=$('#migration');
const worker=new Worker(new URL('./world-worker.js',import.meta.url),{type:'module'});let requestId=0,pending=0,current=null,edits=[],editBaseVersion=Number(versionEl.value);
function state(){return{seed:Number(seedEl.value)||1,generatorVersion:Number(versionEl.value)||1,level:Number(levelEl.value)||0}}
function editsKey(seed){return`kfb-world-kernel-lab:edits:${seed}`}
function loadEdits(){const s=state(),stored=JSON.parse(localStorage.getItem(editsKey(s.seed))||'{"baseGeneratorVersion":1,"items":[]}');edits=stored.items||[];editBaseVersion=stored.baseGeneratorVersion||s.generatorVersion;updateEditUI()}
function saveEdits(){const s=state();localStorage.setItem(editsKey(s.seed),JSON.stringify({baseGeneratorVersion:editBaseVersion,items:edits}));updateEditUI()}
function updateEditUI(){const s=state();editsEl.textContent=`${edits.length} authored`;const mismatch=edits.length&&editBaseVersion!==s.generatorVersion;migrateEl.textContent=mismatch?`migration check: edits were authored on g${editBaseVersion}`:'edit/base versions aligned';migrateEl.dataset.warn=mismatch?'1':'0'}
function requestRender(){const s=state();levelOut.textContent=s.level;identityEl.textContent=worldIdentity(s);statusEl.textContent=current?'coarse fallback visible · refining…':'generating…';pending++;queueEl.textContent=String(pending);worker.postMessage({id:++requestId,...s,size:180})}
function palette(v){const stops=[[46,39,34],[86,73,54],[109,124,73],[143,157,93],[205,190,150]],p=Math.max(0,Math.min(.999,v))*(stops.length-1),i=Math.floor(p),t=p-i,a=stops[i],b=stops[Math.min(i+1,stops.length-1)];return[0,1,2].map(k=>Math.round(a[k]+(b[k]-a[k])*t))}
function draw(result){current=result;const{heights,size,min,max,landmarks}=result,off=document.createElement('canvas');off.width=size;off.height=size;const octx=off.getContext('2d'),img=octx.createImageData(size,size);for(let i=0;i<heights.length;i++){const n=(heights[i]-min)/Math.max(.00001,max-min),[r,g,b]=palette(n),k=i*4;img.data[k]=r;img.data[k+1]=g;img.data[k+2]=b;img.data[k+3]=255}octx.putImageData(img,0,0);ctx.imageSmoothingEnabled=true;ctx.drawImage(off,0,0,canvas.width,canvas.height);ctx.save();for(const l of landmarks){const x=l.x*canvas.width,y=l.y*canvas.height;ctx.beginPath();ctx.arc(x,y,l.kind==='life-tree'?9:6,0,Math.PI*2);ctx.fillStyle='#f0e3bd';ctx.fill();ctx.strokeStyle='#352d27';ctx.lineWidth=2;ctx.stroke()}for(const e of edits){const x=e.x*canvas.width,y=e.y*canvas.height;ctx.beginPath();ctx.rect(x-6,y-6,12,12);ctx.fillStyle='#c76b55';ctx.fill();ctx.strokeStyle='#fff4d6';ctx.stroke()}ctx.restore();fingerprintEl.textContent=result.fingerprint;genMsEl.textContent=`${result.generationMs.toFixed(1)} ms`;statusEl.textContent='refined tile active'}
worker.onmessage=event=>{pending=Math.max(0,pending-1);queueEl.textContent=String(pending);if(event.data.id!==requestId)return;draw(event.data)};
for(const el of[seedEl,versionEl,levelEl])el.addEventListener('input',()=>{if(el===seedEl)loadEdits();else updateEditUI();requestRender()});
$('#regen').addEventListener('click',requestRender);$('#clearEdits').addEventListener('click',()=>{edits=[];editBaseVersion=state().generatorVersion;saveEdits();if(current)draw(current)});$('#adoptVersion').addEventListener('click',()=>{editBaseVersion=state().generatorVersion;saveEdits()});
canvas.addEventListener('click',e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;if(!edits.length)editBaseVersion=state().generatorVersion;edits.push({id:`E${Date.now()}`,x,y,label:'Authored anchor',kind:'authored'});saveEdits();if(current)draw(current)});
loadEdits();requestRender();
