/** Generated by tests/build_landmarks_p02.py from unchanged Pilot 01 host. */
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {buildLandmark,MODEL_IDS} from './geometry.mjs';
import {ZONES} from '../pilot-01/geometry.mjs';
import {zoneColours} from './presentation.mjs';
import {CITY_STYLE_URL} from '../pilot-01/presentation.mjs';
import {createLandmarkGroup,disposeLandmark} from '../pilot-01/three-adapter.mjs';
import {exportGLB} from '../pilot-01/glb.mjs';

export async function boot(){
 const status=document.querySelector('#status'),stage=document.querySelector('#stage'),canvas=document.querySelector('#view');
 const style=window.__KFB_EMBEDDED_CITY_STYLE__||await fetch(CITY_STYLE_URL).then(r=>{if(!r.ok)throw Error('City style HTTP '+r.status);return r.json();});
 const scene=new THREE.Scene();scene.background=new THREE.Color('#d7e0e8');
 const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
 const camera=new THREE.PerspectiveCamera(38,1,.1,10000);const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.09;controls.maxPolarAngle=Math.PI*.49;
 scene.add(new THREE.HemisphereLight(0xffffff,0x7c887b,1.6));
 const sun=new THREE.DirectionalLight(0xfff6e4,2.4);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.normalBias=.06;scene.add(sun);scene.add(sun.target);
 const content=new THREE.Group();scene.add(content);
 let assets=[],roots=[],floor=null,grid=null,paletteMode='city',overrides={},wire=false,active='kremlin-wall',diagonal=1;
 const metadata=Object.fromEntries(MODEL_IDS.map(id=>{const a=buildLandmark(id);return [id,{triangles:a.triangles,bounds:a.bounds,parts:a.parts.length}];}));
 const params=new URLSearchParams(location.search);if(MODEL_IDS.includes(params.get('model')))active=params.get('model');
 function resize(){const r=stage.getBoundingClientRect();if(r.width<1||r.height<1)return;renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();}
 function palette(a){return {...zoneColours(a,style,paletteMode),...overrides};}
 function recolour(){for(let i=0;i<roots.length;i++){const colours=palette(assets[i]);roots[i].traverse(o=>{if(o.isMesh){o.material.color.set(colours[o.userData.kfbMaterialZone]);o.material.wireframe=wire;}});}makeSwatches();}
 function makeSwatches(){
  const box=document.querySelector('#zones');box.replaceChildren();if(!assets.length)return;
  const used=new Set(assets.flatMap(a=>a.parts.map(p=>p.zone)));const p=palette(assets[0]);
  for(const zone of ZONES){if(!used.has(zone))continue;const label=document.createElement('label');const input=document.createElement('input');input.type='color';input.value=p[zone];input.setAttribute('aria-label',zone+' colour');input.addEventListener('input',()=>{overrides[zone]=input.value;for(const root of roots)root.traverse(o=>{if(o.isMesh&&o.userData.kfbMaterialZone===zone)o.material.color.set(input.value);});});label.append(input,document.createTextNode(zone));box.append(label);}
 }
 function frame(view='oblique'){
  const box=new THREE.Box3().setFromObject(content),s=box.getSize(new THREE.Vector3()),c=box.getCenter(new THREE.Vector3());diagonal=s.length();
  const v={oblique:[1,.68,1.1],front:[0,.16,1],side:[1,.16,0],top:[0,1,.001]}[view]||[1,.68,1.1];
  const direction=new THREE.Vector3(...v).normalize();
  const vertical=camera.fov*Math.PI/180,horizontal=2*Math.atan(Math.tan(vertical/2)*camera.aspect),distance=diagonal*.5/Math.sin(Math.min(vertical,horizontal)/2)*1.12;
  controls.target.copy(c);camera.position.copy(c).addScaledVector(direction,distance);camera.near=Math.max(.01,diagonal/4000);camera.far=distance+diagonal*12;camera.updateProjectionMatrix();controls.minDistance=diagonal*.035;controls.maxDistance=diagonal*8;controls.update();
  sun.position.copy(c).add(new THREE.Vector3(-diagonal*.65,diagonal,diagonal*.75));sun.target.position.copy(c);const sh=sun.shadow.camera,rad=Math.max(s.x,s.z,s.y)*.8;sh.left=-rad;sh.right=rad;sh.top=rad;sh.bottom=-rad;sh.near=.1;sh.far=diagonal*5;sh.updateProjectionMatrix();
 }
 function load(id){
  for(const r of roots){content.remove(r);disposeLandmark(r);}roots=[];assets=[];
  if(floor){scene.remove(floor);floor.geometry.dispose();floor.material.dispose();}if(grid){scene.remove(grid);grid.geometry.dispose();grid.material.dispose();}
  const ids=id==='compare'?MODEL_IDS.filter(id=>id!=='spasskaya'):[id];active=id;
  let cursor=0;for(const key of ids){const a=buildLandmark(key);const r=createLandmarkGroup(THREE,a,palette(a));if(id==='compare'){r.position.x=cursor-a.bounds.min[0];r.position.z=-(a.bounds.min[2]+a.bounds.max[2])/2;cursor+=a.bounds.size[0]+55;}assets.push(a);roots.push(r);content.add(r);}
  const box=new THREE.Box3().setFromObject(content),sz=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());const radius=Math.max(sz.x,sz.z)*.68+sz.y*.25;
  const floorMat=new THREE.MeshStandardMaterial({color:active==='giza'?'#d3c5a8':style.palette.green,roughness:1,flatShading:true});
  floor=new THREE.Mesh(new THREE.CylinderGeometry(radius,radius*1.025,Math.max(.3,radius*.012),48),floorMat);floor.position.set(center.x,-Math.max(.3,radius*.012)/2-.05,center.z);floor.receiveShadow=true;scene.add(floor);
  const span=Math.ceil(radius*2/10)*10;grid=new THREE.GridHelper(span,20,'#849382','#849382');grid.position.set(center.x,-.035,center.z);grid.visible=document.querySelector('#grid').checked;grid.material.transparent=true;grid.material.opacity=.35;scene.add(grid);
  resize();frame();recolour();
  const names=assets.map(a=>a.title).join(' + ');document.querySelector('#title').textContent=id==='compare'?'Same-scale lineup':names;
  document.querySelector('#note').textContent=id==='compare'?'All objects keep their metre dimensions. Camera fitting never normalizes model size. This is a showroom, not geographic placement.':assets[0].note;
  document.querySelector('#export').disabled=id==='compare';
  document.querySelector('#model').value=id;
  status.textContent=`${assets.reduce((s,a)=>s+a.triangles,0).toLocaleString('en')} triangles · ${roots.reduce((s,r)=>s+r.children.length,0)} material meshes · 1 unit = 1 m · ${sz.x.toFixed(1)} × ${sz.y.toFixed(1)} × ${sz.z.toFixed(1)} m`;
  if(window.__KFB_LANDMARK_PILOT__)window.__KFB_LANDMARK_PILOT__.active=id;
 }
 document.querySelector('#model').addEventListener('change',e=>load(e.target.value));
 document.querySelector('#palette').addEventListener('change',e=>{paletteMode=e.target.value;overrides={};recolour();});
 document.querySelector('#wire').addEventListener('change',e=>{wire=e.target.checked;recolour();});
 document.querySelector('#grid').addEventListener('change',e=>{if(grid)grid.visible=e.target.checked;});
 for(const b of document.querySelectorAll('[data-view]'))b.addEventListener('click',()=>frame(b.dataset.view));
 document.querySelector('#resetColours').addEventListener('click',()=>{overrides={};recolour();});
 document.querySelector('#export').addEventListener('click',()=>{const bytes=exportGLB(assets[0],palette(assets[0]));const url=URL.createObjectURL(new Blob([bytes],{type:'model/gltf-binary'}));const link=document.createElement('a');link.href=url;link.download='kfb-'+active+'-pilot-02.glb';link.click();setTimeout(()=>URL.revokeObjectURL(url),3000);});
 new ResizeObserver(()=>{resize();}).observe(stage);
 load(active);
 window.__KFB_LANDMARK_PILOT__={ready:true,active,metrics:metadata,units:'metre',movementOwner:'none-viewer-only',geographicBinding:null,donor:'pilot-02',styleSource:'tools/osm-city-lab/styles/kfb-city-v0.json',setModel:load,setView:frame};
 renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera);});
}
