(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],canvas=$('#smearCanvas'),scope=$('#scope'),ctx=canvas?.getContext?.('2d',{alpha:false});
if(!canvas||!scope||!ctx)return;
const dbg=$('#debugLabel'),focus=$('#focus'),focusLabel=$('#focusLabel'),zoomLabel=$('#objectiveLabel'),status=$('#status'),summary=$('#recipeSummary');
const count={rbc:$('#rbcCount'),wbc:$('#wbcCount'),plt:$('#pltCount')},WORLD={w:2400,h:1600},MIN=25,MAX=140,PAN=1.14;
const R={normal:{id:'normal',label:'NORMAL',rbc:1150,platelets:95,wbc:[['segmented_neutrophil',7],['mature_lymphocyte',4],['monocyte',2]],m:{micro:0,hypo:0,ellip:0,schist:0,poly:0},summary:'Normaler technischer Basis-Preset. Procedural RBCs; WBCs bleiben TEMP_VISUAL_DONOR.'},iron_deficiency:{id:'iron_deficiency',label:'EISENMANGEL · POC',rbc:1150,platelets:105,wbc:[['segmented_neutrophil',7],['mature_lymphocyte',4],['monocyte',2]],m:{micro:.50,hypo:.58,ellip:.11,schist:0,poly:.01},summary:'Technischer Composer-Test: kleinere/hypochromere RBC-Population + Teilmenge elliptischer/pencil-artiger Formen. Nicht medizinisch kalibriert.'},tma:{id:'tma',label:'TMA · POC',rbc:1120,platelets:32,wbc:[['segmented_neutrophil',7],['mature_lymphocyte',4],['monocyte',2]],m:{micro:0,hypo:0,ellip:0,schist:.065,poly:.035},summary:'Technischer Composer-Test: diverse Fragmentformen + reduzierte Plättchendichte. Häufigkeiten sind POC-Platzhalter.'}};
const qs=new URLSearchParams(location.search),preset=R[qs.get('preset')]?qs.get('preset'):'normal';
const S={seed:+qs.get('seed')||42,preset,mag:clamp(+qs.get('objective')||100,MIN,MAX),focus:0,view:{x:1200,y:800},cells:[],selected:null,pointers:new Map(),drag:null,pinch:null,velocity:{x:0,y:0}};
let raf=0,inertia=0,urlTimer=0;const reduce=!!matchMedia?.('(prefers-reduced-motion: reduce)').matches;
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function rng32(seed){let a=seed>>>0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}function gauss(r){let u=0,v=0;while(!u)u=r();while(!v)v=r();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}function rec(){return R[S.preset]}function z(){return .1466666667+S.mag*.0103333333}
function rbcClass(r,m){const q=r();if(q<m.schist)return'schistocyte_fragment';if(q<m.schist+m.ellip)return'elliptocyte_pencil_cell';if(q<m.schist+m.ellip+m.poly)return'polychromatophilic_rbc';return(r()<m.micro||r()<m.hypo)?'microcytic_hypochromic_rbc':'normal_erythrocyte'}
function mkRbc(r,i){const m=rec().m,cls=rbcClass(r,m);let rad=clamp(16+gauss(r)*1.15,13.4,18.8),aspect=clamp(1+gauss(r)*.04,.92,1.09),pallor=clamp(.31+gauss(r)*.022,.26,.36);if(cls==='microcytic_hypochromic_rbc'){rad*=.80+r()*.08;aspect=clamp(1+gauss(r)*.08,.86,1.18);pallor=clamp(.49+gauss(r)*.035,.42,.58)}if(cls==='elliptocyte_pencil_cell'){rad*=.94;aspect=1.65+r()*.55;pallor=.34+r()*.08}if(cls==='polychromatophilic_rbc'){rad*=1.05+r()*.08;pallor=.23+r()*.05}if(cls==='schistocyte_fragment'){rad*=.58+r()*.18;pallor=0;aspect=1}return{id:`rbc-${i}`,family:'rbc',class:cls,truth:cls,source:cls==='normal_erythrocyte'?'PROCEDURAL_POC':'TECHNICAL_PATHOLOGY_PLACEHOLDER',x:r()*WORLD.w,y:r()*WORLD.h,r:rad,aspect,pallor,rot:r()*Math.PI*2,seed:(S.seed*65537+i*31)>>>0}}
function mkPlt(r,i){return{id:`plt-${i}`,family:'platelet',class:'normal_platelet',truth:'normal_platelet',source:'PROCEDURAL_POC',x:r()*WORLD.w,y:r()*WORLD.h,r:2.1+r()*1.5,rot:r()*Math.PI,seed:(S.seed*131071+i*101)>>>0}}function mkWbc(r,type,i){const sz=type==='monocyte'?31:type==='segmented_neutrophil'?27:21;return{id:`wbc-${type}-${i}`,family:'wbc',class:type,truth:type,source:'PROCEDURAL_TEMP_VISUAL_DONOR',x:90+r()*(WORLD.w-180),y:90+r()*(WORLD.h-180),r:sz*(.92+r()*.15),rot:r()*Math.PI*2,seed:(S.seed*524287+i*337+type.length*13)>>>0}}
function generate(){const r=rng32(S.seed),o=rec(),a=[];for(let i=0;i<o.rbc;i++)a.push(mkRbc(r,i));for(let i=0;i<o.platelets;i++)a.push(mkPlt(r,i));let n=0;for(const[t,c]of o.wbc)for(let i=0;i<c;i++)a.push(mkWbc(r,t,n++));a.sort((x,y)=>x.family==='wbc'?1:y.family==='wbc'?-1:0);S.cells=a;count.rbc.textContent=o.rbc;count.plt.textContent=o.platelets;count.wbc.textContent=n;summary.textContent=o.summary;updateUI();requestDraw()}
function ellipse(c,rx,ry,fill,stroke){ctx.save();ctx.translate(c.x,c.y);ctx.rotate(c.rot);ctx.beginPath();ctx.ellipse(0,0,rx,ry,0,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=.7;ctx.stroke()}ctx.restore()}
function drawRbc(c){if(c.class==='schistocyte_fragment'){const r=rng32(c.seed),n=3+Math.floor(r()*3);ctx.save();ctx.translate(c.x,c.y);ctx.rotate(c.rot);ctx.beginPath();for(let i=0;i<n;i++){const a=i/n*Math.PI*2,rr=c.r*(.7+r()*.52),x=Math.cos(a)*rr,y=Math.sin(a)*rr;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.fillStyle='#d89096';ctx.fill();ctx.strokeStyle='rgba(126,72,79,.42)';ctx.stroke();ctx.restore();return}if(c.class==='polychromatophilic_rbc'){ellipse(c,c.r*c.aspect,c.r/c.aspect,'#aab7c8','rgba(92,92,118,.28)');return}const rx=c.r*c.aspect,ry=c.r/c.aspect,fill=c.class==='microcytic_hypochromic_rbc'?'#e2a9ad':'#d99299';ellipse(c,rx,ry,fill,'rgba(126,72,79,.26)');ctx.save();ctx.translate(c.x,c.y);ctx.rotate(c.rot);ctx.globalAlpha=c.class==='microcytic_hypochromic_rbc'?.92:.76;ctx.beginPath();ctx.ellipse(0,0,rx*clamp(c.pallor*1.42,.30,.78),ry*clamp(c.pallor*1.42,.30,.78),0,0,Math.PI*2);ctx.fillStyle='#f2dedb';ctx.fill();ctx.restore()}
function granules(c,r,n,col,alpha){ctx.save();ctx.fillStyle=col;ctx.globalAlpha=alpha;for(let i=0;i<n;i++){const a=r()*Math.PI*2,rr=Math.sqrt(r())*c.r*.72;ctx.beginPath();ctx.arc(c.x+Math.cos(a)*rr,c.y+Math.sin(a)*rr,.45+r()*.65,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawWbc(c){const r=rng32(c.seed);ctx.save();const g=ctx.createRadialGradient(c.x-c.r*.15,c.y-c.r*.15,1,c.x,c.y,c.r);if(c.class==='segmented_neutrophil'){g.addColorStop(0,'#f3eef6');g.addColorStop(1,'#d8d0e5');ctx.fillStyle=g;ctx.beginPath();ctx.arc(c.x,c.y,c.r,0,Math.PI*2);ctx.fill();granules(c,r,52,'#9674a6',.30);const n=3+Math.floor(r()*2);for(let i=0;i<n;i++){const a=c.rot+i/n*Math.PI*2;ctx.save();ctx.translate(c.x+Math.cos(a)*c.r*.30,c.y+Math.sin(a)*c.r*.24);ctx.rotate(a*.4);ctx.fillStyle='#593567';ctx.beginPath();ctx.ellipse(0,0,c.r*.20,c.r*.27,0,0,Math.PI*2);ctx.fill();ctx.restore()}}else if(c.class==='mature_lymphocyte'){g.addColorStop(0,'#d7e5f8');g.addColorStop(1,'#a7bce0');ctx.fillStyle=g;ctx.beginPath();ctx.arc(c.x,c.y,c.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#4d2c67';ctx.beginPath();ctx.arc(c.x+c.r*.02,c.y-c.r*.01,c.r*.71,0,Math.PI*2);ctx.fill()}else{g.addColorStop(0,'#d9e4ec');g.addColorStop(1,'#a9bccb');ctx.fillStyle=g;ctx.beginPath();ctx.arc(c.x,c.y,c.r,0,Math.PI*2);ctx.fill();granules(c,r,32,'#7f7791',.16);ctx.save();ctx.translate(c.x,c.y);ctx.rotate(c.rot);ctx.fillStyle='#65456e';ctx.beginPath();ctx.moveTo(-c.r*.45,-c.r*.22);ctx.bezierCurveTo(-c.r*.10,-c.r*.60,c.r*.42,-c.r*.34,c.r*.34,c.r*.05);ctx.bezierCurveTo(c.r*.28,c.r*.42,-c.r*.02,c.r*.52,-c.r*.32,c.r*.30);ctx.bezierCurveTo(-c.r*.04,c.r*.12,c.r*.02,-c.r*.10,-c.r*.45,-c.r*.22);ctx.fill();ctx.restore()}ctx.strokeStyle='rgba(72,49,83,.20)';ctx.beginPath();ctx.arc(c.x,c.y,c.r,0,Math.PI*2);ctx.stroke();ctx.restore()}
function drawPlt(c){const r=rng32(c.seed);ctx.save();ctx.translate(c.x,c.y);ctx.rotate(c.rot);ctx.fillStyle='#75508a';ctx.beginPath();ctx.ellipse(0,0,c.r*1.12,c.r*.72,.2,0,Math.PI*2);ctx.fill();ctx.globalAlpha=.5;ctx.fillStyle='#4d2e68';for(let i=0;i<3;i++){ctx.beginPath();ctx.arc((r()-.5)*c.r,(r()-.5)*c.r*.7,.4+r()*.4,0,Math.PI*2);ctx.fill()}ctx.restore()}
function requestDraw(){if(raf)return;raf=requestAnimationFrame(()=>{raf=0;draw()})}function resize(){const b=scope.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(b.width*d));canvas.height=Math.max(1,Math.round(b.height*d));canvas.style.width=b.width+'px';canvas.style.height=b.height+'px';requestDraw()}
function draw(){if(!canvas.width)return;const d=canvas.width/Math.max(1,scope.clientWidth),sc=z()*d,vw=canvas.width/sc,vh=canvas.height/sc;ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle='#f6eee9';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.save();ctx.setTransform(sc,0,0,sc,canvas.width/2-S.view.x*sc,canvas.height/2-S.view.y*sc);const r=rng32(S.seed^0xA53A9E37);ctx.fillStyle='rgba(146,102,97,.035)';for(let i=0;i<180;i++){ctx.beginPath();ctx.arc(r()*WORLD.w,r()*WORLD.h,.7+r()*1.6,0,Math.PI*2);ctx.fill()}for(const c of S.cells){if(c.x<S.view.x-vw/2-70||c.x>S.view.x+vw/2+70||c.y<S.view.y-vh/2-70||c.y>S.view.y+vh/2+70)continue;c.family==='rbc'?drawRbc(c):c.family==='platelet'?drawPlt(c):drawWbc(c)}ctx.restore();placeLabel()}
function toWorld(x,y){const b=canvas.getBoundingClientRect(),sc=z();return{x:S.view.x+(x-b.left-b.width/2)/sc,y:S.view.y+(y-b.top-b.height/2)/sc}}function toScreen(c){const b=scope.getBoundingClientRect(),sc=z();return{x:b.width/2+(c.x-S.view.x)*sc,y:b.height/2+(c.y-S.view.y)*sc,z:sc}}
function pick(x,y){const p=toWorld(x,y);let best=null,bp=-1,bs=99;for(const c of S.cells){const hit=c.family==='wbc'?c.r*1.18:c.family==='platelet'?c.r*2.7:c.r*1.02,d=Math.hypot(p.x-c.x,p.y-c.y);if(d>hit)continue;const pr=c.family==='wbc'?4:c.family==='platelet'?3:c.class!=='normal_erythrocyte'?2:1,s=d/hit;if(pr>bp||pr===bp&&s<bs){best=c;bp=pr;bs=s}}return best}
const names={segmented_neutrophil:'Segmentierter Neutrophiler',mature_lymphocyte:'Reifer Lymphozyt',monocyte:'Monozyt',normal_platelet:'Thrombozyt',normal_erythrocyte:'Erythrozyt',microcytic_hypochromic_rbc:'Mikrozytär / hypochrom',elliptocyte_pencil_cell:'Elliptozyt / Pencil Cell',schistocyte_fragment:'Schistozyten-Fragment · POC',polychromatophilic_rbc:'Polychromatischer Erythrozyt · POC'};
function select(c){if(!c){S.selected=null;dbg.hidden=true;return}S.selected=c.id;dbg.innerHTML=`<strong>${names[c.truth]||c.truth}</strong><br><span>${c.id} · ${c.source}</span>`;dbg.hidden=false;placeLabel()}
function placeLabel(){if(!S.selected){dbg.hidden=true;return}const c=S.cells.find(x=>x.id===S.selected);if(!c)return select(null);const b=scope.getBoundingClientRect(),p=toScreen(c),rad=Math.min(b.width,b.height)/2-12;if(Math.hypot(p.x-b.width/2,p.y-b.height/2)>rad){dbg.hidden=true;return}dbg.hidden=false;const w=dbg.offsetWidth||190,h=dbg.offsetHeight||48,cr=Math.max(4,c.r*p.z),gap=14;let left=p.x+cr+gap,side='right';if(left+w>b.width-10){left=p.x-cr-gap-w;side='left'}left=clamp(left,10,Math.max(10,b.width-w-10));const top=clamp(p.y-h/2,10,Math.max(10,b.height-h-10));Object.assign(dbg.style,{left:left+'px',top:top+'px',bottom:'auto',transform:'none'});dbg.dataset.side=side}
function clampView(){const sc=z(),w=scope.clientWidth/sc,h=scope.clientHeight/sc;S.view.x=w>=WORLD.w?WORLD.w/2:clamp(S.view.x,w*.48,WORLD.w-w*.48);S.view.y=h>=WORLD.h?WORLD.h/2:clamp(S.view.y,h*.48,WORLD.h-h*.48)}
function updateUI(){status.textContent=`${rec().label} · seed ${S.seed}`;zoomLabel.textContent=Math.round(S.mag)+'×';$$('[data-objective]').forEach(b=>b.classList.toggle('active',Math.abs(+b.dataset.objective-S.mag)<1.5));$$('[data-preset]').forEach(b=>b.classList.toggle('active',b.dataset.preset===S.preset))}
function sync(){try{const u=new URL(location.href);u.searchParams.set('preset',S.preset);u.searchParams.set('seed',S.seed);u.searchParams.set('objective',Math.round(S.mag));history.replaceState(null,'',u)}catch{}}function syncSoon(){clearTimeout(urlTimer);urlTimer=setTimeout(sync,90)}
function setMag(v,x,y,anchor){const b=scope.getBoundingClientRect(),cx=x??b.left+b.width/2,cy=y??b.top+b.height/2,a=anchor||toWorld(cx,cy);S.mag=clamp(v,MIN,MAX);const sc=z();S.view.x=a.x-(cx-b.left-b.width/2)/sc;S.view.y=a.y-(cy-b.top-b.height/2)/sc;clampView();updateUI();requestDraw();syncSoon()}
function stopInertia(){if(inertia){cancelAnimationFrame(inertia);inertia=0}}function glide(){if(reduce||Math.hypot(S.velocity.x,S.velocity.y)<.045)return;let vx=S.velocity.x,vy=S.velocity.y,last=performance.now();const step=t=>{const dt=Math.min(32,t-last);last=t;S.view.x+=vx*dt;S.view.y+=vy*dt;clampView();draw();const d=Math.pow(.84,dt/16.67);vx*=d;vy*=d;if(Math.hypot(vx,vy)>.012)inertia=requestAnimationFrame(step);else inertia=0};inertia=requestAnimationFrame(step)}
function pts(){return[...S.pointers.values()]}function mid(a,b){return{x:(a.x+b.x)/2,y:(a.y+b.y)/2}}function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}function beginDrag(p){S.drag={x:p.x,y:p.y,t:performance.now(),moved:false};S.velocity={x:0,y:0};scope.classList.add('dragging')}
function beginPinch(){const p=pts();if(p.length<2)return;const m=mid(p[0],p[1]);S.drag=null;S.pinch={d:Math.max(1,dist(p[0],p[1])),mag:S.mag,anchor:toWorld(m.x,m.y)};scope.classList.remove('dragging');scope.classList.add('pinching');stopInertia()}
scope.addEventListener('pointerdown',e=>{scope.setPointerCapture?.(e.pointerId);stopInertia();S.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});S.pointers.size===1?beginDrag({x:e.clientX,y:e.clientY}):S.pointers.size===2&&beginPinch()});
scope.addEventListener('pointermove',e=>{if(!S.pointers.has(e.pointerId))return;S.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(S.pointers.size>=2){const p=pts(),m=mid(p[0],p[1]);setMag(S.pinch.mag*dist(p[0],p[1])/S.pinch.d,m.x,m.y,S.pinch.anchor);return}if(!S.drag)return;const t=performance.now(),dx=e.clientX-S.drag.x,dy=e.clientY-S.drag.y,dt=Math.max(1,t-S.drag.t),sc=z(),mx=-dx/sc*PAN,my=-dy/sc*PAN;if(Math.hypot(dx,dy)>1.5)S.drag.moved=true;S.view.x+=mx;S.view.y+=my;S.velocity.x=S.velocity.x*.55+mx/dt*.45;S.velocity.y=S.velocity.y*.55+my/dt*.45;S.drag.x=e.clientX;S.drag.y=e.clientY;S.drag.t=t;clampView();requestDraw()});
function finish(e,cancel=false){const single=S.pointers.size===1,d=S.drag,moved=d?.moved;S.pointers.delete(e.pointerId);if(S.pointers.size>=2)return beginPinch();if(S.pointers.size===1){S.pinch=null;scope.classList.remove('pinching');beginDrag(pts()[0]);S.drag.moved=true;return}S.pinch=null;S.drag=null;scope.classList.remove('dragging','pinching');if(!cancel&&single&&!moved)select(pick(e.clientX,e.clientY));else if(moved)glide()}
scope.addEventListener('pointerup',e=>finish(e));scope.addEventListener('pointercancel',e=>finish(e,true));scope.addEventListener('wheel',e=>{e.preventDefault();stopInertia();const unit=e.deltaMode===1?.035:e.deltaMode===2?.22:.0015;setMag(S.mag*Math.exp(-e.deltaY*unit),e.clientX,e.clientY)},{passive:false});
$$('[data-objective]').forEach(b=>b.onclick=()=>setMag(+b.dataset.objective));$$('[data-preset]').forEach(b=>b.onclick=()=>{S.preset=b.dataset.preset;S.view={x:1200,y:800};select(null);generate();sync()});focus.oninput=()=>{S.focus=+focus.value;focusLabel.textContent=S.focus.toFixed(1);canvas.style.filter=`blur(${S.focus*.34}px)`};$('#resetView').onclick=()=>{stopInertia();S.view={x:1200,y:800};S.mag=100;focus.value=0;focus.oninput();select(null);updateUI();sync();requestDraw()};$('#newSeed').onclick=()=>{stopInertia();S.seed=Math.floor(Math.random()*999999)+1;S.view={x:1200,y:800};select(null);generate();sync()};
if('ResizeObserver'in window)new ResizeObserver(resize).observe(scope);else{addEventListener('resize',resize);resize()}generate();updateUI();sync();
})();
