import {chromium} from 'playwright';import fs from 'node:fs/promises';
const BASE=process.env.CA204_BASE_URL||'http://127.0.0.1:4173/kfb-hub/stage/combat/ca2-melee-lab/';
const EXPECTED=process.env.CA204_IMPLEMENTATION_HEAD||'';
const OUT=process.env.CA204_PROOF_DIR||'ca204-melee-evidence';
const checks=[];const check=(n,c,e='')=>{checks.push({name:n,pass:!!c,extra:e});if(!c)throw Error('FAIL '+n+' '+e);console.log('PASS',n,e)};
await fs.mkdir(OUT,{recursive:true});
const marker=await fetch(BASE+'SOURCE.json?x='+Date.now(),{cache:'no-store'}).then(async r=>({ok:r.ok,status:r.status,json:await r.json()}));
check('source marker HTTP',marker.ok,'status='+marker.status);check('implementation head',marker.json.implementationHead===EXPECTED,marker.json.implementationHead);
let browser;
try{
 browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const page=await browser.newPage({viewport:{width:1440,height:920}}),errors=[],failed=[];
 page.on('pageerror',e=>errors.push('pageerror '+String(e)));page.on('console',m=>{if(m.type()==='error')errors.push('console '+m.text())});page.on('response',r=>{if(r.status()>=400)failed.push({status:r.status(),url:r.url()})});
 const t0=Date.now(),r=await page.goto(BASE,{waitUntil:'domcontentloaded',timeout:60000});check('stage HTTP',r?.ok()===true,'status='+r?.status());
 await page.waitForFunction(()=>window.__KFB_CA204__?.ready||window.__KFB_CA204__?.error,null,{timeout:120000});const bootMs=Date.now()-t0;
 let s=await page.evaluate(()=>window.__KFB_CA204__.snapshot());
 check('lab ready',s.ready===true,JSON.stringify(s.error));check('default donor isolation',s.mode==='weapon',s.mode);
 check('skeleton one mixer',s.actor.skeletonMixer===1,String(s.actor.skeletonMixer));check('driver one mixer',s.actor.driverMixer===1,String(s.actor.driverMixer));
 check('right hand socket',/handslot.?r/i.test(s.actor.handBone||''),s.actor.handBone);
 check('weapon position identity',s.actor.weaponLocal.position.every(v=>Math.abs(v)<1e-9),JSON.stringify(s.actor.weaponLocal.position));
 const q=s.actor.weaponLocal.quaternion;check('weapon rotation identity',Math.abs(q[0])<1e-9&&Math.abs(q[1])<1e-9&&Math.abs(q[2])<1e-9&&Math.abs(q[3]-1)<1e-9,JSON.stringify(q));
 const m=s.markers;check('measured markers finite',Object.values(m).every(v=>Number.isFinite(v)),JSON.stringify(m));
 check('marker order',m.anticipation<=m.activeStart&&m.activeStart<=m.nominalContact&&m.nominalContact<=m.activeEnd&&m.activeEnd<=m.recoveryEnd,JSON.stringify(m));
 check('measured contact agrees marker',Math.abs(s.contactMeasurement.normalized-m.nominalContact)<1e-9,JSON.stringify(s.contactMeasurement));
 check('runtime not promoted',s.scope.arenaRuntimeMutated===false&&s.scope.currentPr5PunchMappingPreserved===true,JSON.stringify(s.scope));
 await page.screenshot({path:OUT+'/01-axe-isolated.png',fullPage:true});
 s=await page.evaluate(()=>window.__KFB_CA204__.setMode('mount'));check('mount mode',s.mode==='mount',s.mode);await page.screenshot({path:OUT+'/02-hand-mount.png',fullPage:true});
 s=await page.evaluate(()=>{const a=window.__KFB_CA204__.snapshot().markers;window.__KFB_CA204__.setMode('attack');return window.__KFB_CA204__.scrub(a.nominalContact)});
 check('contact scrub mode',s.mode==='attack',s.mode);await page.screenshot({path:OUT+'/03-contact-scrub.png',fullPage:true});
 await page.evaluate(()=>{window.__KFB_CA204__.setMiss(true);window.__KFB_CA204__.replay()});
 await page.waitForFunction(()=>{const s=window.__KFB_CA204__.snapshot();return s.ready&&!s.running&&s.missMode},{timeout:120000});
 s=await page.evaluate(()=>window.__KFB_CA204__.snapshot());
 check('forced miss has no hit',s.hitEvent===null,JSON.stringify(s.hitEvent));check('forced miss no damage/vfx/sfx',s.counters.damageIntent===0&&s.counters.vfx===0&&s.counters.sfxDispatch===0,JSON.stringify(s.counters));
 await page.screenshot({path:OUT+'/04-confirmed-miss.png',fullPage:true});
 await page.evaluate(()=>{window.__KFB_CA204__.setMiss(false);window.__KFB_CA204__.replay()});
 await page.waitForFunction(()=>window.__KFB_CA204__.snapshot().hitEvent!==null,null,{timeout:120000});
 s=await page.evaluate(()=>window.__KFB_CA204__.snapshot());
 check('confirmed hit event',s.hitEvent.type==='melee.hit',JSON.stringify(s.hitEvent));check('hit inside active window',s.hitEvent.normalized>=s.markers.activeStart&&s.hitEvent.normalized<=s.markers.activeEnd,String(s.hitEvent.normalized));
 check('reaction starts at hit',Math.abs(s.hitReactStartedAt-s.hitEvent.normalized)<1e-9,String(s.hitReactStartedAt));check('one damage intent',s.counters.damageIntent===1,JSON.stringify(s.counters));
 check('one impact VFX',s.counters.vfx===1,JSON.stringify(s.counters));check('one SFX dispatch',s.counters.sfxDispatch===1,JSON.stringify(s.counters));
 await page.screenshot({path:OUT+'/05-confirmed-contact.png',fullPage:true});
 await page.waitForFunction(()=>!window.__KFB_CA204__.snapshot().running,null,{timeout:120000});s=await page.evaluate(()=>window.__KFB_CA204__.snapshot());
 check('no duplicate event after recovery',s.counters.damageIntent===1&&s.counters.vfx===1&&s.counters.sfxDispatch===1,JSON.stringify(s.counters));
 await page.evaluate(()=>window.__KFB_CA204__.replay());await page.waitForFunction(()=>!window.__KFB_CA204__.snapshot().running,null,{timeout:120000});s=await page.evaluate(()=>window.__KFB_CA204__.snapshot());
 check('repeat attack resets and stays single',s.counters.damageIntent===1&&s.counters.vfx===1&&s.counters.sfxDispatch===1,JSON.stringify(s.counters));
 check('semantic SFX cue only',s.sfx.confirmedCue==='confirm.hit'&&s.sfx.bodyImpactCue===null&&s.sfx.acousticAcceptance==='PENDING',JSON.stringify(s.sfx));
 check('no failed resources',failed.length===0,JSON.stringify(failed));check('no page errors',errors.length===0,JSON.stringify(errors));
 await fs.writeFile(OUT+'/desktop.json',JSON.stringify({bootMs,checks,snapshot:s,failed,errors},null,2)+'\n');
 const narrow=await browser.newPage({viewport:{width:520,height:800}}),nerr=[],nfailed=[];narrow.on('pageerror',e=>nerr.push(String(e)));narrow.on('console',m=>{if(m.type()==='error')nerr.push(m.text())});narrow.on('response',r=>{if(r.status()>=400)nfailed.push({status:r.status(),url:r.url()})});
 const nr=await narrow.goto(BASE,{waitUntil:'domcontentloaded',timeout:60000});check('narrow HTTP',nr?.ok()===true,'status='+nr?.status());await narrow.waitForFunction(()=>window.__KFB_CA204__?.ready||window.__KFB_CA204__?.error,null,{timeout:120000});
 const ns=await narrow.evaluate(()=>{const a=window.__KFB_CA204__.snapshot().markers;window.__KFB_CA204__.setMode('attack');return window.__KFB_CA204__.scrub(a.nominalContact)});
 check('narrow contact ready',ns.ready&&ns.mode==='attack',JSON.stringify(ns.error));check('narrow no failed resources',nfailed.length===0,JSON.stringify(nfailed));check('narrow no page errors',nerr.length===0,JSON.stringify(nerr));
 await narrow.screenshot({path:OUT+'/06-narrow-contact.png',fullPage:true});await narrow.close();
 await fs.writeFile(OUT+'/result.json',JSON.stringify({implementationHead:EXPECTED,bootMs,checks,snapshot:s},null,2)+'\n');
 console.log('CA204_MELEE_RESULT',checks.filter(x=>x.pass).length+'/'+checks.length,'PASS');
 console.log('CA204_MARKERS_JSON',JSON.stringify(s.markers));
 console.log('CA204_PERF_JSON',JSON.stringify({bootMs}));
}finally{if(browser)await browser.close()}
