/* Asset Librarian search + Registry handoff → existing WB2 scene/Edit/Sculpt/save. */
import {hexMetrics,hexToWorld} from '../../../world_atlas/source/lib/hex-grid.js';
import {applyFilters} from '../../../asset_registry/librarian/search.js';
import {manifest} from './wb2-source-evidence.v1.js';
import {RESIDENT_SETS,RESIDENT_SOURCE} from './wb2-residents.v1.js';
const LABELS={basemodule_A:'Raumstation A',basemodule_B:'Raumstation B',basemodule_garage:'Raumstation · Garage',building_blacksmith_red:'Schmiede · rot',building_castle_red:'Burg · rot',building_grain:'Kornspeicher',building_home_A_green:'Wohnhaus A · grün',building_home_A_red:'Wohnhaus A · rot',building_home_B_green:'Wohnhaus B · grün',building_home_B_red:'Wohnhaus B · rot',building_lumbermill_green:'Sägewerk · grün',building_market_red:'Markt · rot',building_tavern_red:'Taverne · rot',building_watermill_green:'Wassermühle · grün',building_well_green:'Brunnen · grün',building_well_red:'Brunnen · rot',building_windmill_green:'Windmühle · grün','building-a.glb':'Industriegebäude A','building-b.glb':'Industriegebäude B','building-c.glb':'Industriegebäude C','building-l.glb':'Industriegebäude L','building-q.glb':'Industriegebäude Q',roofmodule_solarpanels:'Solardach',solarpanel:'Solarmodul',windturbine_tall:'Windrad'};
export function mountWorldStudio(A){
 const pane=document.createElement('section');pane.className='sec';const h=document.createElement('h2');h.textContent='Welt gestalten';const search=document.createElement('input');search.type='search';search.placeholder='Gebäude oder Resident suchen';search.setAttribute('aria-label','Bibliothek durchsuchen');
 const kinds=document.createElement('select');kinds.setAttribute('aria-label','Bibliothek auswählen');for(const [value,label]of [['buildings','Gebäude'],['residents','Residents']]){const o=document.createElement('option');o.value=value;o.textContent=label;kinds.append(o)}const rows=document.createElement('div'),details=document.createElement('p');details.className='src';const hex=document.createElement('input');hex.type='checkbox';hex.checked=true;const hexLabel=document.createElement('label');hexLabel.append(hex,document.createTextNode('Hex-Raster beim Platzieren'));pane.append(h,search,kinds,hexLabel,rows,details);A.registerDrawer('Resources','Bibliothek',pane);
 const views=document.createElement('div');views.className='row';const viewLabel=document.createElement('p');viewLabel.textContent='Welt ansehen · Bau-Kamera';pane.prepend(viewLabel,views);for(const [id,label]of [['world.kfb-town','Town'],['world.dystopia','Dystopia'],['world.utopia','Utopia'],['world.protopia','Protopia']]){const v=document.createElement('button');v.className='quiet';v.textContent=label;v.onclick=()=>{if(isolate){A.candidateEvidence.release();isolate=false}if(A.mvp.drive.active)A.mvp.drive.exit();A.candidateEvidence.frameWorld(id)};views.append(v)}

 const records=Object.entries(manifest.families).flatMap(([worldId,list])=>list.map((r,index)=>({...r,source:{...r.source,path:r.assetId},worldId,index,name:r.assetId.split('/').pop().replace(/\.gltf$/,''),path:r.assetId,kind:'model-3d',format:'GLTF',dependencyStatus:'ok',collectionPath:r.packId})));let selected=null,serial=0,isolate=false;
 function b(label,go,host){const x=document.createElement('button');x.className='quiet';x.textContent=label;x.onclick=()=>Promise.resolve(go()).catch(e=>{details.textContent=e.message;console.error(e)});host.append(x);return x}
 function target(){const p=A.play.position;const x=p.x+Math.sin(A.play.heading)*5,z=p.z+Math.cos(A.play.heading)*5;if(!hex.checked)return[x,null,z];const m=hexMetrics([2,0,2.309]),row=Math.round(z/m.rowStep),col=Math.round((x-(row&1?m.rowOffset:0))/m.colStep),q=hexToWorld(col,row,m);return[q[0],null,q[2]]}
 async function place(r){if(A.mvp.drive.active)A.mvp.drive.exit();if(isolate){A.candidateEvidence.release();isolate=false}A.setPlay(false);const id='studio.'+r.assetId+'#'+Date.now()+'-'+(++serial),rec={id,name:LABELS[r.name]||r.name,kind:r.residentSetId?'resident':'prop',source:r.source,transform:{position:target(),rotation:[0,A.play.heading+Math.PI,0],scale:[1,1,1]}};if(r.residentSetId)rec.residentSetId=r.residentSetId;else rec.registeredAssetId=r.assetId;
  await A.mountSceneRecords([rec]);A.selectRoot(A.sceneObjects.get(id));A.saveDoc();details.textContent='Platziert. Am Objekt verschieben, drehen oder skalieren; Bauen und Spielen teilen dieselbe Szene.';document.body.dataset.studioHandoff=JSON.stringify({schema:'kfb.asset-handoff.v1',consumer:'KFB WorldBuilder / WB2',suitabilityOwnedByReceiver:true,assets:[{assetId:r.assetId,path:r.path,source:r.source,packId:r.packId}],acceptedSceneObject:id});}
 function show(r){selected=r;details.replaceChildren();const t=document.createElement('p');t.textContent=(LABELS[r.name]||r.name)+' · '+r.packId;details.append(t);b('Original ansehen',async()=>{await A.candidateEvidence.inspect(r.residentSetId?'resident:'+r.residentSetId:r.worldId,'original',r.index||0);isolate=true;details.firstChild.textContent='Originalansicht · '+(LABELS[r.name]||r.name);document.body.dataset.studioSource=r.assetId},details);b('Zur Welt',()=>{if(isolate){A.candidateEvidence.release();isolate=false}A.setPlay(false)},details);b('In die Welt setzen',()=>place(r),details);}
 function render(){rows.replaceChildren();const all=kinds.value==='residents'?RESIDENT_SETS.map(r=>({assetId:'resident-set/'+r.id,path:'tools/KFB-ToolBox/_inbox/KFB_RESIDENT_ATLAS_SESSION_CUT_2026-10-04_r1/data/cast.js',residentSetId:r.id,name:r.title,packId:'Resident Atlas',kind:'model-3d',format:'GLTF',dependencyStatus:'ok',source:RESIDENT_SOURCE(r.id)})):records;const found=applyFilters(all,{query:search.value,formats:[],types:[],browseMode:'all'},80);for(const r of found.rows){const row=document.createElement('div');row.className='row';b(LABELS[r.name]||r.name,()=>show(r),row);rows.append(row)}document.body.dataset.studioPalette=JSON.stringify({owner:'Asset Librarian / Registry',rawTotal:found.rawTotal,total:found.total,sceneOwner:'WB2',selected:selected?.assetId||null})}
 search.oninput=render;kinds.onchange=render;render();return{pane,render,evidence:()=>({owner:'Asset Librarian applyFilters / native Registry source handoff',sceneOwner:'WB2',editOwner:'ToolBox Edit Layer',saveOwner:'WB2 scene document',placementGrid:'native Hex Atlas hex-grid.js @ 9c2fee62',buildingCandidates:records.length,residentCandidates:RESIDENT_SETS.length})};
}
