/* WB2 World Studio consumer. Existing scene/edit/save/render/Ground remain sole owners. */
import * as THREE from 'three';
import {createMusicalWorld} from './wb2-musical-world.v1.js';
import {mountWorldStudio} from './wb2-studio.v1.js';
import {RESIDENT_SETS,RESIDENT_SOURCE} from './wb2-residents.v1.js';
import {createMvpCards,CARD_REFS} from './wb2-cards.v1.js';
import {createJourney} from './wb2-journey.v1.mjs';
import {makeAlmanacPile} from './wb2-almanac-fan.v1.js';
import {BILLBOARD_SOURCE} from './wb2-billboards.v1.js';
import {createTaxiDrive,TAXI_SOURCE} from './wb2-taxi.v1.js';
import {EncounterBeatBus,createEncounterHost} from '../../../resident_atlas/life/encounter-bus.js';
import {createSongTransport,loadPlaylist} from '../../_inbox/KFB_RESIDENT_ATLAS_SESSION_CUT_2026-10-04_r1/lib/song-transport.js';
import {createSharedTheatreCurtain} from '../../_inbox/KFB Theatre Curtain v2/2026-09-24-theatre-curtain/game-ready/theatre-curtain-v1/runtime/kfb-theatre-curtain.mjs';
import '../../../../overworld/overworld-v13_2026-08-12/overworld-v13/chatter-phrases.js';
import '../../../../overworld/overworld-v13_2026-08-12/overworld-v13/chatter-2d.js';
import '../../../../overworld/overworld-v13_2026-08-12/overworld-v13/bubble-layout.js';
import '../../../../overworld/overworld-v13_2026-08-12/overworld-v13/bubble-ts.js';
const PIN='b6afb431c25e48767bf875c8b2eb74866f6946e5',DIR='tools/KFB-ToolBox/_inbox/KFB_RESIDENT_ATLAS_SESSION_CUT_2026-10-04_r1/data/';
const $=id=>document.getElementById(id),deep=v=>structuredClone(v);
const LABELS={'town.clown':'Clown','town.driver':'Driver','dystopia.orc':'Orc-Band','dystopia.demon':'Demon Lord','utopia.robots':'Robot Works','utopia.monstrosity':'Monstrosity','protopia.farmers':'Farmer Duo','protopia.lorekeeper':'Lorekeeper','town.taxi':'Taxi'};
const TEXT={
 'town.clown':'Bingo? Eine Uhr fürs Ende der Welt. Bring diese Karte zur Orc-Band in Dystopia!',
 'town.driver':'Bingo? Der Taxi-Schlüssel gehört dir. Zu Fuß kommst du überall hin; mit dem Taxi geht es schneller.',
 'dystopia.orc':'Die Doomsday Clock? Hör unser Konzert bis zum Ende. Dann schenken wir dir den Song, einen Tanz und den glänzenden Horizont.',
 'utopia.monstrosity':'BONGO! Diesen glänzenden Horizont kaufen? Oder lieber ablehnen und ein offenes Notizbuch mitnehmen?',
 'protopia.farmers':'BINGO! Ein offenes Notizbuch. Hier zählt Mitmachen. Die Rules-Lawyer-Karte ist für dich.',
 'protopia.lorekeeper':'BOGGLE? Regeln sind auch nur Geschichten. Wo hast du diese Karte gefunden?',
 'utopia.robots':'Wir arbeiten am perfekten Morgen. Du darfst dich umsehen.',
 'dystopia.demon':'BLÖDSINN! Der Song gehört zur Party. Sprich mit der Orc-Band.'
};
function download(name,value){const u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
export async function createMvp(A){
 const journey=createJourney(()=>A.doc),cards=createMvpCards(),bus=new EncounterBeatBus();
 let curtain=null,plaque=null,ready=false,entered=false,introOpening=false,drive=null,music=null,transport=null,playlist=null,played=0,previousSongTime=0,activeUnit=null,selectedTarget=null,offerChoice=null,heldCard=null,almanacOpen=false,dismissed=false,evidenceFrames=0,legendKey=null;
 const stage=$('stage'),bubbleHost=document.createElement('div');bubbleHost.style.cssText='position:absolute;inset:0;pointer-events:none;z-index:8';bubbleHost.cam={x:0,y:0};bubbleHost.zoomEff=()=>1;stage.append(bubbleHost);
 const phases=new Set(),phaseTotal=10;let enterButton=null,actorButton=null;
 function report(id){phases.add(id);if(plaque){const c=plaque.userData.canvas,x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.fillStyle='#f0dcc0';x.fillRect(0,0,c.width,c.height);x.fillStyle='#3c2417';x.textAlign='center';x.font='bold 88px serif';x.fillText('BLÖDSINN!',512,109);x.font='26px monospace';x.fillText(ready?'ENTER':('Welt wird geladen · '+Math.min(phases.size,phaseTotal)+' / '+phaseTotal),512,171);plaque.material.map.needsUpdate=true}document.body.dataset.mvpLoader=JSON.stringify({completed:phases.size,total:phaseTotal,ready,steps:[...phases]})}
 const host=createEncounterHost({bus,waitForDecision:true,durations:{approach:.2,greet:.25,offer:.25,react:.1,accept:.2,decline:.2,leave:.25},offerProvider:e=>journey.offer(e.targetId)});
 function unitFor(id){const root=targetRoot(id);const u={hp:1,x:0,y:0,unit:{bodyH:0},id,root};projectUnit(u);return u}
 function targetRoot(id){return A.sceneObjects.get(id==='dystopia.orc'?'dystopia.band':id)}
 function projectUnit(u){const root=targetRoot(u.id)||u.root;if(!root)return;const p=root.getWorldPosition(new THREE.Vector3());p.y+=u.id==='dystopia.orc'?3:2.8;p.project(A.camera);u.x=p.x*stage.clientWidth/2;u.y=-p.y*stage.clientHeight/2;}
 function speak(id,text,actions=[]){activeUnit=unitFor(id);window.OW_BUBBLE.zeigen(bubbleHost,activeUnit,{text,actions,stream:false});window.OW_BUBBLE.tick(bubbleHost);music?.speak(text)}
 function persist(){A.saveDoc();document.body.dataset.mvpMemory=JSON.stringify(journey.memory())}
 async function showCard(ref){const c=await cards.load(ref);if(heldCard)heldCard.group.removeFromParent();heldCard=c;A.camera.add(c.group);c.group.position.set(2.7,-1.6,-8);c.group.rotation.set(0,-.08,0);c.group.scale.setScalar(.8)}
 bus.subscribe(e=>{
  if(e.beat==='offer'&&!dismissed)presentOffer(e.targetId);
  if(e.beat==='accept'){const result=journey.choose(e.targetId,offerChoice);if(result.receipt?.kind==='card')showCard(result.receipt.ref).catch(fail);persist();if(result.receipt?.kind==='card')music?.card();if(result.ok)speak(e.targetId,result.receipt?.kind==='card'?'Deine Karte ist im Fractal Almanac.':result.receipt?.kind==='item'?'Der Taxi-Schlüssel gehört jetzt dir.':'Diese Begegnung bleibt im Almanac.',[{label:'Weiter',go:()=>{A.setPlay(true)}}]);}
  if(e.beat==='decline')A.setPlay(true);
  if(e.beat==='leave')music?.social(false);
  if(e.beat==='leave'&&!almanacOpen&&entered&&!drive?.active)A.setPlay(true);
 });
 function choose(id,choice){const o=journey.offer(id);offerChoice=choice;host.choose(o&&!o.missing.length&&!o.completed&&o.choice===choice?'accept':'decline');if(o?.completed){speak(id,'Wir kennen uns schon. Deine Erinnerung bleibt erhalten.',[{label:'Weiter',go:()=>A.setPlay(true)}]);}else if(o?.missing.length)speak(id,'Hier fehlt noch ein Schritt deiner Reise.',[{label:'Weiter',go:()=>A.setPlay(true)}]);}
 function subject(id,kind){const receipt=journey.memory().receipts.filter(r=>r.kind==='card').at(-1),ref=receipt?.ref;let n=journey.memory().receipts.length+journey.memory().seed;const rnd=()=>{n=Math.imul(n^n>>>15,1|n);return((n^n>>>14)>>>0)/4294967296};const biome=id.startsWith('town')?'city':id.startsWith('dystopia')?'dungeon':id.startsWith('utopia')?'town':'camp';const line=window.OW_CHATTER.line(bubbleHost,{zone:{biome,card:heldCard?.card?{t:heldCard.card.title,l:heldCard.card.lore}:null},unit:{id}},kind,rnd);journey.remember('subject:'+id+':'+kind+':'+(ref||'world'),id,'subject',{subjectRef:ref||A.doc.id,connector:({ask:'SHOW IT',philo:'SPIN IT',trade:'SELL IT'})[kind]});persist();if(kind==='ask'&&ref)showCard(ref).catch(fail);speak(id,typeof line==='string'?line:line?.text||LABELS[id],[{label:'Zurück',close:false,go:()=>presentOffer(id)}]);}
 function presentOffer(id){const o=journey.offer(id),actions=['bingo','bongo','boggle','bloedsinn'].map(choice=>({label:choice==='bloedsinn'?'BLÖDSINN!':choice.toUpperCase(),close:false,go:()=>choose(id,choice)}));actions.push({label:'Über Karten reden',close:false,go:()=>speak(id,'Was möchtest du mit deiner Karte machen?',[...([['SHOW IT','ask'],['SPIN IT','philo'],['SELL IT','trade']].map(([label,kind])=>({label,close:false,go:()=>subject(id,kind)}))),{label:'Zurück',close:false,go:()=>presentOffer(id)}])});if(id==='dystopia.orc')actions.unshift({label:transport?.playing&&transport.song.id==='demon-afro-strut'?'Musik pausieren':'Konzert starten',close:false,go:()=>{if(transport?.blobOk){if(!transport.playing&&transport.songTime()<.05){played=0;previousSongTime=0}music.party()}}});speak(id,TEXT[id]||LABELS[id],actions);}
 function nearest(){const p=A.play?.position;if(!p)return null;let best=null;for(const id of Object.keys(LABELS)){const r=targetRoot(id);if(!r?.visible)continue;const d=Math.hypot(p.x-r.position.x,p.z-r.position.z);if(d<(id==='dystopia.orc'?10:id==='protopia.farmers'?9:7)&&(!best||d<best.distance))best={id,distance:d}}return best}
 function interact(id=nearest()?.id){if(!entered||!id)return false;if(drive?.active){drive.exit();return true}if(id==='town.taxi'){if(!journey.owns('item.taxi-key.01')){speak(id,'Der Driver hat den Schlüssel.');return false}window.OW_BUBBLE.schliessen?.(bubbleHost);drive.enter();return true}journey.remember('resident:'+id,id,'met');if(id==='dystopia.orc')journey.remember('place:dystopia-party','dystopia.orc','visit');selectedTarget=id;music?.social(true);dismissed=false;A.pauseForEncounter();const result=host.start({actorId:'player',targetId:id,context:{worldId:A.doc.id}});if(!result.ok)presentOffer(id);return result.ok;}
 function framePlayer(){const h=A.play.evidence().bodyHeight;Object.assign(A.play.params,{cameraDistance:h*9,cameraHeight:h*5.5,cameraLookHeight:h*2.3,cameraLookAhead:h});}
 function fail(e){console.error(e);document.body.dataset.mvpError=String(e.message||e)}
 const almanac=document.createElement('section');almanac.hidden=true;almanac.className='wb2-mvp-almanac';almanac.style.cssText='position:absolute;left:20px;top:78px;max-height:calc(100% - 100px);overflow:auto;z-index:9;pointer-events:auto;color:#f4ead6';stage.append(almanac);
 const fanHost=document.createElement('div');fanHost.className='r9pile';const info=document.createElement('p'),heading=document.createElement('h2');heading.textContent='Fractal Almanac';almanac.append(heading,fanHost,info);
 const style=document.createElement('style');style.textContent='.r9pile{position:relative;pointer-events:auto;--e9:cubic-bezier(.4,0,.2,1)}.r9c{position:absolute;min-width:0;cursor:pointer;filter:drop-shadow(0 2px 4px #0005)}.r9c canvas{display:block;width:100%;height:100%}.r9pile:hover .r9c{filter:drop-shadow(0 6px 12px #0006)}';document.head.append(style);
 const fan=makeAlmanacPile(fanHost,{width:()=>Math.min(224,stage.clientWidth*.24),drawCard:(cv,c)=>{let drawn=false;return()=>{if(drawn)return;cv.width=c.mat.map.image.width;cv.height=c.mat.map.image.height;const x=cv.getContext('2d');x.drawImage(c.mat.map.image,0,0);if(c.dmat.map?.image)x.drawImage(c.dmat.map.image,0,0,cv.width,cv.height);drawn=true}}});
 async function openAlmanac(){almanacOpen=!almanacOpen;almanac.hidden=!almanacOpen;if(!almanacOpen){A.setPlay(true);return}if(drive?.active)drive.exit();A.pauseForEncounter();const receipts=journey.memory().receipts.filter(r=>r.kind==='card');const list=[];for(const r of receipts){const c=await cards.load(r.ref);list.push({card:c,title:c.card.title,click:()=>{info.textContent=c.card.title+' · gefunden bei '+(LABELS[r.residentId]||r.residentId)+' · '+r.time;showCard(r.ref)}})}fan.set(list);info.textContent=list.length?'Karte anklicken: Herkunft ansehen.':'Du sammelst Karten durch Begegnungen.';}
 function button(id,label,go,parent=$('wiGrp')){const b=document.createElement('button');b.id=id;b.textContent=label;b.onclick=()=>Promise.resolve(go()).catch(fail);parent.append(b);return b}
 const importer=document.createElement('input');importer.type='file';importer.accept='.json,application/json';importer.hidden=true;importer.onchange=async()=>{try{const b=JSON.parse(await importer.files[0].text());if(drive?.active)drive.exit();if(b.schema==='kfb.player-journey-bundle/1'){if(b.player?.actorProfileId!==A.play.evidence().actorProfileId)await A.play.setActor(b.player.actorProfileId);journey.applyBundle(b);A.play.readDoc(A.doc);persist();A.setPlay(true)}else if(b.schema==='kfb.authoring-workspace-bundle/1'){A.validateSceneDocument(b.scene);await A.applySceneDocument(b.scene);persist();A.setPlay(true)}else throw Error('Unbekanntes Speicherformat');document.body.dataset.mvpImport='PASS';}catch(e){fail(e)}finally{importer.value=''}};stage.append(importer);
 function exportJourney(){if(drive?.active)drive.exit();A.saveDoc();download('KFB_PlayerJourney.json',journey.exportBundle())}
 const API={journey,cards,report,get ready(){return ready},get entered(){return entered},get transport(){return transport},get drive(){return drive},get encounter(){return host.current},interact,choose,openAlmanac,exportJourney,
  async prepareIntro(){curtain=await createSharedTheatreCurtain({renderer:A.renderer});if(!A.camera.parent)A.scene.add(A.camera);A.camera.add(curtain.scene);curtain.scene.position.set(0,0,-4.8);const c=document.createElement('canvas');c.width=1024;c.height=208;plaque=new THREE.Mesh(new THREE.BoxGeometry(4.3,.88,.22),new THREE.MeshStandardMaterial({map:new THREE.CanvasTexture(c),roughness:1}));plaque.userData.canvas=c;plaque.position.set(0,-.1,-4.5);A.camera.add(plaque);report('curtain');enterButton=button('mvpEnter','Welt wird geladen',()=>API.enter(),stage);enterButton.disabled=true;actorButton=button('mvpActorChoice','Figur: FrizzleBob',()=>API.selectActor(),stage);actorButton.disabled=true;actorButton.style.cssText='position:absolute;left:calc(50% - 94px);top:70%;z-index:12';enterButton.style.cssText='position:absolute;left:calc(50% - 70px);top:61%;z-index:12;padding:12px 32px;font:700 18px serif';document.body.dataset.mvpPhase='LOADING';},
  async mount(){
   A.setPlay(false);report('world');const arch=A.world.archipelago,records=A.world.buildingSceneRecords();
   for(const def of RESIDENT_SETS){const a=arch.anchorMap.get(def.anchor);records.push({id:def.id,name:def.title,kind:'resident',residentSetId:def.id,source:RESIDENT_SOURCE(def.id),transform:{position:[a.position[0],null,a.position[2]],rotation:[0,a.heading,0],scale:[1,1,1]}})}
   const a=arch.anchorMap.get('town.vehicle.taxi.01');records.push({id:'town.taxi',name:'Taxi',kind:'prop',taxi:true,source:TAXI_SOURCE,transform:{position:[a.position[0],null,a.position[2]],rotation:[0,a.heading,0],scale:[1,1,1]}});
   for(const kind of ['band','disco']){const a=arch.anchorMap.get(kind==='band'?'dystopia.party.orc-singer':'dystopia.party.pentagram');records.push({id:'dystopia.'+kind,name:kind==='band'?'Orc-Band':'Resident Disco',kind:'resident',performanceSetId:kind,source:{commit:PIN,path:DIR+(kind==='band'?'resident-band-module-01.json':'resident-disco-01.json')},transform:{position:[a.position[0],null,a.position[2]],rotation:[0,0,0],scale:[1,1,1]}})}
   for(const n of arch.nodes){const a=arch.anchorMap.get(n.recipe.billboard.id);if(!a)throw Error('Required Billboard anchor missing '+n.id);records.push({id:n.recipe.billboard.id,name:'Billboard · '+n.recipe.label,kind:'prop',billboardWorldId:n.id,source:BILLBOARD_SOURCE,transform:{position:[a.position[0],null,a.position[2]],rotation:[0,Math.PI,0],scale:[.35,.35,.35]}})}
   if(!A.doc.studio){A.world.adoptBuildingObjects(()=>[...A.sceneObjects.values()].filter(r=>r.userData.registeredAssetId));await A.mountSceneRecords(records);A.doc.studio={schema:'kfb.wb2-world-studio/1',sourceProfile:'native-four-worlds',seed:3}}A.world.adoptBuildingObjects(()=>[...A.sceneObjects.values()].filter(r=>r.userData.registeredAssetId));if(A.doc.studio&&!A.doc.objects.some(o=>o.billboardWorldId))await A.mountSceneRecords(records.filter(r=>r.billboardWorldId));report('objects');report('player');
   try{const actor=A.doc.world?.player?.actorProfileId==='Mannequin_Medium'&&journey.memory().receipts.length?'Mannequin_Medium':'FrizzleBob_v5b';await A.play.setActor(actor);A.play.readDoc(A.doc);document.body.dataset.mvpActor=actor;}catch(e){console.warn('Optional FrizzleBob remains quarantined:',e.message);document.body.dataset.mvpActor='Mannequin_Medium_FALLBACK';}
   for(const ref of CARD_REFS){await cards.load(ref);report('card:'+ref)}
   playlist=await loadPlaylist(new URL('../../_inbox/KFB_RESIDENT_ATLAS_SESSION_CUT_2026-10-04_r1/data/disco-playlist-01.json',import.meta.url));const song=playlist.tracks.find(t=>t.id==='demon-afro-strut');if(!song)throw Error('Required signature song missing');
   music=createMusicalWorld(A,{signature:song,journey,onError:fail});await music.prepare();transport=createSongTransport(song,{requireVerified:true,getSharedGraph:()=>music.getSharedGraph(),onEnded:s=>{const result=journey.completeSong(s.id,{playedSeconds:transport.playedSeconds,duration:transport.duration,ended:true,gitBlob:transport.blobHash,blobOk:transport.blobOk});if(result.ok){persist();speak('dystopia.orc','Song und Tanz gehören jetzt zu deiner Sammlung.')}music.ended(s.id);}});await new Promise((ok,no)=>{const check=()=>{if(transport.state==='bereit'){transport.blobOk?ok():no(Error('Signature song blob mismatch'))}else if(transport.state.startsWith('fehlt'))no(Error(transport.state));};transport.onChange(check);check()});music.attach(transport);report('audio');
   drive=createTaxiDrive(A,{root:A.sceneObjects.get('town.taxi'),remember:journey.remember});report('interaction');
   framePlayer();for(const [id,label]of [['sculptObject','Objekte'],['sculptRaise','Anheben'],['sculptLower','Absenken']])$(id).childNodes[0].textContent=label;$('sculptUndo').textContent='Rückgängig';$('sculptClear').textContent='Zurücksetzen';API.studio=mountWorldStudio(A);button('mvpAlmanac','Almanac',openAlmanac);button('mvpJukebox','Jukebox',()=>{if(journey.owns('song:demon-afro-strut'))music.radio();else {const n=nearest();if(n?.id==='dystopia.orc')interact(n.id);else info.textContent='Songs findest du bei den Residents. Die Orc-Band spielt in Dystopia.';}});button('mvpExport','Reise speichern',exportJourney,almanac);button('mvpImport','Reise laden',()=>importer.click(),almanac);button('mvpDance','Tanzen',async()=>{if(!journey.owns('dance:kfb_dance_hip_hop_a')){info.textContent='Den Tanz lernst du bei der Orc-Band.';return}if(drive.active)drive.exit();A.setPlay(true);await A.play.setDancing(!A.play.evidence().dance.active);});button('mvpWorkspace','Studio speichern',()=>{if(drive.active)drive.exit();A.saveDoc();download('KFB_AuthoringWorkspace.json',{schema:'kfb.authoring-workspace-bundle/1',scene:deep(A.doc)})},API.studio.pane);button('mvpWorkspaceImport','Studio laden',()=>importer.click(),API.studio.pane);
   $('addActor').hidden=true;$('addProp').hidden=true;$('wiEdit').textContent='Bauen';$('wiPlay').childNodes[0].textContent='Spielen';$('wiHud').style.background='var(--panel)';$('wiHud').style.border='1px solid var(--line)';$('wiHud').style.borderRadius='7px';$('tabDoc').textContent='Szene';$('tabTerrain').textContent='Gelände';$('tabLook').textContent='Aussehen';$('save').textContent='Welt sichern';$('reload').textContent='Gesicherte Welt laden';API.studio.pane.append($('saveGrp'));document.querySelector('.brand').textContent='KFB World Studio';ready=true;actorButton.disabled=false;actorButton.textContent='Figur: '+(A.play.evidence().actorProfileId==='FrizzleBob_v5b'?'FrizzleBob':'Mannequin');report('interaction');enterButton.textContent='ENTER';enterButton.disabled=false;document.body.dataset.mvpPhase='READY_BEHIND_CURTAIN';A.setPlay(false);
  },
  async selectActor(){if(!ready||entered)return;const next=A.play.evidence().actorProfileId==='FrizzleBob_v5b'?'Mannequin_Medium':'FrizzleBob_v5b';await A.play.setActor(next);framePlayer();A.play.writeDoc(A.doc);actorButton.textContent='Figur: '+(next==='FrizzleBob_v5b'?'FrizzleBob':'Mannequin');document.body.dataset.mvpActor=next;},
  enter(){if(!ready||entered)return false;introOpening=true;entered=true;music.start();enterButton.hidden=true;actorButton.hidden=true;curtain.setState('open');plaque.visible=false;document.body.dataset.mvpPhase='ENTERING';return true},
  update(dt){if(curtain){curtain.update(dt);if(introOpening&&curtain.open>=.999){curtain.dispose();curtain=null;A.camera.remove(plaque);A.setPlay(true);document.body.dataset.mvpPhase='PLAYING'}}if(!ready)return;const legend=$('wiHud'),n=entered&&A.play.on?nearest():null,nextLegend=drive?.active?'drive':entered&&A.play.on?(n?.id||'ground'):'off';if(nextLegend!==legendKey){legendKey=nextLegend;if(nextLegend==='off'){if(!A.play.on)legend.hidden=true;}else{legend.hidden=false;legend.replaceChildren();if(nextLegend==='drive')legend.textContent='W Gas · S bremsen · A/D lenken · I aussteigen';else{const k=document.createElement('kbd');k.textContent=n?'I':'W/S';legend.append(k,document.createTextNode(n?(n.id==='town.taxi'?'Taxi benutzen':'Mit '+LABELS[n.id]+' sprechen'):'laufen · A/D drehen · Shift sprinten · Tab bauen'));}}}drive?.update(dt);music?.update(dt);for(const root of A.sceneObjects.values())if(root.userData.billboardWorldId)root.userData.lifecycle?.update(dt,{camera:A.camera});host.update(dt);if(activeUnit){projectUnit(activeUnit);window.OW_BUBBLE.tick(bubbleHost)}if(transport){const t=transport.songTime(),delta=t-previousSongTime;played=transport.playedSeconds;previousSongTime=t;const performing=transport.playing&&transport.song.id==='demon-afro-strut',clock={time:performing?t:0,beatPos:performing?transport.beatPos():0,spb:60/103.18,level:performing?transport.level():0,bass:performing?transport.bass():0,dt,camera:A.camera,playing:performing};for(const kind of ['band','disco']){const root=A.sceneObjects.get('dystopia.'+kind);if(root&&((transport.playing&&transport.song.id==='demon-afro-strut')||root.position.distanceTo(A.play.position)<45))root.userData.lifecycle?.update(dt,clock)}}if(++evidenceFrames%15===0)document.body.dataset.mvpEvidence=JSON.stringify(API.evidence());},
  evidence(){return{ready,entered,nearestInteraction:nearest(),selectedTarget,phase:document.body.dataset.mvpPhase,movementOwner:drive?.active?'J14 Drive':'WB2 Ground',residentSets:[...A.sceneObjects.values()].filter(r=>r.userData.lifecycle).map(r=>({id:r.userData.sceneObjectId,evidence:r.userData.lifecycle.evidence()})),cards:cards.evidence(),memory:deep(journey.memory()),audio:transport?{id:transport.song.id,state:transport.state,blobOk:transport.blobOk,songTime:transport.songTime(),playedSeconds:played,heardIntervals:transport.heardIntervals,playing:transport.playing}:null,drive:drive?.evidence(),musicalWorld:music?.evidence(),studio:API.studio?.evidence(),chatter:window.OW_CHATTER.report(),scenePlacements:[...A.sceneObjects.values()].filter(r=>r.userData.lifecycle).map(r=>({id:r.userData.sceneObjectId,position:r.position.toArray(),modelOffset:r.userData.model?.position.toArray(),groundY:A.world.groundAt(r.position.x,r.position.z,A.terrainHeightAt(r.position.x,r.position.z))})),sceneObjectCount:A.doc.objects.length};}
 };
 addEventListener('keydown',e=>{if(e.repeat||/^(INPUT|TEXTAREA|SELECT)$/.test(e.target?.tagName))return;if(e.code==='KeyI'){e.preventDefault();if(drive?.active)drive.exit();else interact()}if(e.code==='KeyY'&&entered){e.preventDefault();openAlmanac().catch(fail)}if(e.code==='Escape'){dismissed=true;music?.social(false);host.choose('decline');window.OW_BUBBLE.schliessen?.(bubbleHost);almanac.hidden=true;almanacOpen=false;if(entered&&!drive?.active)A.setPlay(true)}});
 return API;
}
