import { chromium } from 'playwright';
const base='http://127.0.0.1:8765/kfb-hub/stage/toolbox/production-r2-review/';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:900}});
const errors=[], failed=[];
page.on('pageerror',e=>errors.push(String(e)));
page.on('requestfailed',r=>failed.push(r.url()+' :: '+r.failure()?.errorText));
await page.goto(base,{waitUntil:'domcontentloaded',timeout:120000});
await page.waitForFunction(()=>window.__kfbTB && window.__kfbTB.state && window.__kfbTB.ws && window.__kfbTB.doc && window.__kfbTB.runtime && !window.__kfbTB.state.loading && ['ready','restored','self-test done'].includes(window.__kfbTB.state.status),{timeout:180000});
const boot=await page.evaluate(()=>({failures:window.__kfbTB.state.failures?.map(x=>x.name+': '+x.msg)||[],stage:document.querySelector('#kfb-stage')?.getBoundingClientRect().toJSON?.()||null,canvas:document.querySelector('#kfb-stage canvas')?.getBoundingClientRect().toJSON?.()||null}));
if(boot.failures.length) throw new Error('boot source failures: '+JSON.stringify(boot.failures));
const results=await page.evaluate(async()=>await window.__kfbTB.selfTest());
const bad=results.filter(x=>!x.ok);
if(results.length!==19||bad.length) throw new Error('selftest '+results.filter(x=>x.ok).length+'/'+results.length+' '+JSON.stringify(bad));
const dims=await page.evaluate(()=>{const c=document.querySelector('#kfb-stage canvas')?.getBoundingClientRect();return c?{w:c.width,h:c.height,vw:innerWidth,vh:innerHeight}:null;});
if(!dims||dims.w<700||dims.h<650) throw new Error('stage not dominant '+JSON.stringify(dims));
if(errors.length) throw new Error('page errors '+JSON.stringify(errors));
const ownerFailed=failed.filter(u=>/pose-rig|locomotion-profiles|ear-dangle|graft-mount|KFB_Motion_Library/.test(u));
if(ownerFailed.length) throw new Error('owner requests failed '+JSON.stringify(ownerFailed));
console.log('TOOLBOX R2 STAGE BROWSER PASS 19/19 · stage '+Math.round(dims.w)+'x'+Math.round(dims.h)+' · page errors 0 · owner request failures 0');
await browser.close();
