const $=id=>document.getElementById(id);
const seedEl=$('seed'),countEl=$('count'),countNEl=$('countN'),clusterEl=$('cluster'),fieldEl=$('field'),edgeEl=$('edge'),variantsEl=$('variants'),previewEl=$('preview'),recipeEl=$('recipe'),statusEl=$('status');
const STORAGE_KEY='kfb.world-seed-lab.poc.v0';
let variants=[],selectedIndex=0,pinned=null;

function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function toInt(v,f=0){const n=Number(v);return Number.isFinite(n)?Math.trunc(n):f}
function hash32(x){x|=0;x=Math.imul(x^(x>>>16),0x45d9f3b);x=Math.imul(x^(x>>>16),0x45d9f3b);return (x^(x>>>16))>>>0}
function mixSeed(base,i){return hash32((base|0)^Math.imul(i+1,0x9e3779b1))}
function rng32(seed){let s=(seed>>>0)||0x6d2b79f5;return()=>{s^=s<<13;s^=s>>>17;s^=s<<5;return (s>>>0)/4294967296}}
function params(){return{baseSeed:toInt(seedEl.value,1807),count:clamp(toInt(countEl.value,54),12,120),clusterStrength:Number(clusterEl.value),fieldScale:Number(fieldEl.value),edgeFalloff:Number(edgeEl.value),zoneSize:[20,20],categories:['tree','shrub','rock','flower']}}
function fieldValue(x,z,seed,p){const a=(seed%997)*0.017,b=((seed>>>8)%991)*0.019,s=p.fieldScale;const v=Math.sin(x*s+a)*.45+Math.cos(z*s*1.17+b)*.35+Math.sin((x+z)*s*.57+a*.4)*.2;return clamp((v+1)/2,0,1)}
function makePoints(seed,p){const r=rng32(seed),pts=[];let guard=0;while(pts.length<p.count&&guard<p.count*160){guard++;const x=(r()-.5)*p.zoneSize[0],z=(r()-.5)*p.zoneSize[1];const f=fieldValue(x,z,seed,p);const nx=Math.abs(x)/(p.zoneSize[0]/2),nz=Math.abs(z)/(p.zoneSize[1]/2),edge=Math.max(nx,nz);const edgeWeight=1-p.edgeFalloff*Math.pow(edge,1.7);const clusterWeight=(1-p.clusterStrength)+p.clusterStrength*(.18+.82*f);if(r()>clamp(clusterWeight*edgeWeight,.05,1))continue;const rr=r(),cat=rr<.44?'tree':rr<.68?'shrub':rr<.88?'rock':'flower';const scale=.65+r()*.75+f*.35;pts.push({x,z,cat,scale,f})}return pts}
function pointHash(pts){let h=2166136261>>>0;for(const p of pts){for(const n of [p.x,p.z,p.scale]){const q=Math.round(n*1000);h^=q&255;h=Math.imul(h,16777619);h^=(q>>>8)&255;h=Math.imul(h,16777619)}for(const c of p.cat){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}}return (h>>>0).toString(16).padStart(8,'0')}
function generateVariant(seed,p){const points=makePoints(seed,p);const cx=points.reduce((a,b)=>a+b.x,0)/(points.length||1),cz=points.reduce((a,b)=>a+b.z,0)/(points.length||1);return{seed,params:{count:p.count,clusterStrength:p.clusterStrength,fieldScale:p.fieldScale,edgeFalloff:p.edgeFalloff,zoneSize:p.zoneSize,categories:p.categories},points,hash:pointHash(points),stats:{count:points.length,centroid:[Number(cx.toFixed(3)),Number(cz.toFixed(3))]}}}
function generateSix(){const p=params();variants=Array.from({length:6},(_,i)=>generateVariant(mixSeed(p.baseSeed,i),p));selectedIndex=0;renderVariants();renderPreview();refreshRecipe()}
function catColor(cat){return{tree:'#66d48f',shrub:'#9ed870',rock:'#9aa4ae',flower:'#e89ac6'}[cat]||'#fff'}
function drawScatter(canvas,v,large=false){const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#1d281f';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#415444';ctx.lineWidth=1;for(let i=1;i<5;i++){ctx.beginPath();ctx.moveTo(i*w/5,0);ctx.lineTo(i*w/5,h);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i*h/5);ctx.lineTo(w,i*h/5);ctx.stroke()}for(const p of v.points){const x=(p.x/v.params.zoneSize[0]+.5)*w,y=(p.z/v.params.zoneSize[1]+.5)*h;ctx.fillStyle=catColor(p.cat);const r=(large?5:3)*p.scale;if(p.cat==='tree'){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}else if(p.cat==='rock'){ctx.fillRect(x-r,y-r,r*2,r*2)}else if(p.cat==='flower'){ctx.beginPath();ctx.moveTo(x,y-r);ctx.lineTo(x+r,y+r);ctx.lineTo(x-r,y+r);ctx.closePath();ctx.fill()}else{ctx.beginPath();ctx.ellipse(x,y,r*1.25,r*.75,0,0,Math.PI*2);ctx.fill()}}if(large){ctx.fillStyle='#dfe6dd';ctx.font='18px system-ui';ctx.fillText(`seed ${v.seed} · ${v.stats.count} items · hash ${v.hash}`,16,28)}}
function renderVariants(){variantsEl.innerHTML='';variants.forEach((v,i)=>{const d=document.createElement('div');d.className='variant'+(i===selectedIndex?' selected':'')+(pinned?.seed===v.seed?' pinned':'');const c=document.createElement('canvas');c.width=320;c.height=256;d.appendChild(c);const b=document.createElement('b');b.textContent=`Variant ${i+1} · seed ${v.seed}`;d.appendChild(b);const s=document.createElement('small');s.textContent=`${v.stats.count} points · hash ${v.hash}`;d.appendChild(s);d.onclick=()=>{selectedIndex=i;renderVariants();renderPreview()};variantsEl.appendChild(d);drawScatter(c,v,false)})}
function renderPreview(){const v=variants[selectedIndex];if(!v){const c=previewEl.getContext('2d');c.clearRect(0,0,previewEl.width,previewEl.height);return}drawScatter(previewEl,v,true)}
function pinSelected(){const v=variants[selectedIndex];if(!v)return;pinned={seed:v.seed,parameters:v.params,previewHash:v.hash,previewStats:v.stats};statusEl.innerHTML=`<b>PINNED</b><br>seed ${v.seed}<br>hash ${v.hash}<br>${v.stats.count} preview points`;renderVariants();refreshRecipe()}
function serialize(){return{schema:'kfb.world-recipe.v0-poc',status:'candidate-only',purpose:'Seed Lab scatter donor; Travel validation required',coordinateSpace:'poc-local',ownerBoundary:{runtimeSSOT:'georg-doc/KFB-Travel-Globe',terrainPlacementPersistence:'NOT OWNED HERE'},extensions:{proceduralCandidates:pinned?[{id:'zone-scatter-poc',kind:'SCATTER',generator:'kfb-seed-lab-scatter-v0',seed:pinned.seed,parameters:pinned.parameters,previewHash:pinned.previewHash,previewStats:pinned.previewStats,storePoints:false,note:'Seed + parameters only; generated point list intentionally not persisted.'}]:[]},updated:new Date().toISOString()}}
function refreshRecipe(){recipeEl.textContent=JSON.stringify(serialize(),null,2)}
function syncCount(fromRange=true){if(fromRange)countNEl.value=countEl.value;else countEl.value=clamp(toInt(countNEl.value,54),12,120);generateSix()}
function saveLocal(){localStorage.setItem(STORAGE_KEY,JSON.stringify({ui:params(),selectedIndex,pinned}))}
function loadLocal(){const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return alert('No local Seed Lab state saved.');try{const s=JSON.parse(raw),p=s.ui||{};seedEl.value=p.baseSeed??1807;countEl.value=p.count??54;countNEl.value=p.count??54;clusterEl.value=p.clusterStrength??.65;fieldEl.value=p.fieldScale??.26;edgeEl.value=p.edgeFalloff??.35;generateSix();selectedIndex=clamp(toInt(s.selectedIndex,0),0,5);pinned=s.pinned||null;renderVariants();renderPreview();statusEl.innerHTML=pinned?`<b>PINNED</b><br>seed ${pinned.seed}<br>hash ${pinned.previewHash||'—'}`:'Nothing pinned.';refreshRecipe()}catch(e){alert(`Seed Lab load error: ${e.message||e}`)}}

countEl.addEventListener('input',()=>{countNEl.value=countEl.value});countEl.addEventListener('change',()=>syncCount(true));countNEl.addEventListener('change',()=>syncCount(false));
for(const el of [clusterEl,fieldEl,edgeEl])el.addEventListener('change',generateSix);
$('generate').onclick=generateSix;$('next').onclick=()=>{seedEl.value=toInt(seedEl.value,1807)+6;generateSix()};$('pin').onclick=pinSelected;$('regen').onclick=renderPreview;$('save').onclick=saveLocal;$('load').onclick=loadLocal;
$('copy').onclick=async()=>navigator.clipboard.writeText(JSON.stringify(serialize(),null,2));$('download').onclick=()=>{const blob=new Blob([JSON.stringify(serialize(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='kfb-seed-lab-scatter-poc.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
seedEl.addEventListener('change',generateSix);
generateSix();