import {chromium} from 'playwright';import fs from 'node:fs/promises';
const BASE=process.env.CA203_BASE_URL||'http://127.0.0.1:4173/kfb-hub/stage/combat/ca2-enemy-adapters/';const EXPECTED=process.env.CA203_SOURCE_HEAD||'';const OUT=process.env.CA203_PROOF_DIR||'ca203-enum-evidence';const checks=[];const check=(n,c,e='')=>{checks.push({name:n,pass:!!c,extra:e});if(!c)throw Error('FAIL '+n+' '+e);console.log('PASS',n,e)};await fs.mkdir(OUT,{recursive:true});
const marker=await fetch(BASE+'SOURCE.json?x='+Date.now()).then(async r=>({ok:r.ok,json:await r.json()}));check('source marker HTTP',marker.ok);check('source marker head',marker.json.implementationHead===EXPECTED,marker.json.implementationHead);
let browser;try{browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1440,height:920}});const errors=[],failed=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('response',r=>{if(r.status()>=400)failed.push({status:r.status(),url:r.url()})});
const r=await page.goto(BASE,{waitUntil:'domcontentloaded',timeout:60000});check('stage HTTP',r?.ok()===true,'status='+r?.status());await page.waitForFunction(()=>window.__KFB_CA203_ENUM__?.ready||window.__KFB_CA203_ENUM__?.error,null,{timeout:120000});const snap=await page.evaluate(()=>window.__KFB_CA203_ENUM__.snapshot());check('enumerator ready',snap.ready===true,JSON.stringify(snap.error));check('exact model pin',snap.source.modelPin==='891eadf01e218f5fc21387e64cea1fec8332c5b6');check('exact animation pin',snap.source.animationPin==='11d7df978c63b9e375707bd8d9431b4c8358cda8');
check('three actors loaded',snap.actors.length===3);for(const a of snap.actors){check(a.id+' bones',a.facts?.bones?.count>0,String(a.facts?.bones?.count));check(a.id+' visible height',Number(a.facts?.bounds?.height)>0,String(a.facts?.bounds?.height))}
for(const rig of ['Medium','Large'])for(const set of ['General','MovementBasic','CombatMelee'])check(rig+' '+set+' clips',(snap.clipSets?.[rig]?.[set]?.length||0)>0,String(snap.clipSets?.[rig]?.[set]?.length||0));
for(const rig of ['Medium','Large'])for(const state of ['idle','move','attack','hit','defeat'])check(rig+' '+state+' candidate',(snap.semantics?.[rig]?.[state]?.length||0)>0,JSON.stringify(snap.semantics?.[rig]?.[state]||[]));
check('no Arena ownership',Object.values(snap.scope).every(v=>v===false),JSON.stringify(snap.scope));for(const id of ['skeleton-warrior','orc-brute','avian-swordsman']){await page.evaluate(x=>window.__KFB_CA203_ENUM__.select(x),id);await page.waitForTimeout(120);await page.screenshot({path:OUT+'/'+id+'.png',fullPage:true})}
check('no failed resources',failed.length===0,JSON.stringify(failed));check('no page errors',errors.length===0,JSON.stringify(errors));await fs.writeFile(OUT+'/enumeration.json',JSON.stringify({checks,snapshot:snap,failed,errors},null,2)+'\n');console.log('CA203_ENUM_RESULT',checks.filter(x=>x.pass).length+'/'+checks.length,'PASS');console.log('CA203_ENUM_JSON',JSON.stringify(snap));}finally{if(browser)await browser.close()}
