import fs from 'node:fs';
const idx=fs.readFileSync('kfb-hub/stage/toolbox/eye-actor-studio/index.html','utf8');
const app=fs.readFileSync('kfb-hub/stage/toolbox/eye-actor-studio/app.mjs','utf8');
const cluster=fs.readFileSync('tools/KFB-ToolBox/eye-actor-studio-v1/eye-cluster.v1.mjs','utf8');
const clay=fs.readFileSync('tools/KFB-ToolBox/eye-actor-studio-v1/clay-lid.v1.mjs','utf8');
const checks=[];const ok=(n,c)=>{checks.push([n,!!c]);if(!c)throw Error('FAIL '+n);console.log('PASS',n)};
ok('imports exact EyeRig v6',app.includes('pet-eye-rig.v6.js'));
ok('imports exact BrowRig v2',app.includes('brow-rig.v2.js'));
ok('imports exact EyeOval v1',app.includes('eyeoval.v1.js'));
ok('Eye Cluster schema',cluster.includes('kfb.eye-cluster/0.1-candidate'));
ok('count clamps 1-4',cluster.includes('clamp(Math.round(n),1,4)'));
ok('pair asymmetric preset',cluster.includes("'pair-asymmetric'"));
ok('frog side preset',cluster.includes("'pair-frog-side'"));
ok('single eye preset',cluster.includes("'single-eye'"));
ok('three eye preset',cluster.includes("'three-eye'"));
ok('four eye preset',cluster.includes("'four-eye'"));
ok('per-eye euler',cluster.includes('eulerDeg'));
ok('per-eye quaternion export',cluster.includes('quaternion'));
ok('per-eye size',cluster.includes('size'));
ok('per-eye W/H/D',cluster.includes('shape'));
ok('Clay lid hard rim',clay.includes('hardInnerRim:true'));
ok('scope selected',cluster.includes("scope==='selected'"));
ok('scope primary',cluster.includes("scope==='primary'"));
ok('mobile viewport',idx.includes('viewport-fit=cover'));
ok('mobile CSS',idx.includes('@media(max-width:820px)'));
ok('published debug object',app.includes('__KFB_EYE_ACTOR_STUDIO_V1__'));
console.log('KFB_EAS1_STATIC_RESULT',checks.length+'/'+checks.length,'PASS');
