const ROOT=new URL('../../../',location.href),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let spec=null,ctx=null,master=null,filter=null,laneNodes=new Map(),buffers=new Map(),sources=[],selected='neutral';
const state={loadedDonor:null,playing:false,contextCount:0,activity:.35,roadLift:0,night:0,voiceFocus:false,starts:[],errors:[]};
const BASE={drums:.50,bass:.72,guitar:.18,keyboard:.46,percussion:.13,strings:.07,synth:.16,other:.09,brass:.04,woodwinds:.05};
const ACT={drums:.32,bass:.10,guitar:.10,keyboard:.08,percussion:.24,strings:.02,synth:.06,other:.04,brass:.02,woodwinds:.01};
const ROAD={drums:.20,bass:.18,guitar:.09,keyboard:.05,percussion:.18,strings:-.03,synth:.10,other:.04,brass:.02,woodwinds:-.02};
const NIGHT={drums:-.12,bass:-.02,guitar:-.09,keyboard:-.08,percussion:-.11,strings:.06,synth:.10,other:.04,brass:-.01,woodwinds:.04};
const VOICE={drums:.74,bass:.80,guitar:.25,keyboard:.32,percussion:.42,strings:.22,synth:.28,other:.24,brass:.18,woodwinds:.20};
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,Number(v)||0));const rootURL=p=>new URL(p,ROOT).href;
function donor(){return spec.donors.find(d=>d.id===selected)}
function stemPath(d,s){return 'media/3D_Assets/Sounds/KFB RoadTrip JukeBox v2/'+d.stemDir+'/'+s[1]}
function target(role){let v=(BASE[role]||.05)+(ACT[role]||0)*state.activity+(ROAD[role]||0)*state.roadLift+(NIGHT[role]||0)*state.night;v=clamp(v,0,.95);if(state.voiceFocus)v*=VOICE[role]??.35;return clamp(v,0,.95)}
function targets(){return Object.fromEntries((donor()?.stems||[]).map(s=>[s[0],+target(s[0]).toFixed(3)]))}
function stop(){for(const s of sources){try{s.stop()}catch{}try{s.disconnect()}catch{}}sources=[];state.starts=[];state.playing=false;if(master&&ctx)master.gain.setTargetAtTime(.0001,ctx.currentTime,.08);render()}
function graph(){master=ctx.createGain();master.gain.value=.0001;filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=12000;filter.connect(master);master.connect(ctx.destination)}
async function decodeCurrent(){const d=donor();buffers.clear();laneNodes.clear();for(const s of sources){try{s.stop()}catch{}}sources=[];for(const s of d.stems){const r=await fetch(rootURL(stemPath(d,s)),{cache:'no-store'});if(!r.ok)throw new Error(stemPath(d,s)+' HTTP '+r.status);const b=await ctx.decodeAudioData((await r.arrayBuffer()).slice(0));buffers.set(s[0],b);const g=ctx.createGain();g.gain.value=.0001;g.connect(filter);laneNodes.set(s[0],g);}state.loadedDonor=d.id;renderLanes();applyMix(true)}
async function ensureContext(){if(!ctx){ctx=new AudioContext({latencyHint:'interactive'});state.contextCount++;graph()}if(ctx.state!=='running')await ctx.resume()}
async function loadSelected(){await ensureContext();$('#mode').textContent='LOADING…';await decodeCurrent();$('#play').disabled=false;$('#stop').disabled=false;$('#reset').disabled=false;render();return snapshot()}
function play(){if(state.loadedDonor!==selected)throw new Error('selected donor not loaded');stop();const t=ctx.currentTime+.10;master.gain.setValueAtTime(.88,t);filter.frequency.setValueAtTime(12000-state.night*7800,t);const starts=[];for(const s of donor().stems){const src=ctx.createBufferSource();src.buffer=buffers.get(s[0]);src.connect(laneNodes.get(s[0]));laneNodes.get(s[0]).gain.setValueAtTime(Math.max(.0001,target(s[0])),t);src.start(t);sources.push(src);starts.push(t)}state.starts=starts;state.playing=true;render()}
function setParam(p,v,tau=.18){if(!ctx)return;p.cancelScheduledValues(ctx.currentTime);p.setTargetAtTime(Math.max(.0001,v),ctx.currentTime,tau)}
function applyMix(immediate=false){if(!ctx||!donor())return;for(const s of donor().stems){const g=laneNodes.get(s[0]);if(!g)continue;const v=target(s[0]);if(immediate)g.gain.setValueAtTime(Math.max(.0001,v),ctx.currentTime);else setParam(g.gain,v)}const cutoff=12000-state.night*7800;if(immediate)filter.frequency.setValueAtTime(cutoff,ctx.currentTime);else setParam(filter.frequency,cutoff,.25);if(state.playing)setParam(master.gain,state.voiceFocus?.74:.88,.18);render()}
function selectDonor(id){if(selected===id)return;stop();selected=id;state.loadedDonor=null;buffers.clear();laneNodes.clear();const d=donor();state.activity=d.defaults.activity;state.roadLift=d.defaults.roadLift;state.night=d.defaults.night;state.voiceFocus=false;$('#play').disabled=true;syncUI();renderDonors();renderLanes();render()}
function setControl(n,v){state[n]=clamp(v);applyMix();return snapshot()}
function setVoice(v){state.voiceFocus=!!v;applyMix();syncUI();return snapshot()}
function preset(p){if(p==='calm'){state.activity=.12;state.roadLift=0;state.night=.12;state.voiceFocus=false}else if(p==='active'){state.activity=.82;state.roadLift=.10;state.night=0;state.voiceFocus=false}else if(p==='road'){state.activity=.78;state.roadLift=.85;state.night=0;state.voiceFocus=false}else if(p==='night'){state.activity=.28;state.roadLift=0;state.night=.88;state.voiceFocus=false}else if(p==='voice'){state.voiceFocus=true}syncUI();applyMix();return snapshot()}
function reset(){const d=donor();state.activity=d.defaults.activity;state.roadLift=d.defaults.roadLift;state.night=d.defaults.night;state.voiceFocus=false;syncUI();applyMix();return snapshot()}
function renderDonors(){const r=$('#donors');r.innerHTML='';for(const d of spec.donors){const b=document.createElement('button');b.className='donor'+(d.id===selected?' active':'');b.innerHTML='<b>'+d.title+'</b><span>'+d.mood+' · '+d.bpm+' BPM</span>';b.onclick=()=>selectDonor(d.id);r.appendChild(b)}}
function renderLanes(){const r=$('#lanes');r.innerHTML='';const d=donor();for(const s of d?.stems||[]){const el=document.createElement('div');el.className='lane';el.dataset.lane=s[0];el.innerHTML='<span>'+s[0].toUpperCase()+'</span><b>'+s[1]+'</b><div class="meter"><i></i></div><div class="meta">—</div>';r.appendChild(el)}}
function syncUI(){for(const id of ['activity','roadLift','night']){const el=$('#'+id);el.value=state[id];el.nextElementSibling.textContent=Math.round(state[id]*100)+'%'}$('#voiceFocus').setAttribute('aria-pressed',String(state.voiceFocus));$('#voiceFocus').textContent=state.voiceFocus?'ON':'OFF'}
function render(){const d=donor();if(d){$('#donorName').textContent=d.title;$('#mood').textContent=d.mood;$('#bpm').textContent=d.bpm}$('#mode').textContent=state.playing?'PLAYING':(state.loadedDonor===selected?'READY':'IDLE');const t=targets();for(const s of d?.stems||[]){const el=document.querySelector('[data-lane="'+s[0]+'"]');if(el){el.querySelector('.meter i').style.width=Math.round((t[s[0]]||0)*100)+'%';el.querySelector('.meta').textContent=(t[s[0]]||0).toFixed(2)}}$('#diag').textContent=JSON.stringify(snapshot(),null,2)}
function snapshot(){return{build:spec?.build||null,selected,loadedDonor:state.loadedDonor,playing:state.playing,contextCount:state.contextCount,contextState:ctx?.state||'none',controls:{activity:state.activity,roadLift:state.roadLift,night:state.night,voiceFocus:state.voiceFocus},targets:spec?targets():{},starts:[...state.starts],synchronizedStarts:state.starts.length<2||Math.max(...state.starts)-Math.min(...state.starts)<1e-7,stemCount:donor()?.stems?.length||0,donors:spec?.donors?.map(d=>({id:d.id,mood:d.mood,bpm:d.bpm,stemCount:d.stems.length}))||[],errors:[...state.errors]}}
function bind(){$('#load').onclick=()=>loadSelected().catch(e=>{state.errors.push(e.message);render()});$('#play').onclick=()=>{try{play()}catch(e){state.errors.push(e.message);render()}};$('#stop').onclick=stop;$('#reset').onclick=reset;for(const id of ['activity','roadLift','night'])$('#'+id).oninput=e=>{setControl(id,e.target.value);e.target.nextElementSibling.textContent=Math.round(e.target.value*100)+'%'};$('#voiceFocus').onclick=()=>setVoice(!state.voiceFocus);$$('[data-preset]').forEach(b=>b.onclick=()=>preset(b.dataset.preset))}
window.__KFB_MOOD_POOL__={loadSelected,play,stop,selectDonor,setControl,setVoice,preset,reset,snapshot};
fetch('./SOURCE.json',{cache:'no-store'}).then(r=>r.json()).then(s=>{spec=s;selected=spec.donors[0].id;renderDonors();renderLanes();bind();syncUI();render()}).catch(e=>{state.errors.push(e.message);render()});