const ROOT=new URL('../../../',location.href),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let spec=null,ctx=null,output=null,refGain=null,lowShelf=null,presence=null,nightFilter=null,laneNodes=new Map(),buffers=new Map(),sources=[],selected='neutral';
const state={loadedDonor:null,playing:false,mode:'idle',contextCount:0,activity:0,roadLift:0,night:0,voiceFocus:false,starts:[],errors:[],processing:{}};
const MASTER_LEVEL=.70;
const BASE={drums:.48,bass:.72,guitar:.16,keyboard:.48,percussion:.12,strings:.05,synth:.14,brass:.025};
const ACT={drums:.34,bass:.12,guitar:.10,keyboard:.08,percussion:.26,strings:.02,synth:.06,brass:.02};
const ROAD={drums:.18,bass:.16,guitar:.09,keyboard:.05,percussion:.18,strings:-.02,synth:.10,brass:.015};
const NIGHT={drums:-.12,bass:-.03,guitar:-.08,keyboard:-.08,percussion:-.10,strings:.05,synth:.08,brass:-.01};
const VOICE={drums:.72,bass:.78,guitar:.26,keyboard:.34,percussion:.42,strings:.24,synth:.28,brass:.20};
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,Number(v)||0)),rootURL=p=>new URL(p,ROOT).href;
function donor(){return spec.donors.find(d=>d.id===selected)}
function masterPath(d){return 'media/3D_Assets/Sounds/KFB RoadTrip JukeBox v2/'+d.master.file}
function stemPath(d,s){return 'media/3D_Assets/Sounds/KFB RoadTrip JukeBox v2/'+d.stemDir+'/'+s[1]}
function stemTarget(role){let v=(BASE[role]||0)+(ACT[role]||0)*state.activity+(ROAD[role]||0)*state.roadLift+(NIGHT[role]||0)*state.night;v=clamp(v,0,.95);if(state.voiceFocus)v*=VOICE[role]??.4;return clamp(v,0,.95)}
function stemTargets(){return Object.fromEntries((donor()?.runtimePolicy==='stem-certified'?donor().stems:[]).map(s=>[s[0],+stemTarget(s[0]).toFixed(3)]))}
function stop(){for(const s of sources){try{s.stop()}catch{}try{s.disconnect()}catch{}}sources=[];state.starts=[];state.playing=false;state.mode='idle';if(output&&ctx)output.gain.setTargetAtTime(.0001,ctx.currentTime,.05);if(refGain&&ctx)refGain.gain.setTargetAtTime(.0001,ctx.currentTime,.05);render()}
function graph(){output=ctx.createGain();refGain=ctx.createGain();lowShelf=ctx.createBiquadFilter();presence=ctx.createBiquadFilter();nightFilter=ctx.createBiquadFilter();lowShelf.type='lowshelf';lowShelf.frequency.value=180;presence.type='highshelf';presence.frequency.value=2200;nightFilter.type='lowpass';nightFilter.frequency.value=18000;nightFilter.Q.value=.12;lowShelf.connect(presence);presence.connect(nightFilter);nightFilter.connect(output);output.connect(ctx.destination);refGain.connect(ctx.destination);output.gain.value=.0001;refGain.gain.value=.0001}
async function decode(key,path){const r=await fetch(rootURL(path),{cache:'no-store'});if(!r.ok)throw new Error(path+' HTTP '+r.status);const b=await ctx.decodeAudioData((await r.arrayBuffer()).slice(0));buffers.set(key,b);return b}
async function ensureContext(){if(!ctx){ctx=new AudioContext({latencyHint:'interactive'});state.contextCount++;graph()}if(ctx.state!=='running')await ctx.resume()}
async function loadSelected(){await ensureContext();stop();const d=donor();buffers.clear();laneNodes.clear();$('#mode').textContent='LOADING…';await decode('master',masterPath(d));if(d.runtimePolicy==='stem-certified'){await Promise.all(d.stems.map(s=>decode('stem:'+s[0],stemPath(d,s))));for(const s of d.stems){const g=ctx.createGain();g.gain.value=.0001;g.connect(lowShelf);laneNodes.set(s[0],g)}}state.loadedDonor=d.id;$('#play').disabled=false;$('#playMaster').disabled=false;$('#stop').disabled=false;$('#reset').disabled=false;renderLanes();applyProcessing(true);render();return snapshot()}
function source(buffer,dest,t){const s=ctx.createBufferSource();s.buffer=buffer;s.connect(dest);s.start(t);sources.push(s);return s}
function playMaster(){if(state.loadedDonor!==selected)throw new Error('selected donor not loaded');stop();const t=ctx.currentTime+.10;refGain.gain.setValueAtTime(MASTER_LEVEL,t);source(buffers.get('master'),refGain,t);state.starts=[t];state.mode='master-reference';state.playing=true;render()}
function play(){if(state.loadedDonor!==selected)throw new Error('selected donor not loaded');stop();const d=donor(),t=ctx.currentTime+.10,starts=[];if(d.runtimePolicy==='stem-certified'){for(const s of d.stems){source(buffers.get('stem:'+s[0]),laneNodes.get(s[0]),t);starts.push(t)}state.mode='stem-certified'}else{source(buffers.get('master'),lowShelf,t);starts.push(t);state.mode='master-safe'}state.starts=starts;state.playing=true;applyProcessing(true);render()}
function setParam(p,v,tau=.18){if(!ctx)return;p.cancelScheduledValues(ctx.currentTime);p.setTargetAtTime(v,ctx.currentTime,tau)}
function applyProcessing(immediate=false){if(!ctx||!donor())return;const d=donor();if(d.runtimePolicy==='stem-certified'){for(const s of d.stems){const g=laneNodes.get(s[0]);if(!g)continue;const v=stemTarget(s[0]);if(immediate)g.gain.setValueAtTime(Math.max(.0001,v),ctx.currentTime);else setParam(g.gain,Math.max(.0001,v))}}const low=state.roadLift*1.8,high=state.activity*1.2+state.roadLift*.45-state.night*.8,cutoff=18000-state.night*9000,gain=MASTER_LEVEL*(state.voiceFocus?.72:1)*(1+state.activity*.02+state.roadLift*.02);if(immediate){lowShelf.gain.setValueAtTime(low,ctx.currentTime);presence.gain.setValueAtTime(high,ctx.currentTime);nightFilter.frequency.setValueAtTime(cutoff,ctx.currentTime);output.gain.setValueAtTime(gain,ctx.currentTime)}else{setParam(lowShelf.gain,low);setParam(presence.gain,high);setParam(nightFilter.frequency,cutoff,.24);setParam(output.gain,gain)}state.processing={lowShelfDb:+low.toFixed(2),presenceDb:+high.toFixed(2),lowpassHz:Math.round(cutoff),outputGain:+gain.toFixed(3)};render()}
function selectDonor(id){if(selected===id)return;stop();selected=id;state.loadedDonor=null;buffers.clear();laneNodes.clear();const d=donor();state.activity=d.defaults.activity;state.roadLift=d.defaults.roadLift;state.night=d.defaults.night;state.voiceFocus=false;$('#play').disabled=true;$('#playMaster').disabled=true;syncUI();renderDonors();renderLanes();render()}
function setControl(n,v){state[n]=clamp(v);applyProcessing();return snapshot()}
function setVoice(v){state.voiceFocus=!!v;applyProcessing();syncUI();return snapshot()}
function preset(p){const d=donor();if(p==='neutral'){state.activity=d.runtimePolicy==='stem-certified'?.35:0;state.roadLift=0;state.night=0;state.voiceFocus=false}else if(p==='calm'){state.activity=0;state.roadLift=0;state.night=.12;state.voiceFocus=false}else if(p==='active'){state.activity=.80;state.roadLift=.08;state.night=0;state.voiceFocus=false}else if(p==='road'){state.activity=.55;state.roadLift=.80;state.night=0;state.voiceFocus=false}else if(p==='night'){state.activity=.12;state.roadLift=0;state.night=.78;state.voiceFocus=false}else if(p==='voice'){state.voiceFocus=true}syncUI();applyProcessing();return snapshot()}
function reset(){const d=donor();state.activity=d.defaults.activity;state.roadLift=d.defaults.roadLift;state.night=d.defaults.night;state.voiceFocus=false;syncUI();applyProcessing();return snapshot()}
function renderDonors(){const r=$('#donors');r.innerHTML='';for(const d of spec.donors){const b=document.createElement('button');b.className='donor'+(d.id===selected?' active':'');b.innerHTML='<b>'+d.title+'</b><span>'+d.mood+' · '+d.bpm+' BPM · '+(d.runtimePolicy==='stem-certified'?'STEMS':'MASTER')+'</span>';b.onclick=()=>selectDonor(d.id);r.appendChild(b)}}
function renderLanes(){const r=$('#lanes');r.innerHTML='';const d=donor();if(!d)return;if(d.runtimePolicy==='master-safe'){const el=document.createElement('div');el.className='lane';el.dataset.lane='master';el.innerHTML='<span>MASTER GROUND TRUTH</span><b>'+d.master.file+'</b><div class="meter"><i style="width:100%"></i></div><div class="meta">'+d.stems.length+' source stems retained · inactive until certified</div>';r.appendChild(el);return}for(const s of d.stems){const el=document.createElement('div');el.className='lane';el.dataset.lane=s[0];el.innerHTML='<span>'+s[0].toUpperCase()+'</span><b>'+s[1]+'</b><div class="meter"><i></i></div><div class="meta">certified Cyclical stem path</div>';r.appendChild(el)}}
function syncUI(){for(const id of ['activity','roadLift','night']){const el=$('#'+id);el.value=state[id];el.nextElementSibling.textContent=Math.round(state[id]*100)+'%'}$('#voiceFocus').setAttribute('aria-pressed',String(state.voiceFocus));$('#voiceFocus').textContent=state.voiceFocus?'ON':'OFF'}
function render(){const d=donor();if(d){$('#donorName').textContent=d.title;$('#mood').textContent=d.mood;$('#bpm').textContent=d.bpm}$('#mode').textContent=state.mode.toUpperCase();if(d?.runtimePolicy==='stem-certified'){const t=stemTargets();for(const s of d.stems){const el=document.querySelector('[data-lane="'+s[0]+'"]');if(el){el.querySelector('.meter i').style.width=Math.round((t[s[0]]||0)*100)+'%'}}}$('#diag').textContent=JSON.stringify(snapshot(),null,2)}
function snapshot(){const d=donor();return{build:spec?.build||null,selected,loadedDonor:state.loadedDonor,playing:state.playing,mode:state.mode,runtimePolicy:d?.runtimePolicy||null,contextCount:state.contextCount,contextState:ctx?.state||'none',controls:{activity:state.activity,roadLift:state.roadLift,night:state.night,voiceFocus:state.voiceFocus},processing:{...state.processing},targets:d?.runtimePolicy==='stem-certified'?stemTargets():{master:1},starts:[...state.starts],synchronizedStarts:state.starts.length<2||Math.max(...state.starts)-Math.min(...state.starts)<1e-7,sourceStemCount:d?.stems?.length||0,loadedStemCount:[...buffers.keys()].filter(k=>k.startsWith('stem:')).length,masterLoaded:buffers.has('master'),donors:spec?.donors?.map(x=>({id:x.id,mood:x.mood,bpm:x.bpm,runtimePolicy:x.runtimePolicy,sourceStemCount:x.stems.length}))||[],errors:[...state.errors]}}
function bind(){$('#load').onclick=()=>loadSelected().catch(e=>{state.errors.push(e.message);render()});$('#playMaster').onclick=()=>{try{playMaster()}catch(e){state.errors.push(e.message);render()}};$('#play').onclick=()=>{try{play()}catch(e){state.errors.push(e.message);render()}};$('#stop').onclick=stop;$('#reset').onclick=reset;for(const id of ['activity','roadLift','night'])$('#'+id).oninput=e=>{setControl(id,e.target.value);e.target.nextElementSibling.textContent=Math.round(e.target.value*100)+'%'};$('#voiceFocus').onclick=()=>setVoice(!state.voiceFocus);$$('[data-preset]').forEach(b=>b.onclick=()=>preset(b.dataset.preset))}
window.__KFB_MOOD_POOL__={loadSelected,playMaster,play,stop,selectDonor,setControl,setVoice,preset,reset,snapshot};
fetch('./SOURCE.json',{cache:'no-store'}).then(r=>r.json()).then(s=>{spec=s;selected=spec.donors[0].id;renderDonors();renderLanes();bind();const d=donor();state.activity=d.defaults.activity;state.roadLift=d.defaults.roadLift;state.night=d.defaults.night;syncUI();render()}).catch(e=>{state.errors.push(e.message);render()});