const ROOT=new URL('../../../',location.href),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let spec=null,ctx=null,masterBus=null,filter=null,laneNodes=new Map(),buffers=new Map(),sources=[],selected='neutral';
const state={loadedDonor:null,playing:false,mode:'idle',contextCount:0,activity:0,roadLift:0,night:0,voiceFocus:false,starts:[],errors:[],reconstruction:null};
const MASTER_LEVEL=.70;
const ACT={drums:.10,bass:.04,guitar:.02,keyboard:.01,percussion:.10,strings:-.02,synth:.01,other:0,brass:.01,woodwinds:0,leadResidual:0,backingResidual:0};
const ROAD={drums:.08,bass:.06,guitar:.04,keyboard:.02,percussion:.07,strings:-.03,synth:.03,other:.01,brass:.01,woodwinds:-.01,leadResidual:0,backingResidual:0};
const NIGHT={drums:-.08,bass:-.02,guitar:-.04,keyboard:-.03,percussion:-.08,strings:.04,synth:.05,other:.02,brass:-.02,woodwinds:.03,leadResidual:0,backingResidual:0};
const VOICE={drums:.84,bass:.90,guitar:.74,keyboard:.70,percussion:.80,strings:.70,synth:.72,other:.70,brass:.68,woodwinds:.72,leadResidual:.80,backingResidual:.76};
const OLD_BASE={drums:.50,bass:.72,guitar:.18,keyboard:.46,percussion:.13,strings:.07,synth:.16,other:.09,brass:.04,woodwinds:.05};
const OLD_ACT={drums:.32,bass:.10,guitar:.10,keyboard:.08,percussion:.24,strings:.02,synth:.06,other:.04,brass:.02,woodwinds:.01};
const OLD_ROAD={drums:.20,bass:.18,guitar:.09,keyboard:.05,percussion:.18,strings:-.03,synth:.10,other:.04,brass:.02,woodwinds:-.02};
const clamp=(v,a=0,b=1.25)=>Math.max(a,Math.min(b,Number(v)||0)),rootURL=p=>new URL(p,ROOT).href;
function donor(){return spec.donors.find(d=>d.id===selected)}
function masterPath(d){return 'media/3D_Assets/Sounds/KFB RoadTrip JukeBox v2/'+d.master.file}
function stemPath(d,s){return 'media/3D_Assets/Sounds/KFB RoadTrip JukeBox v2/'+d.stemDir+'/'+s[1]}
function stemType(s){return s[4]||'music'}
function target(role){let v=1+(ACT[role]||0)*state.activity+(ROAD[role]||0)*state.roadLift+(NIGHT[role]||0)*state.night;v=clamp(v,.60,1.18);if(state.voiceFocus)v*=VOICE[role]??.74;return clamp(v,.50,1.18)}
function targets(){return Object.fromEntries((donor()?.stems||[]).map(s=>[s[0],+target(s[0]).toFixed(3)]))}
function oldTarget(role,d){if(role==='leadResidual'||role==='backingResidual')return 0;let v=(OLD_BASE[role]||.05)+(OLD_ACT[role]||0)*(d.id==='sunshine'?.74:d.defaults.activity||0)+(OLD_ROAD[role]||0)*(d.id==='sunshine'?.20:d.defaults.roadLift||0);return Math.max(0,Math.min(.95,v))}
function stop(){for(const s of sources){try{s.stop()}catch{}try{s.disconnect()}catch{}}sources=[];state.starts=[];state.playing=false;state.mode='idle';if(masterBus&&ctx)masterBus.gain.setTargetAtTime(.0001,ctx.currentTime,.05);render()}
function graph(){masterBus=ctx.createGain();masterBus.gain.value=.0001;filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=16000;filter.Q.value=.12;filter.connect(masterBus);masterBus.connect(ctx.destination)}
async function decode(key,path){const r=await fetch(rootURL(path),{cache:'no-store'});if(!r.ok)throw new Error(path+' HTTP '+r.status);const b=await ctx.decodeAudioData((await r.arrayBuffer()).slice(0));buffers.set(key,b);return b}
function metric(master,stems,weights){const m=master.getChannelData(0),arrays=stems.map(x=>x.buffer.getChannelData(0)),n=Math.min(m.length,...arrays.map(a=>a.length)),stride=Math.max(1,Math.floor(n/180000));let dot=0,mm=0,ss=0,count=0;for(let i=0;i<n;i+=stride){let s=0;for(let j=0;j<arrays.length;j++)s+=arrays[j][i]*(weights?weights[j]:1);const x=m[i];dot+=x*s;mm+=x*x;ss+=s*s;count++}const scale=ss>0?dot/ss:1;let ee=0;for(let i=0;i<n;i+=stride){let s=0;for(let j=0;j<arrays.length;j++)s+=arrays[j][i]*(weights?weights[j]:1);const e=m[i]-s*scale;ee+=e*e}const corr=dot/Math.sqrt(Math.max(1e-20,mm*ss)),masterRms=Math.sqrt(mm/Math.max(1,count)),errorRms=Math.sqrt(ee/Math.max(1,count));return{scale:+scale.toFixed(5),corr:+corr.toFixed(5),errorRatio:+(errorRms/Math.max(1e-9,masterRms)).toFixed(5),samples:count}}
function measureReconstruction(){const d=donor(),master=buffers.get('master'),all=d.stems.map(s=>({s,buffer:buffers.get('stem:'+s[0])})),music=all.filter(x=>stemType(x.s)!=='residual');const allMetric=metric(master,all);const musicMetric=metric(master,music);const oldWeights=all.map(x=>oldTarget(x.s[0],d));const oldMetric=metric(master,all,oldWeights);state.reconstruction={all:allMetric,instrumentOnly:musicMetric,oldWeighted:oldMetric,residualRoles:all.filter(x=>stemType(x.s)==='residual').map(x=>x.s[0])};return state.reconstruction}
async function ensureContext(){if(!ctx){ctx=new AudioContext({latencyHint:'interactive'});state.contextCount++;graph()}if(ctx.state!=='running')await ctx.resume()}
async function loadSelected(){await ensureContext();stop();const d=donor();buffers.clear();laneNodes.clear();$('#mode').textContent='LOADING…';const jobs=[decode('master',masterPath(d))];for(const s of d.stems)jobs.push(decode('stem:'+s[0],stemPath(d,s)));await Promise.all(jobs);for(const s of d.stems){const g=ctx.createGain();g.gain.value=1;g.connect(filter);laneNodes.set(s[0],g)}state.reconstruction=null;measureReconstruction();state.loadedDonor=d.id;$('#play').disabled=false;$('#playMaster').disabled=false;$('#stop').disabled=false;$('#reset').disabled=false;renderLanes();applyMix(true);render();return snapshot()}
function source(buffer,dest,t){const s=ctx.createBufferSource();s.buffer=buffer;s.connect(dest);s.start(t);sources.push(s);return s}
function playMaster(){if(state.loadedDonor!==selected)throw new Error('selected donor not loaded');stop();const t=ctx.currentTime+.10;filter.frequency.setValueAtTime(18000,t);masterBus.gain.setValueAtTime(MASTER_LEVEL,t);source(buffers.get('master'),filter,t);state.starts=[t];state.mode='master';state.playing=true;render()}
function play(){if(state.loadedDonor!==selected)throw new Error('selected donor not loaded');stop();const t=ctx.currentTime+.10,scale=state.reconstruction?.all?.scale||1;masterBus.gain.setValueAtTime(MASTER_LEVEL*clamp(scale,.20,2.0),t);filter.frequency.setValueAtTime(16000-state.night*9000,t);const starts=[];for(const s of donor().stems){const src=source(buffers.get('stem:'+s[0]),laneNodes.get(s[0]),t);starts.push(t)}state.starts=starts;state.mode='adaptive';state.playing=true;applyMix(true);render()}
function setParam(p,v,tau=.18){if(!ctx)return;p.cancelScheduledValues(ctx.currentTime);p.setTargetAtTime(Math.max(.0001,v),ctx.currentTime,tau)}
function applyMix(immediate=false){if(!ctx||!donor())return;for(const s of donor().stems){const g=laneNodes.get(s[0]);if(!g)continue;const v=target(s[0]);if(immediate)g.gain.setValueAtTime(v,ctx.currentTime);else setParam(g.gain,v)}const cutoff=16000-state.night*9000;if(immediate)filter.frequency.setValueAtTime(cutoff,ctx.currentTime);else setParam(filter.frequency,cutoff,.25);if(state.mode==='adaptive'){const scale=state.reconstruction?.all?.scale||1;setParam(masterBus.gain,MASTER_LEVEL*clamp(scale,.20,2.0)*(state.voiceFocus?.90:1),.18)}render()}
function selectDonor(id){if(selected===id)return;stop();selected=id;state.loadedDonor=null;state.reconstruction=null;buffers.clear();laneNodes.clear();const d=donor();state.activity=d.defaults.activity;state.roadLift=d.defaults.roadLift;state.night=d.defaults.night;state.voiceFocus=false;$('#play').disabled=true;$('#playMaster').disabled=true;syncUI();renderDonors();renderLanes();render()}
function setControl(n,v){state[n]=clamp(v,0,1);applyMix();return snapshot()}
function setVoice(v){state.voiceFocus=!!v;applyMix();syncUI();return snapshot()}
function preset(p){if(p==='neutral'){state.activity=0;state.roadLift=0;state.night=0;state.voiceFocus=false}else if(p==='calm'){state.activity=0;state.roadLift=0;state.night=.15;state.voiceFocus=false}else if(p==='active'){state.activity=.85;state.roadLift=.10;state.night=0;state.voiceFocus=false}else if(p==='road'){state.activity=.60;state.roadLift=.85;state.night=0;state.voiceFocus=false}else if(p==='night'){state.activity=.15;state.roadLift=0;state.night=.80;state.voiceFocus=false}else if(p==='voice'){state.voiceFocus=true}syncUI();applyMix();return snapshot()}
function reset(){return preset('neutral')}
function renderDonors(){const r=$('#donors');r.innerHTML='';for(const d of spec.donors){const b=document.createElement('button');b.className='donor'+(d.id===selected?' active':'');b.innerHTML='<b>'+d.title+'</b><span>'+d.mood+' · '+d.bpm+' BPM</span>';b.onclick=()=>selectDonor(d.id);r.appendChild(b)}}
function renderLanes(){const r=$('#lanes');r.innerHTML='';const d=donor();for(const s of d?.stems||[]){const residual=stemType(s)==='residual';const el=document.createElement('div');el.className='lane'+(residual?' residual':'');el.dataset.lane=s[0];el.innerHTML='<span>'+s[0].toUpperCase()+(residual?' · RESIDUAL':'')+'</span><b>'+s[1]+'</b><div class="meter"><i></i></div><div class="meta">—</div>';r.appendChild(el)}}
function syncUI(){for(const id of ['activity','roadLift','night']){const el=$('#'+id);el.value=state[id];el.nextElementSibling.textContent=Math.round(state[id]*100)+'%'}$('#voiceFocus').setAttribute('aria-pressed',String(state.voiceFocus));$('#voiceFocus').textContent=state.voiceFocus?'ON':'OFF'}
function render(){const d=donor();if(d){$('#donorName').textContent=d.title;$('#mood').textContent=d.mood;$('#bpm').textContent=d.bpm}$('#mode').textContent=state.mode.toUpperCase();const t=targets();for(const s of d?.stems||[]){const el=document.querySelector('[data-lane="'+s[0]+'"]');if(el){el.querySelector('.meter i').style.width=Math.min(100,Math.round((t[s[0]]||0)*100))+'%';el.querySelector('.meta').textContent=(t[s[0]]||0).toFixed(2)}}$('#diag').textContent=JSON.stringify(snapshot(),null,2)}
function snapshot(){return{build:spec?.build||null,selected,loadedDonor:state.loadedDonor,playing:state.playing,mode:state.mode,contextCount:state.contextCount,contextState:ctx?.state||'none',controls:{activity:state.activity,roadLift:state.roadLift,night:state.night,voiceFocus:state.voiceFocus},targets:spec?targets():{},starts:[...state.starts],synchronizedStarts:state.starts.length<2||Math.max(...state.starts)-Math.min(...state.starts)<1e-7,stemCount:donor()?.stems?.length||0,residualCount:donor()?.stems?.filter(s=>stemType(s)==='residual').length||0,masterLoaded:buffers.has('master'),reconstruction:state.reconstruction,donors:spec?.donors?.map(d=>({id:d.id,mood:d.mood,bpm:d.bpm,stemCount:d.stems.length,residualCount:d.stems.filter(s=>stemType(s)==='residual').length}))||[],errors:[...state.errors]}}
function bind(){$('#load').onclick=()=>loadSelected().catch(e=>{state.errors.push(e.message);render()});$('#playMaster').onclick=()=>{try{playMaster()}catch(e){state.errors.push(e.message);render()}};$('#play').onclick=()=>{try{play()}catch(e){state.errors.push(e.message);render()}};$('#stop').onclick=stop;$('#reset').onclick=reset;for(const id of ['activity','roadLift','night'])$('#'+id).oninput=e=>{setControl(id,e.target.value);e.target.nextElementSibling.textContent=Math.round(e.target.value*100)+'%'};$('#voiceFocus').onclick=()=>setVoice(!state.voiceFocus);$$('[data-preset]').forEach(b=>b.onclick=()=>preset(b.dataset.preset))}
window.__KFB_MOOD_POOL__={loadSelected,playMaster,play,stop,selectDonor,setControl,setVoice,preset,reset,snapshot};
fetch('./SOURCE.json',{cache:'no-store'}).then(r=>r.json()).then(s=>{spec=s;selected=spec.donors[0].id;renderDonors();renderLanes();bind();syncUI();render()}).catch(e=>{state.errors.push(e.message);render()});