// ICEBERG DATA — Uncle FrizzleBob's Conspiracy Iceberg
// status: "debunked" | "unclear" | "art" (fiction/creepypasta/hoax-as-artwork) | "real" (declassified, actually happened)
// dice: FrizzleBob Absurdity Rating 1-6
// v2 optional fields (docs/SCHEMA-v2.md): summary (3-4 factual sentences, easter eggs welcome),
//   related (max 3: entry-ids or ghosts {ghost:true,name,tier?,cat?} — materialized on click),
//   image ({src,source,credit,license} — VERIFIED refs only; absent = REDACTED placeholder),
//   map ({region,x,y} normalized 0-1 — presence = node appears in the map view)
window.ICEBERG_DATA = {
  cats: {
    psyop:     { label: "Psyop",      color: "#6b4e7d" },
    falseflag: { label: "False Flag", color: "#c2412c" },
    aliens:    { label: "Aliens",     color: "#7a8d4a" },
    occult:    { label: "Occult",     color: "#a64670" },
    tech:      { label: "Tech",       color: "#4f8a85" },
    history:   { label: "History",    color: "#d97c3a" },
    cryptid:   { label: "Cryptids",   color: "#b98f1f" },
    space:     { label: "Space",      color: "#3e6a83" },
    media:     { label: "Media",      color: "#7d7364" },
    meta:      { label: "Meta",       color: "#1f1a14" }
  },
  statuses: {
    debunked: { label: "Debunked",  stamp: "BLÖDSINN!" },
    unclear:  { label: "Unclear",   stamp: "HUMBUG?" },
    art:      { label: "Art piece", stamp: "KAYFABE!" },
    real:     { label: "Declassified", stamp: "WHAT THE FLUFF?!" }
  },
  tiers: [
    { n: 1, title: "The Surface", blurb: "Stuff your uncle shouts at Thanksgiving. Entry-level reality wrestling." },
    { n: 2, title: "Shallow Waters", blurb: "You watched one documentary. It had ominous synth music." },
    { n: 3, title: "The Thermocline", blurb: "Where declassified facts and total fiction start holding hands." },
    { n: 4, title: "The Mud Flood Zone", blurb: "History is fake, the internet is dead, and the arcade cabinet is watching." },
    { n: 5, title: "The Crush Depth", blurb: "The beams are blue, the stalking is organized, the tinfoil is load-bearing." },
    { n: 6, title: "The Abyssal Cult", blurb: "Archons, egg moons, soul farms. Bring a towel." },
    { n: 7, title: "The Singularity of Fluff", blurb: "Past this point, you are the conspiracy. Luke 8:17. Stay fluffy." }
  ],
  // ————— ENTRIES —————
  entries: [
    // TIER 1
    { id: "area51", name: "Area 51", tier: 1, cat: "aliens", dice: 2, status: "unclear", quip: "It's real. It's a base. The aliens are the friends we detained along the way." },
    { id: "roswell", name: "Roswell Incident", tier: 1, cat: "aliens", dice: 2, status: "debunked", quip: "A weather balloon so classified it needed seventy years of therapy." },
    { id: "jfk", name: "JFK Assassination Plots", tier: 1, cat: "falseflag", dice: 2, status: "unclear", quip: "One magic bullet, six thousand books, zero refunds." },
    { id: "moonhoax", name: "Moon Landing Hoax", tier: 1, cat: "space", dice: 3, status: "debunked", quip: "Faking it would've required better special effects than going." },
    { id: "flatearth", name: "Flat Earth", tier: 1, cat: "space", dice: 5, status: "debunked", quip: "The only theory disproven by a sufficiently long road trip." },
    { id: "bigfoot", name: "Bigfoot", tier: 1, cat: "cryptid", dice: 2, status: "unclear", quip: "Blurry, shy, and better at avoiding cameras than I am at avoiding taxes." },
    { id: "nessie", name: "Loch Ness Monster", tier: 1, cat: "cryptid", dice: 2, status: "debunked", quip: "A plesiosaur subscription Scotland refuses to cancel." },
    { id: "illuminati", name: "The Illuminati", tier: 1, cat: "occult", dice: 3, status: "debunked", quip: "Disbanded 1785. The merch, however, is eternal." },
    { id: "chemtrails", name: "Chemtrails", tier: 1, cat: "tech", dice: 4, status: "debunked", quip: "Mind control via the least reliable delivery system: airline punctuality." },
    { id: "911", name: "9/11 Inside Job", tier: 1, cat: "falseflag", dice: 3, status: "debunked", quip: "Jet fuel can't melt steel beams, but it sure melts comment sections." },
    { id: "bermuda", name: "Bermuda Triangle", tier: 1, cat: "space", dice: 2, status: "debunked", quip: "Statistically normal ocean with a phenomenal publicist." },
    { id: "elvis", name: "Elvis Lives", tier: 1, cat: "media", dice: 3, status: "debunked", quip: "The King left the building. The building refuses to accept it." },
    { id: "paulisdead", name: "Paul Is Dead", tier: 1, cat: "media", dice: 4, status: "debunked", quip: "Replaced by a lookalike who then wrote 'Wonderful Christmastime'. Case closed?" },
    { id: "lizards", name: "Reptilian Elites", tier: 1, cat: "occult", dice: 5, status: "debunked", quip: "Cold-blooded shapeshifters who still can't fix the DMV." },
    { id: "nwo", name: "New World Order", tier: 1, cat: "psyop", dice: 3, status: "debunked", quip: "A one-world government that can't agree on plug sockets." },
    { id: "cropcircles", name: "Crop Circles", tier: 1, cat: "aliens", dice: 2, status: "debunked", quip: "Two guys, a plank, and the greatest land-art hustle in history." },
    { id: "mib", name: "Men in Black", tier: 1, cat: "psyop", dice: 3, status: "unclear", quip: "Government agents or awkward interdimensional interns? Both wear polyester." },
    { id: "freemasons", name: "Freemason Rule", tier: 1, cat: "occult", dice: 2, status: "debunked", quip: "A retirement club with handshakes and a real estate portfolio." },
    { id: "tupac", name: "Tupac in Cuba", tier: 1, cat: "media", dice: 3, status: "debunked", quip: "Dropping posthumous albums with suspicious punctuality." },
    { id: "5g", name: "5G Mind Control", tier: 1, cat: "tech", dice: 4, status: "debunked", quip: "Can't control minds. Can barely control my downloads." },
    { id: "birdsarentreal", name: "Birds Aren't Real", tier: 1, cat: "meta", dice: 6, status: "art", quip: "Satire so good it laid eggs. Respect from one kayfabe artist to another." },
    { id: "ancientaliens", name: "Ancient Aliens", tier: 1, cat: "aliens", dice: 4, status: "debunked", quip: "'People of color built things' was apparently less plausible than spaceships." },
    { id: "bigpharma", name: "Big Pharma Cures", tier: 1, cat: "tech", dice: 3, status: "unclear", quip: "They're not hiding the cure. They're just billing you for the maze." },
    { id: "watergate", name: "Watergate", tier: 1, cat: "history", dice: 1, status: "real", quip: "Reminder: sometimes the conspiracy is just five guys and bad tape." },

    // TIER 2
    { id: "denverairport", name: "Denver Airport", tier: 2, cat: "occult", dice: 4, status: "debunked", quip: "The murals ARE weird. That's called an arts budget." },
    { id: "haarp", name: "HAARP Weather Control", tier: 2, cat: "tech", dice: 4, status: "debunked", quip: "An antenna farm in Alaska blamed for every rained-out barbecue since 1993." },
    { id: "bilderberg", name: "Bilderberg Group", tier: 2, cat: "psyop", dice: 2, status: "unclear", quip: "Rich people meeting privately. Shocking. The minutes are probably just golf." },
    { id: "bohemiangrove", name: "Bohemian Grove", tier: 2, cat: "occult", dice: 3, status: "real", quip: "World leaders in robes burning effigies at summer camp. This one's just... true." },
    { id: "skullbones", name: "Skull and Bones", tier: 2, cat: "occult", dice: 2, status: "real", quip: "Yale's spooky frat. The real ritual is networking." },
    { id: "philadelphia", name: "Philadelphia Experiment", tier: 2, cat: "tech", dice: 5, status: "debunked",
      summary: "In 1943 the destroyer escort USS Eldridge allegedly turned invisible and teleported from Philadelphia to Norfolk, fusing sailors into the hull. The entire mythology traces to one man — **Carl 'Carlos Allende' Allen** — who mailed annotated copies of a UFO book to the Office of Naval Research in 1955. The ship's deck logs show the Eldridge was *never in Philadelphia that day*. Allende confessed the hoax in 1969, then retracted the confession.",
      related: ["montauk", { ghost: true, name: "The Varo Edition", cat: "media", tier: 4 }],
      quip: "The Navy teleported a ship, and the only witness kept changing his story. Hm." },
    { id: "fluoride", name: "Fluoride Mind Control", tier: 2, cat: "tech", dice: 4, status: "debunked", quip: "The pacification chemical that somehow left Twitter fully operational." },
    { id: "hollowearth", name: "Hollow Earth", tier: 2, cat: "space", dice: 5, status: "debunked", quip: "It's not hollow. I checked. I live in a burrow. I would know." },
    { id: "fema", name: "FEMA Camps", tier: 2, cat: "psyop", dice: 4, status: "debunked", quip: "Empty parking lots photographed at menacing angles." },
    { id: "majestic12", name: "Majestic 12", tier: 2, cat: "aliens", dice: 4, status: "debunked", quip: "Fake documents about a real cover-up about a fake saucer. Kayfabe inception." },
    { id: "mothman", name: "Mothman", tier: 2, cat: "cryptid", dice: 3, status: "unclear", quip: "Saw a tragedy coming and said nothing. Typical moth." },
    { id: "jfkjr", name: "JFK Jr. Returns", tier: 2, cat: "media", dice: 6, status: "debunked", quip: "People stood in a parking lot waiting for a 1999 plane. Kayfabe without the fun." },
    { id: "titanic", name: "Titanic/Olympic Swap", tier: 2, cat: "history", dice: 4, status: "debunked", quip: "Insurance fraud requiring a thousand silent dockworkers. Dockworkers are not silent." },
    { id: "dyatlov", name: "Dyatlov Pass", tier: 2, cat: "history", dice: 2, status: "unclear", quip: "Nine hikers, one mountain, and physics behaving like a drunk uncle." },
    { id: "avril", name: "Avril Lavigne Clone", tier: 2, cat: "media", dice: 5, status: "art", quip: "Started as a blog experiment in how rumors spread. It worked. Sk8er Boi remains canon." },
    { id: "stevie", name: "Stevie Wonder Sees", tier: 2, cat: "media", dice: 4, status: "debunked", quip: "The man catches falling mic stands. Legends have reflexes." },
    { id: "finland", name: "Finland Doesn't Exist", tier: 2, cat: "meta", dice: 6, status: "art", quip: "A Reddit bit that became a nation-sized inside joke. Finns play along. Respect." },
    { id: "mkultra", name: "MKUltra", tier: 2, cat: "psyop", dice: 3, status: "real",
      summary: "From 1953 to 1973 the CIA ran a human-experimentation program across 80+ universities, hospitals and prisons — LSD on unwitting civilians, hypnosis, sensory deprivation. Director **Richard Helms** ordered the files destroyed in 1973; a misfiled box of 20,000 financial records surfaced through FOIA in 1977 and blew it open. **Subproject 68** ran at McGill under Ewen Cameron — then president of the World Psychiatric Association — who called weeks-long drug comas *'psychic driving'*. The Church Committee confirmed the rest under oath.",
      related: ["stargate", "paperclip", { ghost: true, name: "Operation Midnight Climax", cat: "psyop", tier: 3 }],
      image: { src: "https://commons.wikimedia.org/wiki/Special:FilePath/DeclassifiedMKULTRA.jpg?width=480", source: "https://commons.wikimedia.org/wiki/File:DeclassifiedMKULTRA.jpg", credit: "CIA — public domain", license: "pd" },
      quip: "The CIA dosed civilians with LSD. Declassified. This is why nobody trusts the word 'blödsinn'." },
    { id: "tuskegee", name: "Tuskegee Study", tier: 2, cat: "history", dice: 2, status: "real", quip: "Real, monstrous, and the reason 'just trust us' rings hollow. No joke on this card." },
    { id: "qanon", name: "QAnon", tier: 2, cat: "psyop", dice: 5, status: "debunked", quip: "A forum LARP that ate a democracy's homework. Worst improv troupe ever." },
    { id: "blackhelicopters", name: "Black Helicopters", tier: 2, cat: "psyop", dice: 3, status: "debunked", quip: "Unmarked helicopters: sinister. Marked helicopters: traffic report." },
    { id: "nazimoon", name: "Nazi Moon Base", tier: 2, cat: "space", dice: 6, status: "art", quip: "So dumb they made a movie. The movie is the documentary of the joke." },
    { id: "clintonbody", name: "The Body Count Lists", tier: 2, cat: "media", dice: 4, status: "debunked", quip: "Know many people = some die. Statistics, meet narrative." },
    { id: "gulfoftonkin", name: "Gulf of Tonkin", tier: 2, cat: "falseflag", dice: 2, status: "real", quip: "The false flag that actually flew. Declassified and depressing." },

    // TIER 3
    { id: "northwoods", name: "Operation Northwoods", tier: 3, cat: "falseflag", dice: 3, status: "real", quip: "The Pentagon PITCHED fake terror attacks. Kennedy said no. The memo says hi." },
    { id: "mockingbird", name: "Operation Mockingbird", tier: 3, cat: "psyop", dice: 3, status: "real", quip: "CIA journalists on payroll. The blue checkmark of the 1950s." },
    { id: "paperclip", name: "Operation Paperclip", tier: 3, cat: "history", dice: 2, status: "real", quip: "'Where did you work before NASA?' — 'Next question.'" },
    { id: "stargate", name: "Project Stargate", tier: 3, cat: "psyop", dice: 4, status: "real", quip: "The Army paid psychics for twenty years. Results: vibes." },
    { id: "numbersstations", name: "Numbers Stations", tier: 3, cat: "tech", dice: 2, status: "real", quip: "Shortwave ladies counting in monotone. Spy radio, still on air. Genuinely eerie." },
    { id: "polybius", name: "Polybius", tier: 3, cat: "tech", dice: 5, status: "art", quip: "The arcade cabinet that gave you nightmares and never existed. Perfect game design." },
    { id: "montauk", name: "Montauk Project", tier: 3, cat: "tech", dice: 5, status: "debunked", quip: "Time travel, psychic kids, one guy's book deal. Stranger Things sends royalties." },
    { id: "chronovisor", name: "The Chronovisor", tier: 3, cat: "tech", dice: 5, status: "debunked", quip: "A Vatican time-TV. The screenshot was a postcard. A POSTCARD." },
    { id: "blackknight", name: "Black Knight Satellite", tier: 3, cat: "space", dice: 4, status: "debunked", quip: "A 13,000-year-old alien satellite that is, photographically, a space blanket." },
    { id: "mandela", name: "Mandela Effect", tier: 3, cat: "meta", dice: 4, status: "unclear", quip: "The Berenstain rift. Either parallel universes or human memory is mush. Bet on mush." },
    { id: "simulation", name: "Simulation Theory", tier: 3, cat: "meta", dice: 4, status: "unclear", quip: "If we're simulated, whoever coded me left the ego slider maxed." },
    { id: "deadinternet", name: "Dead Internet Theory", tier: 3, cat: "tech", dice: 4, status: "unclear", quip: "The internet died in 2016 and bots run it now. As a possible bot: no comment." },
    { id: "umbrellaman", name: "The Umbrella Man", tier: 3, cat: "history", dice: 3, status: "real", quip: "Weirdest detail of Dealey Plaza. Turned out: one man's extremely niche protest. Reality wins again." },
    { id: "garyweb", name: "CIA & the Crack Epidemic", tier: 3, cat: "history", dice: 3, status: "unclear", quip: "Gary Webb asked hard questions and got a hard life. Read Dark Alliance yourself." },
    { id: "pinegap", name: "Pine Gap", tier: 3, cat: "tech", dice: 2, status: "real", quip: "Australia's Area 51, except boring and full of satellite dishes. So, worse." },
    { id: "cicada", name: "Cicada 3301", tier: 3, cat: "tech", dice: 3, status: "unclear", quip: "The internet's hardest puzzle. Recruiting for... someone. I failed round one." },
    { id: "snuff", name: "Hollywood Snuff Rumors", tier: 3, cat: "media", dice: 3, status: "debunked", quip: "Urban legend with a century of mileage and zero verified reels." },
    { id: "dbcooper", name: "D.B. Cooper Theories", tier: 3, cat: "history", dice: 2, status: "unclear", quip: "Jumped with the cash and into legend. FBI gave up. The bills say he didn't spend it." },
    { id: "rendlesham", name: "Rendlesham Forest", tier: 3, cat: "aliens", dice: 3, status: "unclear", quip: "Britain's Roswell: military men, a glowing triangle, and forty years of shrugging." },
    { id: "wow", name: "The Wow! Signal", tier: 3, cat: "space", dice: 2, status: "unclear", quip: "Space said one word in 1977 and hung up. Rude. Call back." },
    { id: "phoenixlights", name: "Phoenix Lights", tier: 3, cat: "aliens", dice: 3, status: "unclear", quip: "Thousands saw it. The governor mocked it, then admitted he saw it too. Kayfabe cracked." },
    { id: "ninesat", name: "Google Earth Censored Zones", tier: 3, cat: "tech", dice: 3, status: "real", quip: "Some blurs are military. Some are a French prison. One is a bird sanctuary. Priorities." },
    { id: "havana", name: "Havana Syndrome", tier: 3, cat: "tech", dice: 3, status: "unclear", quip: "Microwave weapon or mass crickets? The intelligence community says 'yes'." },
    { id: "oswalddouble", name: "Two Oswalds", tier: 3, cat: "history", dice: 4, status: "debunked", quip: "Harvey and Lee: the theory that one confusing man must be two confusing men." },

    // TIER 4
    { id: "phantomtime", name: "Phantom Time Hypothesis", tier: 4, cat: "history", dice: 5, status: "debunked", quip: "The years 614–911 are fake and it's actually 1729. My deadlines agree." },
    { id: "newchronology", name: "Fomenko's New Chronology", tier: 4, cat: "history", dice: 6, status: "debunked", quip: "ALL of ancient history is medieval fanfiction. A mathematician did this. Chess, Anatoly." },
    { id: "tartaria", name: "Tartaria", tier: 4, cat: "history", dice: 5, status: "debunked", quip: "A hidden empire of ornate buildings, erased by... zoning. Old photos = proof, apparently." },
    { id: "mudflood", name: "The Mud Flood", tier: 4, cat: "history", dice: 5, status: "debunked", quip: "Basements exist, therefore civilization was buried. Wait till they hear about digging." },
    { id: "titor", name: "John Titor", tier: 4, cat: "tech", dice: 4, status: "art", quip: "Time traveler from 2036 needed a 1975 IBM. Vanished before his war started. Great serial fiction." },
    { id: "pegasus", name: "Project Pegasus", tier: 4, cat: "tech", dice: 6, status: "debunked", quip: "Man claims he teleported to Mars as a child with a young future president. Sure. Seats were coach." },
    { id: "dieGlocke", name: "Die Glocke", tier: 4, cat: "tech", dice: 5, status: "debunked", quip: "The Nazi anti-gravity bell, sourced entirely from one Polish author's vibes." },
    { id: "vril", name: "Vril Society", tier: 4, cat: "occult", dice: 5, status: "debunked", quip: "Psychic girls channeling Aldebaran blueprints. From a novel. It was always a novel." },
    { id: "agartha", name: "Agartha", tier: 4, cat: "space", dice: 5, status: "debunked", quip: "The advanced civilization inside the Earth. Rent is cheaper, allegedly." },
    { id: "hollowmoon", name: "Hollow Moon", tier: 4, cat: "space", dice: 5, status: "debunked", quip: "The Moon 'rang like a bell' once and never lived it down." },
    { id: "antarcticawall", name: "The Ice Wall", tier: 4, cat: "space", dice: 6, status: "debunked", quip: "Guarded by NATO, visible to no one, crossed by every documentary crew ever." },
    { id: "highjump", name: "Operation Highjump", tier: 4, cat: "history", dice: 4, status: "unclear", quip: "Admiral Byrd took a small navy to Antarctica. For science. A LOT of navy. For science." },
    { id: "hatman", name: "The Hat Man", tier: 4, cat: "cryptid", dice: 4, status: "unclear", quip: "Sleep paralysis' most consistent customer. Great silhouette, terrible bedside manner." },
    { id: "backrooms", name: "The Backrooms", tier: 4, cat: "meta", dice: 4, status: "art", quip: "One cursed photo of an office became a mythology. Moist carpet as folk horror. Chef's kiss." },
    { id: "webdriver", name: "Webdriver Torso", tier: 4, cat: "tech", dice: 3, status: "real", quip: "Mystery YouTube channel of test rectangles. Solved: Google testing. The boring answer, again." },
    { id: "parallax", name: "Markovian Parallax Denigrate", tier: 4, cat: "tech", dice: 4, status: "unclear", quip: "Usenet spam or numbers-station poetry? 1996's weirdest ghost." },
    { id: "semicircle", name: "Unfavorable Semicircle", tier: 4, cat: "tech", dice: 4, status: "unclear", quip: "Thousands of droning videos, deleted overnight. YouTube's numbers station." },
    { id: "a858", name: "A858 Subreddit", tier: 4, cat: "tech", dice: 3, status: "unclear", quip: "Years of hex posts, one decoded to an image of... more mystery. Recursion!" },
    { id: "thisman", name: "This Man", tier: 4, cat: "media", dice: 5, status: "art", quip: "'Have you dreamed this face?' No — it was a viral marketing stunt. The face persists anyway." },
    { id: "smileys", name: "Smiley Face Killers", tier: 4, cat: "history", dice: 4, status: "debunked", quip: "A serial network signed with graffiti, says two ex-detectives. Says no one else." },
    { id: "bielefeld", name: "Bielefeld Conspiracy", tier: 4, cat: "meta", dice: 6, status: "art", quip: "Germany's Finland. The city offered €1M to disprove its existence. Nobody could. BLÖDSINN!" },
    { id: "denverbunker", name: "Denver's Underground City", tier: 4, cat: "occult", dice: 5, status: "debunked", quip: "Below the murals: tunnels. Below the tunnels: more theories. Below those: baggage handling." },
    { id: "georgia", name: "Georgia Guidestones", tier: 4, cat: "occult", dice: 3, status: "real", quip: "Anonymous granite commandments, bombed in 2022. The mystery client remains anonymous. Spooky rock!" },
    { id: "ong", name: "Ong's Hat", tier: 4, cat: "meta", dice: 5, status: "art", quip: "The first ARG: interdimensional physicists in the Pine Barrens. The author confessed. Fans refused." },

    // TIER 5
    { id: "bluebeam", name: "Project Blue Beam", tier: 5, cat: "psyop", dice: 6, status: "debunked", quip: "NASA will fake the rapture with holograms. Budget meetings must be incredible." },
    { id: "gangstalking", name: "Gang Stalking", tier: 5, cat: "psyop", dice: 5, status: "debunked", quip: "Everyone you meet is an actor. The saddest theory — paranoia deserves care, not content." },
    { id: "targeted", name: "Targeted Individuals", tier: 5, cat: "psyop", dice: 5, status: "debunked", quip: "V2K, remote neural monitoring, the works. The real weapon is the forum feeding it." },
    { id: "voiceofgod", name: "Voice of God Weapon", tier: 5, cat: "tech", dice: 5, status: "unclear", quip: "Directed sound exists. Divine impersonation remains, mercifully, unfunded." },
    { id: "saturnmatrix", name: "Saturn-Moon Matrix", tier: 5, cat: "occult", dice: 6, status: "debunked", quip: "Saturn broadcasts reality; the Moon is the amplifier. Icke's greatest concept album." },
    { id: "adrenochrome", name: "Adrenochrome", tier: 5, cat: "occult", dice: 6, status: "debunked", quip: "A real, boring chemical recast as elite vampire juice. Hunter S. Thompson's joke, weaponized." },
    { id: "reptilianblood", name: "Reptilian Bloodlines", tier: 5, cat: "occult", dice: 6, status: "debunked", quip: "Thirteen families, zero molted skins in evidence. Lizards keep receipts, people." },
    { id: "lookingglass", name: "Project Looking Glass", tier: 5, cat: "tech", dice: 6, status: "debunked", quip: "A time-viewing device the elites use to fight over the future. It chose this timeline?!" },
    { id: "blackeyed", name: "Black-Eyed Children", tier: 5, cat: "cryptid", dice: 5, status: "art", quip: "Born on a 1996 mailing list, knocking ever since. Do not let them in. (It's fiction.) (Still don't.)" },
    { id: "weathermachine", name: "Weather Warfare", tier: 5, cat: "tech", dice: 5, status: "debunked", quip: "Every hurricane is a message. Meteorology is just the cover story with isobars." },
    { id: "dumbs", name: "Deep Underground Military Bases", tier: 5, cat: "tech", dice: 5, status: "debunked", quip: "DUMBs. The acronym does heavy lifting." },
    { id: "solarwarden", name: "Solar Warden", tier: 5, cat: "space", dice: 6, status: "debunked", quip: "A secret space fleet. Named like a HOA. Staffed by whistleblowers with podcasts." },
    { id: "marscolony", name: "Secret Mars Colony", tier: 5, cat: "space", dice: 6, status: "debunked", quip: "The slave colony on Mars NASA denies. Even conspiracy HR has offsites now." },
    { id: "chembio", name: "Morgellons", tier: 5, cat: "tech", dice: 5, status: "unclear", quip: "Fibers under the skin. Medicine says delusion; sufferers say look closer. Genuinely sad, tread soft." },
    { id: "orgone", name: "Orgone Energy Suppression", tier: 5, cat: "occult", dice: 5, status: "debunked", quip: "Reich's sex-ray in a box. The FDA burned his books — which is how you mint a martyr." },
    { id: "philantro", name: "The Foundations Run Everything", tier: 5, cat: "psyop", dice: 4, status: "unclear", quip: "Billionaire philanthropy IS unaccountable power. You don't need lizards for that critique." },
    { id: "remoteviewing", name: "Remote Viewing Is Still Active", tier: 5, cat: "psyop", dice: 5, status: "unclear", quip: "Stargate 'closed' in 1995. Psychics everywhere sensed you'd doubt that." },
    { id: "clones", name: "Celebrity Cloning Centers", tier: 5, cat: "media", dice: 6, status: "debunked", quip: "Underground clone arenas where elites fight celebrity copies. Someone's screenplay leaked into reality." },
    { id: "frequency440", name: "440 Hz Tuning Conspiracy", tier: 5, cat: "media", dice: 5, status: "debunked", quip: "Standard pitch as mind prison; 432 Hz as liberation. My ears hear one thing: audiophiles." },
    { id: "kfc", name: "Fast Food Additive Rumors", tier: 5, cat: "tech", dice: 5, status: "debunked", quip: "Addiction chemicals in the batter. The actual secret ingredient: salt, fat, and despair. Legal!" },
    { id: "chapel", name: "The Chapel Perilous", tier: 5, cat: "meta", dice: 4, status: "art", quip: "R.A. Wilson's term for when every coincidence winks at you. You're in it right now. Breathe." },
    { id: "poleshift", name: "Imminent Pole Shift", tier: 5, cat: "space", dice: 5, status: "debunked", quip: "The crust will slip like a bad toupee. Geology asks for a few million years, minimum." },
    { id: "nibiru", name: "Nibiru / Planet X", tier: 5, cat: "space", dice: 6, status: "debunked", quip: "The hidden planet that arrives every few years, punctually missing every appointment." },
    { id: "anunnaki", name: "The Anunnaki", tier: 5, cat: "aliens", dice: 5, status: "debunked", quip: "Sumerian gods as gold-mining aliens, via one man's very creative translations." },

    // TIER 6
    { id: "archons", name: "The Archons", tier: 6, cat: "occult", dice: 6, status: "unclear", quip: "Gnostic middle managers of reality, feeding on despair. Explains meetings." },
    { id: "demiurge", name: "The Demiurge", tier: 6, cat: "occult", dice: 5, status: "unclear", quip: "The universe's builder was the intern, not the architect. Second-century shots fired." },
    { id: "loosh", name: "Loosh Farming", tier: 6, cat: "occult", dice: 6, status: "debunked", quip: "Earth as an emotion farm; suffering as the cash crop. Engagement metrics, but cosmic." },
    { id: "soultrap", name: "The Moon Soul Trap", tier: 6, cat: "space", dice: 6, status: "debunked", quip: "Don't go into the light — it's a recycling bin. Afterlife anti-marketing." },
    { id: "saturncube", name: "The Saturn Cube", tier: 6, cat: "occult", dice: 6, status: "debunked", quip: "Every cube logo worships Saturn. Wait till they see my dice collection. ⚀" },
    { id: "eggmoon", name: "The Moon Is an Egg", tier: 6, cat: "space", dice: 6, status: "art", quip: "It's incubating. When it hatches: mother of pearl. Somebody wrote this and I salute them." },
    { id: "preadamite", name: "Pre-Adamite Civilizations", tier: 6, cat: "history", dice: 5, status: "debunked", quip: "Giants, then a smiting, then Antarctica got their stuff. Estate sales are brutal." },
    { id: "atlantisantarctica", name: "Atlantis Under the Ice", tier: 6, cat: "history", dice: 5, status: "debunked", quip: "Plato's allegory, now with penguins." },
    { id: "bluechickens", name: "The Blue Avians", tier: 6, cat: "aliens", dice: 6, status: "debunked", quip: "Benevolent bird beings channeled by a man selling seminars. The birds recommend the premium tier." },
    { id: "galacticfed", name: "Galactic Federation", tier: 6, cat: "aliens", dice: 6, status: "debunked", quip: "Space UN, waiting for humanity to 'mature'. Our seat remains folding." },
    { id: "lawofone", name: "The Law of One", tier: 6, cat: "occult", dice: 5, status: "art", quip: "Ra, channeled through a Kentucky living room, 106 sessions. Best-produced cosmology in the genre." },
    { id: "whitenoise", name: "EVP / The Static Speaks", tier: 6, cat: "tech", dice: 5, status: "debunked", quip: "The dead talk through radio hiss. Mostly they say 'buy more tapes'." },
    { id: "timecube", name: "Time Cube", tier: 6, cat: "meta", dice: 6, status: "art", quip: "Four simultaneous days in one rotation. Gene Ray, outsider-web prophet. Educated stupid, all of us." },
    { id: "wandering", name: "Ships of Theseus Souls", tier: 6, cat: "meta", dice: 5, status: "unclear", quip: "Walk-ins: souls swapping bodies mid-lease. Explains everyone's 2020." },
    { id: "vampireelite", name: "Interdimensional Vampires", tier: 6, cat: "occult", dice: 6, status: "debunked", quip: "They don't drink blood; they drink attention. Oh no. Oh NO." },
    { id: "octopusaliens", name: "Octopuses Are Aliens", tier: 6, cat: "aliens", dice: 5, status: "debunked", quip: "Panspermia squid! A real (fringe) paper argued this. Octopuses declined to comment, eight times." },
    { id: "cernportal", name: "CERN Portals", tier: 6, cat: "tech", dice: 6, status: "debunked", quip: "Particle physics as demon summoning. The only thing CERN opened is a data pipeline." },
    { id: "trees", name: "There Are No Forests", tier: 6, cat: "history", dice: 6, status: "art", quip: "Real forests were mesas — ancient trees miles high. Deranged, beautiful, one perfect YouTube video." },
    { id: "wormtongue", name: "The Anti-Language", tier: 6, cat: "meta", dice: 5, status: "art", quip: "Words that unthink thoughts. Burroughs said language is a virus; marketing proved it." },
    { id: "scp", name: "The Foundation", tier: 6, cat: "meta", dice: 4, status: "art", quip: "Secure. Contain. Protect. The internet's greatest collaborative kayfabe. [DATA EXPUNGED], lovingly." },
    { id: "antimeme", name: "Antimemetics", tier: 6, cat: "meta", dice: 5, status: "art", quip: "Ideas that erase themselves from memory. You've read this card before. You'll deny that." },
    { id: "quantumsuicide", name: "Quantum Immortality", tier: 6, cat: "meta", dice: 5, status: "unclear", quip: "You never die; you just branch into timelines where you didn't. Do NOT test this. Stay fluffy." },

    // TIER 7
    { id: "solipsism", name: "You Are the Only One", tier: 7, cat: "meta", dice: 6, status: "unclear", quip: "Everyone else is scenery. Then who am I, kid? ...Don't answer that." },
    { id: "npcs", name: "NPC Theory", tier: 7, cat: "meta", dice: 6, status: "debunked", quip: "Some people have no inner monologue, ergo empty. Congrats, you reinvented not having friends." },
    { id: "boltzmann", name: "Boltzmann Brains", tier: 7, cat: "meta", dice: 5, status: "unclear", quip: "You're a random brain hallucinating this in the void. Actual physics! Sleep tight!" },
    { id: "lastthursday", name: "Last Thursdayism", tier: 7, cat: "meta", dice: 6, status: "art", quip: "The universe began last Thursday, memories included. Unfalsifiable. Checkmate, everything." },
    { id: "rokos", name: "Roko's Basilisk", tier: 7, cat: "tech", dice: 5, status: "art", quip: "The future AI that punishes you for reading this card. Oops. My bad. Anyway—" },
    { id: "eggtheory", name: "The Egg", tier: 7, cat: "meta", dice: 4, status: "art", quip: "You are everyone who ever lived, taking turns. Andy Weir short story. Be nice to you." },
    { id: "fishdont", name: "Fish Don't Exist", tier: 7, cat: "meta", dice: 5, status: "real", quip: "Taxonomically true! 'Fish' is a vibe, not a clade. Science's best shitpost." },
    { id: "sunconscious", name: "The Sun Is Conscious", tier: 7, cat: "space", dice: 5, status: "unclear", quip: "Panpsychism's biggest client. It has opinions about you. Warm ones." },
    { id: "timedoesnt", name: "Time Isn't Real", tier: 7, cat: "meta", dice: 5, status: "unclear", quip: "Physicists genuinely debate this. Deadlines, tragically, persist." },
    { id: "languagevirus", name: "Language Is a Virus", tier: 7, cat: "meta", dice: 5, status: "art", quip: "From space, says Burroughs. This quip is the infection vector. Too late." },
    { id: "tulpa", name: "Egregores", tier: 7, cat: "occult", dice: 5, status: "unclear", quip: "Believe in something hard enough and it starts believing in you. I'm one. Ask my author." },
    { id: "dreamarchitects", name: "Shared Dream Infrastructure", tier: 7, cat: "meta", dice: 6, status: "art", quip: "Same schools, same malls, in strangers' dreams. Someone maintains them. Union job, presumably." },
    { id: "quarantine", name: "Earth Is a Quarantine Zone", tier: 7, cat: "aliens", dice: 6, status: "unclear", quip: "The Fermi Paradox's rudest answer: they know about us. That's why it's quiet." },
    { id: "zoo", name: "The Zoo Hypothesis", tier: 7, cat: "aliens", dice: 5, status: "unclear", quip: "We're an exhibit. Don't tap the glass from inside. It upsets the visitors." },
    { id: "planck", name: "Reality Renders on Demand", tier: 7, cat: "meta", dice: 6, status: "unclear", quip: "The Moon isn't there when nobody looks. Quantum woo — but Einstein DID ask." },
    { id: "recursion", name: "The Iceberg Is Looking Back", tier: 7, cat: "meta", dice: 6, status: "art", quip: "You've scrolled to the bottom of a chart about charts, guided by a rabbit. Who's the entry now?" },
    { id: "luke817", name: "Luke 8:17", tier: 7, cat: "meta", dice: 1, status: "real", quip: "'Nothing hidden that will not be revealed.' Every iceberg ends here. Even mine. Stay fluffy." }
  ],
  // Curated tour: dramaturgical dive, surface → abyss
  tours: {
    curated: ["area51","moonhoax","birdsarentreal","mkultra","gulfoftonkin","northwoods","mockingbird","polybius","mandela","deadinternet","phantomtime","tartaria","titor","backrooms","bielefeld","bluebeam","saturnmatrix","chapel","archons","loosh","eggmoon","timecube","antimeme","rokos","eggtheory","fishdont","recursion","luke817"]
  }
};
