import test from 'node:test';
import assert from 'node:assert/strict';
import {createJourney} from '../tools/KFB-ToolBox/worldbuilder/procedural-test-world-01/wb2-journey.v1.mjs';
import {EncounterBeatBus,createEncounterHost} from '../tools/resident_atlas/life/encounter-bus.js';
const fixture=()=>({id:'kfb-mvp-archipelago-01',world:{source:{owner:'WB2'},player:{actorProfileId:'Mannequin_Medium',worldId:'kfb-mvp-archipelago-01',position:[-19,.6,1],heading:0,speed:0}}});
test('all four islands stay open while rewards require actual ordered encounters',()=>{const d=fixture(),j=createJourney(()=>d);assert.equal(j.choose('protopia.farmers','bingo').reason,'prerequisite');assert.equal(j.choose('town.clown','bongo').reason,'choice');assert.equal(j.choose('town.clown','bingo').ok,true);assert.equal(j.owns('ignore_dystopia:1'),true);assert.equal(j.choose('dystopia.orc','bingo').reason,'prerequisite');assert.equal(d.world.locked,undefined);assert.equal(j.choose('town.driver','bingo').ok,true);assert.equal(j.owns('item.taxi-key.01'),true);});
test('seek/end and unverified audio cannot manufacture song/dance completion',()=>{const d=fixture(),j=createJourney(()=>d);for(const values of [{playedSeconds:1,duration:118.76,ended:true,gitBlob:'a',blobOk:true},{playedSeconds:119,duration:118.76,ended:false,gitBlob:'a',blobOk:true},{playedSeconds:119,duration:118.76,ended:true,gitBlob:'a',blobOk:false}])assert.equal(j.completeSong('demon-afro-strut',values).ok,false);assert.equal(j.owns('song:demon-afro-strut'),false);assert.equal(j.completeSong('demon-afro-strut',{playedSeconds:118.6,duration:118.76,ended:true,gitBlob:'530908085f34ef8c11901e2007bb915ad06492be',blobOk:true}).ok,true);assert.equal(j.owns('dance:kfb_dance_hip_hop_a'),true);});
test('Golden receipts keep four different deck identities and exact fresh-document resume',()=>{const d=fixture(),j=createJourney(()=>d,{now:()=> '2026-10-04T00:00:00Z'});j.choose('town.clown','bingo');j.choose('town.driver','bingo');j.completeSong('demon-afro-strut',{playedSeconds:118.76,duration:118.76,ended:true,gitBlob:'530908085f34ef8c11901e2007bb915ad06492be',blobOk:true});for(const [r,c] of [['dystopia.orc','bingo'],['utopia.monstrosity','bongo'],['protopia.farmers','bingo'],['protopia.lorekeeper','boggle']])assert.equal(j.choose(r,c).ok,true);assert.equal(j.memory().quests.length,0);const refs=j.memory().receipts.filter(r=>r.kind==='card').map(r=>r.ref);assert.equal(new Set(refs).size,4);const bundle=JSON.parse(JSON.stringify(j.exportBundle())),fresh=fixture(),resume=createJourney(()=>fresh);resume.applyBundle(bundle);assert.deepEqual(resume.memory(),j.memory());assert.deepEqual(fresh.world.player.position,d.world.player.position);assert.equal(fresh.world.player.speed,0);const n=resume.memory().receipts.length;assert.equal(resume.choose('town.clown','bingo').repeated,true);assert.equal(resume.memory().receipts.length,n);});
test('native encounter host waits for a human choice without changing default unattended decline',()=>{const bus=new EncounterBeatBus(),events=[];bus.subscribe(e=>events.push(e.beat));const h=createEncounterHost({bus,waitForDecision:true,durations:{approach:.1,greet:.1,offer:.1,react:.1}});h.start({actorId:'player',targetId:'clown'});for(let i=0;i<6;i++)h.update(1);assert.equal(h.current.beat,'react');assert.equal(events.includes('decline'),false);h.choose('accept');h.update(.1);assert.equal(h.current.beat,'accept');const unattended=createEncounterHost({bus:new EncounterBeatBus()});unattended.start({actorId:'player',targetId:'clown'});for(let i=0;i<4;i++)unattended.update(2);assert.equal(unattended.current.beat,'decline');});
